### ISSUE TITLE
Calendar map: Should remove button from Color Picker, since color scheme is not a feature

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1014]
Screenshot Example

![calendar_should_remove_extra_button_from_ColorPicker_since_color_scheme_not_used](https://user-images.githubusercontent.com/11938477/193653291-6de02a8c-a669-4a33-a2c2-b997062d5d3f.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, Can you please test it again and let me know if it's working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
