### ISSUE TITLE
Save Document Key modal: When number of days exceeds MAX_EXP_DAYS, it should automatically be set to equal it

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1037]
Since the user actually wanted more days, when input exceeds the maximum, it should automatically update to the MAX_EXP_DAYS value after the Alert displays.
Screenshot Example

![save_key_modal_automatically_should_set_to_MAX_EXP_DAYS_when_selected_exceeds](https://user-images.githubusercontent.com/11938477/195144324-7d8b4b2d-f6d1-405a-82c1-4ae066cc6cb1.png)

**Comment by LAlexMHllc** [comment]
See related Issue #1034

**Comment by zachegnermh** [comment]
fixed with https://github.com/MicroHealthLLC/mSuite/commit/0793ad55ef992fcbe9589c72635d13465bad8f1f
