### ISSUE TITLE
Kanban map: Should be in sync for real time collaboration

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1046]
Screenshot Example after Drag 'N Drop

![kanban_drag_n_drop_stage_should_be_in_sync_collaborator_real_time](https://user-images.githubusercontent.com/11938477/195181962-0f27b3b1-0c1e-4461-b84e-767a26fa8aae.png)

_______________________________________________________________________________________________________________________________

Screenshot Example after Update Stage Background Color

![kanban_stage_backgroundColor_should_be_in_sync_collaborator_real_time](https://user-images.githubusercontent.com/11938477/195181976-63355451-6dc6-4369-879d-0fc589fea1d8.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
