### ISSUE TITLE
DEV and QA: TreeMap, TreeChart, and FlowMap: Clicking "Add Child Node" should automatically display the new child node

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1049]
Clicking "Add Child Node" should consistently function as expected.

No child nodes displayed after clicking "Add Child Node" link several times.
Screenshot Example

![treemap_sometimes_child_node_does_automatically_display_when_clicked](https://user-images.githubusercontent.com/11938477/195198754-f6e400a8-1dd2-4050-8b4a-9b4f3a112346.png)

Then after a random number of clicks, all the Child Nodes displayed at once.
Screenshot Example

![treemap_sometimes_child_node_does_automatically_display_when_clicked_2](https://user-images.githubusercontent.com/11938477/195198858-4460f42c-7a62-486f-848a-bbc5fefaae1e.png)

**Comment by LAlexMHllc** [comment]
Closing, since fine on prod

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
