### ISSUE TITLE
DEV and QA: TreeMap, TreeChart, and FlowMap: Clicking "Delete" link should consistently delete the corresponding Child Node

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1050]
Screenshot Example

![treemap_sometimes_child_node_does_automatically_delete_when_link_clicked](https://user-images.githubusercontent.com/11938477/195201052-e8b735ff-c64a-4113-ac16-f4556690e0a7.png)

**Comment by LAlexMHllc** [comment]
Closing, since fine on prod

**Comment by LAlexMHllc** [comment]
Fix on QA - DONE
Still needs to be fixed on DEV

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it again and let me know if it is working for you

**Comment by LAlexMHllc** [comment]
Closing, fixed
