### ISSUE TITLE
QA and DEV: TreeMap - New Child Node should consistently be added to the map within its Parent

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1052]
Clicked "Add Child Node" and the new node displayed next to the main Parent node, without action links.
Screenshot Example on QA

![treemap_clicked_add_child_node_of_child__node_displayed_next_main_parent_without_button_links](https://user-images.githubusercontent.com/11938477/195207253-54c1b5da-f8a8-4c54-8c22-e8803503ae06.png)

Screenshot Example on DEV

![treemap_clicked_add_child_node_of_child__node_displayed_next_main_parent_without_button_links_2](https://user-images.githubusercontent.com/11938477/195387797-12fcea6a-0274-4299-98df-f8cfa0ee5fd0.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
