### ISSUE TITLE
Clicking "Duplicate" on Kanban should create duplicate map

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1063]
Duplicate Kanban displayed with Stages in different order.
Screenshot Example

![kanban_duplicate_file_should_display_stages_in_same_order](https://user-images.githubusercontent.com/11938477/195436533-596355fd-d6bf-43f3-9dfe-c55ab9b68411.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
