### ISSUE TITLE
the export of word number doesn't match to the midmap

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#107]
![image](https://user-images.githubusercontent.com/3675043/92658017-d556c700-f2c3-11ea-9e47-c0933c11cf7e.png)

it inserts numbers here and there which seems random in the text

Then it has 
![image](https://user-images.githubusercontent.com/3675043/92658069-ebfd1e00-f2c3-11ea-933e-2d3cbc26f29e.png)

Then it has "new idea" all over the place though deleted on the mindmap

![image](https://user-images.githubusercontent.com/3675043/92658134-0df6a080-f2c4-11ea-8a96-528decd90805.png)

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/92658364-7180ce00-f2c4-11ea-875f-9bcaf6510666.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
Screenshot Example

![mindmap_word_export](https://user-images.githubusercontent.com/11938477/153450371-d3a5a5af-3044-43e5-b633-f68990f37e8f.png)
