### ISSUE TITLE
Save Document Key number of days and "Save" button tooltip should be in sync for real time collaboration

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1073]
When a user updates the number of days till file deleted, it should update in real time on other user screen(s).
Screenshot Example

![shared_map_save_tooltip_updating](https://user-images.githubusercontent.com/11938477/195650034-1f04c57c-532d-460a-ad23-5a5bfe76d3ed.png)

![save_key_number_of_days_and_Save_button_tooltips_should_be_in_sync](https://user-images.githubusercontent.com/11938477/195650104-3397d67d-831e-41ca-b192-334c784ce615.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed, since collaborators have to reload to see updated Save tooltip and same number of days selected on Save Document Key modal

**Comment by LAlexMHllc** [comment]
Save Tooltip in sync - DONE

Number of days selected on Save Document Key modal for collaborator(s) - Still needs to be fixed

Screenshot Example of Save tooltip after another collaborator saved with updated number of days

![tooltip_date_changed_after_collaborator_saved_with_updated_number_of_days](https://user-images.githubusercontent.com/11938477/200022597-cdbab004-1ad9-43e9-8569-972e4e34c359.png)

Screenshot Example of tooltip date not in sync with number of days selected on modal for collaborator; user should not have to reload/refresh

![save_document_key_modal_number_of_days_updated_after_reload-refresh](https://user-images.githubusercontent.com/11938477/200023269-b471e270-fc86-459c-85cb-9684f5e91698.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
