### ISSUE TITLE
Number of days selected should consistently be included when Saving Map (Public or Private) or Change Password

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1074]
Sometimes when switching between Private and Public, or Change Password, the number of days is not included in the update.
Screenshot Example

![save_key_modal_consistently_update_number_of_days_even_when_switching_save_mode_or_change_pwd](https://user-images.githubusercontent.com/11938477/195656624-5bf0817f-311d-4ed7-ab17-f6df086480f7.png)

**Comment by zachegnermh** [comment]
Fixed with PRhttps://github.com/MicroHealthLLC/mSuite/pull/1124

**Comment by LAlexMHllc** [comment]
Still needs to be fixed
Screenshot Example of Save Private with 5 days selected

![save_document_key_modal_save_Private_with_default_5](https://user-images.githubusercontent.com/11938477/197820428-819c6b9c-05cd-4136-ba4f-0ff4ead736b9.png)

Screenshot Example of map saving with 180 days instead of 5

![save_document_key_modal_save_Private_with_default_5_got_180_instead_2](https://user-images.githubusercontent.com/11938477/197820500-b68c3454-aa8d-463c-9f20-63c3fa1cca1b.png)

**Comment by zachegnermh** [comment]
See https://github.com/MicroHealthLLC/mSuite/issues/1129 & https://github.com/MicroHealthLLC/mSuite/issues/1161
