### ISSUE TITLE
All Maps: Editing by and Last Edited text should be in sync for real time collaboration; also should not display for default map(s).

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1085]
Screenshot Example on QA - Poll map

![QA_Poll_map_should_not_have_editing_for_default_maps_creator_and_shared](https://user-images.githubusercontent.com/11938477/195891199-0d3ea864-045d-4262-9a4b-16b96dee65e8.png)

___________________________________________________________________________________________

Screenshot Example on DEV - Poll map

![DEV_Poll_Map_shared_map_should_not_have_Editing_text_for_default_map](https://user-images.githubusercontent.com/11938477/195891186-dbe59c21-a8f6-425a-af4d-dd0dfb959505.png)

**Comment by LAlexMHllc** [comment]
Still displays for some default shared maps.
Screenshot Example

![pollmap_user_open_shared_default_map_Last_Edited_text_should_not_display](https://user-images.githubusercontent.com/11938477/197036679-2f7aca6b-c864-4ede-9113-dddb165920ae.png)

**Comment by b-solution** [comment]
@LAlexMHll Can you please test it again and let me know.
