### ISSUE TITLE
Clicking reload/refresh on map in default state should reload the screen, instead of displaying 404 error screen.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1091]
When reload/refresh is clicked before user Save Public or Save Private on default map, then the error screen immediately displays.
When reload/refresh is clicked after user Save Public or Save Private on default map, then the screen will reload once. But when the user clicks reload/refresh again and the map is still default, then the error screen will display.

A map in default state should not be deleted UNLESS the user navigates away from the map without Save Public or Save Private, not for reload/refresh.

Screenshot Example

![404_error_screen_displays_after_reload-refresh_clicked](https://user-images.githubusercontent.com/11938477/195918001-ffbc655c-8166-4390-93e5-c123c78607e5.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Closing, since 404 screen does not display for map in default state after user Save Public/Private
