### ISSUE TITLE
All Maps: PASSWORD modal should not display for map that was not Save Private

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1092]
Screenshot Example of map created, reload/refresh clicked before Save map

![index_click_map_box_open_click_reload-refresh_before_Save](https://user-images.githubusercontent.com/11938477/195920555-435bacb0-404f-4bee-8a15-87e59040012f.png)

Screenshot Example of PASSWORD modal that displayed after reload/refresh clicked for map that was not Save Private

![index_click_map_box_open_click_reload-refresh_before_Save__Password_modal_displayed](https://user-images.githubusercontent.com/11938477/195920672-53058f75-13c5-4ed9-b7ea-12e3e81f4a0c.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
