### ISSUE TITLE
Mindmap: Newly drawn child node not connected, even after reload/refresh

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1097]
Screenshot Example

![mindmap_child_node_not_connected_even_after_reload](https://user-images.githubusercontent.com/11938477/196204763-80f8dbbe-0962-41c0-811b-94746d75df64.png)

**Comment by LAlexMHllc** [comment]
Closing, since this was the only instance

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
