### ISSUE TITLE
QA and Beta - TreeMap: Clicking "Add Child Node" should only create a single Child Node (with a unique default Title) that corresponds to itself.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1099]
After another sibling was added with default duplicate Title, when "Add Child Node" was clicked on one of the duplicates, a child was added to each (both with duplicate Title as well).

Screenshot Example

![treemap_clicked_Add_child_Node_when_one_child_exists](https://user-images.githubusercontent.com/11938477/196224470-9f7f41c3-7593-4703-b1e1-24feda44a551.png)

Screenshot Example of child node added with existing Title

![treemap_clicked_Add_child_Node_created_child_with_duplicate_Name](https://user-images.githubusercontent.com/11938477/196225483-57d78b77-bf77-4f4f-a40b-5966f9d92dc0.png)

Screenshot Example of clicking "Add Child Node"

![treemap_clicked_Add_child_Node_when_one_child_exists_click_Add_Child_Node_on_a_duplicate](https://user-images.githubusercontent.com/11938477/196225498-bcb1329e-0fdc-47c7-bf31-6605053922fd.png)

Screenshot Example of an extra Child Node added to the map, but under the sibling with the duplicate Title

![treemap_clicked_Add_child_Node_when_one_child_exists_click_Add_Child_Node_on_a_duplicate_2](https://user-images.githubusercontent.com/11938477/196225534-b2fa6663-a540-4707-bdf0-a6e7b90396a7.png)

**Comment by b-solution** [comment]
@LAlexMHllc  I've fixed this issue, can you please test it again and let me know if it's not working.
