### ISSUE TITLE
QA and Beta - TreeMap: Edit node Title should have updated the edited node, not another node.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1100]
Screenshot Example of nodes with duplicate default Title

![treemap_child_node_added_with_duplicate_Name](https://user-images.githubusercontent.com/11938477/196232897-cd9471a3-0f94-481d-a72c-52e16b7a8dd9.png)

Screenshot Example of Edit Node Title

![treemap_child_node_added_with_duplicate_Name_edit_duplicate_Name](https://user-images.githubusercontent.com/11938477/196232905-4a393986-9704-40d1-a576-68bc4d966139.png)

Screenshot Example Title updating the unedited Node

![treemap_child_node_added_with_duplicate_Name_edit_duplicate_Name_updated_wrong_node](https://user-images.githubusercontent.com/11938477/196232913-cd03e35c-a799-4cf4-8635-ca9167c24c22.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Fixed on QA
