### ISSUE TITLE
DEV TreeChart and FlowMap: New node should consistently be given default Title; node Title should update with user input instead of default Title.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1105]
Screenshot Example 

![DEV_TreeChart_node_not_automatically_filled_with_default_Title_should_update_user_input_instead_default_Title](https://user-images.githubusercontent.com/11938477/196468242-3910699a-2682-4f5b-8a97-c657fdb2dace.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Please test it again and tell me if it is working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
