### ISSUE TITLE
Duplicate Map should include Replies to Comments

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1108]
Screenshot Example of Comments with Replies on original map

![map_Comments_with_Replies](https://user-images.githubusercontent.com/11938477/196507501-8a4d6617-6ea1-428f-91a1-b784aa6e3b96.png)

Screenshot Example of Duplicate clicked

![map_Comments_with_Replies_click_Duplicate](https://user-images.githubusercontent.com/11938477/196507527-b9246ca0-fe94-48a9-88d8-f65189c812b5.png)

Screenshot Example of Duplicate Map missing Replies to Comments

![duplicate_map_missing_Replies_to_Comments](https://user-images.githubusercontent.com/11938477/196507625-1ee3a06f-de6e-464e-b5f6-f615dbc9cf75.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
