### ISSUE TITLE
User should not be able to access/update/delete/reset/duplicate/save a map that is Save Private without verifying Password

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1114]
Screenshot Example of user Save Private map

![user_create_map_Save_Private_clicked](https://user-images.githubusercontent.com/11938477/197005531-3de77d8b-87ee-402e-adb3-25d6e8027414.png)

![user_create_map_Save_Private_clicked_2](https://user-images.githubusercontent.com/11938477/197005544-3e4e5347-85a3-42b8-a793-69aff6c4545c.png)

______________________________________________________________________________________

Screenshot Example of User with access to URL (without Password) closed PASSWORD modal instead of input/verify Password

![Save_Private_map_as_Save_Public_without_document_key_1](https://user-images.githubusercontent.com/11938477/197011400-07997fd2-ac1d-4475-9e80-9a68122dfa3a.png)

___________________________________________________________________________________________

User should not be able to Save Private map as Save Public map without document key
Screenshot Example after user clicks "Save" button, then clicks "Save Public" OR user clicks Logo, then "Save Public", then reopens map.

![Save_Private_map_as_Save_Public_without_document_key_2](https://user-images.githubusercontent.com/11938477/197007899-73fbcd53-4369-4b45-92df-f3f629dee34b.png)

![Save_Private_map_as_Save_Public_without_document_key_3_reload](https://user-images.githubusercontent.com/11938477/197009577-e4ccd053-c0e6-4b83-92f4-e8adb447ef91.png)

![Save_Private_map_as_Save_Public_without_document_key_4](https://user-images.githubusercontent.com/11938477/197012079-54eb2af4-d098-4b97-a3d9-328c635d6ec9.png)

______________________________________________________________________________________________________________

Unless the map creator reloads/refreshes the screen or closes/reopens the map, they do not know the map is now Save Public
Screenshot Example

![Save_Private_map_as_Save_Public_without_document_key_5_delete_for_both](https://user-images.githubusercontent.com/11938477/197015358-37e70c6f-3855-456d-8ffd-8cf59faf9299.png)

Screenshot Example of user without map Password is able to delete the map

![Save_Private_map_as_Save_Public_without_document_key_6_delete_clicked](https://user-images.githubusercontent.com/11938477/197015956-4176e921-c738-479a-8b0e-68bfd1f0910a.png)

![Save_Private_map_as_Save_Public_without_document_key_7_delete_by_user_without_password](https://user-images.githubusercontent.com/11938477/197016213-f9d32e28-fcdf-49b7-96d3-e4f9fe0d138e.png)

**Comment by LAlexMHllc** [comment]
User without Password for Save Private map should not be able to Comment/Reply
Screenshot Example

![user_without_Password_should_not_be_able_Comment_Reply](https://user-images.githubusercontent.com/11938477/197019551-1b4ee34c-76d6-4445-8e6a-538fea93939b.png)

**Comment by LAlexMHllc** [comment]
User without Password for Save Private map should not be able to Reset map
Screenshot Example

![user_without_Password_should_not_be_able_Reset_map_1](https://user-images.githubusercontent.com/11938477/197021923-2d5a1f90-7ca6-4090-91b5-299c92474120.png)

![user_without_Password_should_not_be_able_Reset_map_2](https://user-images.githubusercontent.com/11938477/197021963-2056cddc-41ff-478c-9cd2-4edc0dbdf966.png)

**Comment by LAlexMHllc** [comment]
User without Password for Save Private map should not be able to duplicate the map. The user that Saved Private map does not know the map was duplicated, then accessed.

Screenshot Example of user Duplicate Save Private map, then after changing to Save Public, was able to access the copy

![user_without_Password_should_not_be_able_Duplicate_map_1](https://user-images.githubusercontent.com/11938477/197024947-f7cfc731-0ef0-4a27-ae63-3bc5ae2f5afe.png)

![user_without_Password_should_not_be_able_Duplicate_map_2](https://user-images.githubusercontent.com/11938477/197024962-d8a32cfa-7dff-4024-b49d-79e720fdb9df.png)

**Comment by zachegnermh** [comment]
fixed with PR https://github.com/MicroHealthLLC/mSuite/pull/1116

**Comment by zachegnermh** [comment]
See PR https://github.com/MicroHealthLLC/mSuite/pull/1126

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
