### ISSUE TITLE
Password requirement should be 8 nonblank characters minimum

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1136]
Screenshot Example

![password_requirement_should_be_8_nonblank_characters_minimum](https://user-images.githubusercontent.com/11938477/198052614-66b29a85-0181-4fdb-a718-b02334a3e510.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've worked on it, Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
