### ISSUE TITLE
Mindmap: New node should have been child of another node

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1137]
User dragged from Central Idea node, but it was attached to another node. Notice the different color connector line from its parent.
Screenshot Example

![mindmap_new_node_should_have_been_central_Idea_child](https://user-images.githubusercontent.com/11938477/198082583-8ce070e3-b562-4670-beb4-d3d39d804be9.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
