### ISSUE TITLE
Mindmap: Save Private map (without default content) should not get automatically deleted after reload/refresh OR collaborator clicks "Verify" on Password modal.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1139]
Screenshot Example of Save Private when not default map

![mindmap_save_private_after_edit_node_text](https://user-images.githubusercontent.com/11938477/198114688-e252d9ef-7567-4a5c-928a-f285a9090014.png)

Screenshot Example of 404 Error screen after reload/refresh

![mindmap_save_private_after_edit_node_text__click_reload_404_error](https://user-images.githubusercontent.com/11938477/198114824-0bd70926-44e2-4851-acd3-e80fb4a471af.png)

_________________________________________________________________________________

Collaborator input correct Password, then clicks "Verify"
Screenshot Example

![mindmap_share_url_with_pw_map_deleted_one_screen_index_the_other_404_error_1](https://user-images.githubusercontent.com/11938477/198109632-3375c4dc-6e73-4799-93fa-687c20000436.png)

![mindmap_share_url_with_pw_map_deleted_one_screen_index_the_other_404_error_2](https://user-images.githubusercontent.com/11938477/198109661-7b9cdcd4-acf2-41e6-98a3-f0877b25d6e0.png)

**Comment by LAlexMHllc** [comment]
NOTE: This does not seem to happen whenever the map is first Save Public, then changed to Save Private.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Please test it and let me know if it is working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
