### ISSUE TITLE
*hot scroll bars are missing from kanban

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#1140]
![image](https://user-images.githubusercontent.com/3675043/198121946-a1a675ad-bf76-4633-a6f5-6c712de151ba.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example of horizontal scrollbar not visible at 90% zoom

![kanban_horizontal_scrollbar_not_visible_at_90_percent_zoom](https://user-images.githubusercontent.com/11938477/198338545-613306fe-acbd-4ee3-ab87-c7306cfd2ab6.png)


Screenshot Example of horizontal scrollbar barely visible at 80% zoom

![kanban_horizontal_scrollbar_barely_visible_at_80_percent_zoom](https://user-images.githubusercontent.com/11938477/198338563-50275fe6-ce6e-436a-9c71-ece780b6e03b.png)

**Comment by LAlexMHllc** [comment]
@bluenevus Horizontal scrollbar visible for you?

**Comment by LAlexMHllc** [comment]
Closing, fixed
