### ISSUE TITLE
ToDo: Switch to Calendar dates should display the same as ToDo dates, instead of one day earlier

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1150]
Screenshot Example

![todo_click_switch_to_calendar](https://user-images.githubusercontent.com/11938477/198370355-88e075ff-3b9f-4068-94ff-14715bf47141.png)

![todo_click_switch_to_calendar_should_match_toDo_instead_of_one_day_earlier](https://user-images.githubusercontent.com/11938477/198370510-46b0c142-ce46-4620-a31e-f326bd52d1b7.png)

**Comment by b-solution** [comment]
@LAlexMHllc check it again and let me know if it is working for you.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.

Screenshot Example of ToDo List before Switch to Calendar

![todo_click_switch_to_calendar_2](https://user-images.githubusercontent.com/11938477/199297222-d4e7bf39-59d4-4aba-8c36-1b0acbb066e1.png)

Screenshot Example of Calendar with dates one day earlier

![todo_click_switch_to_calendar_should_match_toDo_instead_of_one_day_earlier_2](https://user-images.githubusercontent.com/11938477/199297429-1e89c659-961c-4f0f-9252-2f4eb9481131.png)

Screenshot Example after Update date for ToDo Task

![todo_click_switch_to_calendar_Update_task_date_click_Switch_ToDo_button](https://user-images.githubusercontent.com/11938477/199297736-bc5223b5-218a-46fd-911e-311e7fbbd279.png)

Screenshot Example after Switch to ToDo
The ToDo with the Update date displays correctly, and the other ToDos still display with the selected ToDo List dates

![todo_click_switch_to_ToDo_after_Update_ToDo_task](https://user-images.githubusercontent.com/11938477/199298622-9454b545-d5de-4889-adce-74c300e1650e.png)

Screenshot Example after Switch to Calendar again
The ToDo task that was updated on the Calendar displays on the correct date, but the other ToDo tasks still display a day earlier

![todo_click_switch_to_calendar_Update_task_date_click_Switch_ToDo_button_2](https://user-images.githubusercontent.com/11938477/199299749-b32ef522-21f3-4c40-9e10-d68eb4ac32ce.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it and tell me if it is working for you.
