### ISSUE TITLE
ToDo map: Complete ToDo function should stick; should not change child ToDo to parent ToDo.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1153]
Screenshot Example before checking child ToDo complete

![todo_list_without_any_task_complete_strikethrough](https://user-images.githubusercontent.com/11938477/198380660-69fd94ab-cead-4a50-b5b4-8e235dfcfe01.png)

Screenshot Example just for a second after child ToDo checked complete; the box is checked and the text style is strikethrough (CORRECT)

![todo_list_without_any_task_complete_strikethrough__check_box_complete](https://user-images.githubusercontent.com/11938477/198381041-cc9cec39-d7ea-4ec8-9fbf-3657d939d930.png)

Screenshot Example of child ToDo that was checked complete, automatically became unchecked parent ToDo (INCORRECT)

![todo_list_without_any_task_complete_strikethrough__check_box_complete__became_unchecked_parent_do_do](https://user-images.githubusercontent.com/11938477/198381225-060f933f-4768-4e1b-9f7d-a5755ce6b3eb.png)

__________________________________________________________________________________________________________

Screenshot Example before checking parent ToDo complete

![todo_list_before_checking_parent_todo_complete](https://user-images.githubusercontent.com/11938477/198382893-fc721f66-43b7-41ef-a19b-444a488222a9.png)

Screenshot Example just for a second after parent ToDo checked complete; the box is checked and the text style is strikethrough (CORRECT)

![todo_list_after_checking_parent_todo_complete](https://user-images.githubusercontent.com/11938477/198383035-13ebfe24-c832-4739-84ca-abec17dc489c.png)

Screenshot Example of parent ToDo that was checked complete, automatically became unchecked (INCORRECT)

![todo_list_after_checking_parent_todo_complete_did_not_stick](https://user-images.githubusercontent.com/11938477/198383061-cc39ac1a-5558-460c-a167-c6373554f399.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Please test it and let me know if it is working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
