### ISSUE TITLE
Poll collaborators screen: Poll URL with copy button/function should remain accessible for non-expired Poll

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1165]
Currently, after the Poll is launched, the Poll URL with copy button no longer displays. Poll collaborators should still be able to access the Poll URL from the map screen, until the poll expires.
Screenshot Example

![poll_results_should_include_Poll_URL_with_copy_button](https://user-images.githubusercontent.com/11938477/199282181-4441cbcb-d371-47a4-b335-5fb50facb1c0.png)

**Comment by zachegnermh** [comment]
@LAlexMHllc Hi, would you please provide a screenshot of the URL when it is not displaying.

**Comment by LAlexMHllc** [comment]
Closing, fixed
