### ISSUE TITLE
DEV - Save Document Key modal missing "Change Password" button for Save Private map

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1179]
Screenshot Example

![save_document_key_modal_missing_Change_Password_button_when_map_is_Save_Private](https://user-images.githubusercontent.com/11938477/199775127-9f25c5e6-6f1a-4472-8618-f98f628b4d1f.png)

**Comment by b-solution** [comment]
Hi @zachegnermh i hope you are doing well. I've checked this modal and you are working on it i've seen some issues like that when click on **Save Map & Save Private** multiple times request generates. I think you may have to figure it out to solve this issue.

**Comment by LAlexMHllc** [comment]
Closing, fixed
