### ISSUE TITLE
Mindmap: Arm should not display after its node is removed; should not have to reload/refresh

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1193]
Screenshot Example

![mindmap_arm_should_not_display_after_its_node_is_removed_should_not_have_to_reload](https://user-images.githubusercontent.com/11938477/200362119-3112cd16-6a20-48fd-92f3-459a0d8f09ab.png)

**Comment by b-solution** [comment]
Fixed
