### ISSUE TITLE
Poll Vote: Should not be able to check more than Allowable selectable options. Clicking "Reset" should reset the form.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1207]
Even though the form will not pass validation when Submit is clicked, the user should still not be able to select more than allowable options. After the maximum number of boxes are checked, the other checkboxes should become disabled, like Poll Preview.
Screenshot Example

![poll_vote_should_not_be_able_check_more_than_allowable_options_clicking_reset_should_function](https://user-images.githubusercontent.com/11938477/200891559-18e2db73-7490-470e-bb5e-4a1b952d3ff0.png)

**Comment by zachegnermh** [comment]
@LAlexMHllc I can't seem to reproduce this, is there certain steps I should take to see this?

**Comment by LAlexMHllc** [comment]
Closing, since it happened when collaborating, and have not able to reproduce
