### ISSUE TITLE
Poll Map: "EDIT" button should automatically display after map is reset AND before poll vote input exists

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1209]
Currently, user has to reload/refresh for the "EDIT" button to display.

Screenshot Example

![poll_map_click_Reset_Poll](https://user-images.githubusercontent.com/11938477/200925074-f2fe52c7-3901-4bf6-8061-c2fcf314b1f4.png)

![poll_map_missing_EDIT_after_Poll_Reset_click_reload](https://user-images.githubusercontent.com/11938477/200925103-276af19a-1d76-4b09-9263-0d628e48670b.png)

![poll_map_missing_EDIT_after_Poll_Reset_displayed_after_reload](https://user-images.githubusercontent.com/11938477/200925168-1df30c4e-c40e-40cf-a7b6-1c1bea5834c3.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it and tell me if it is working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
