### ISSUE TITLE
Spreadsheet map: "Duplicate" map should function

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1215]
"Duplicate" Save Private map gets deleted (Error screen 404 displays) after successful "Verify" Password.

Screenshot Example of Spreadsheet that is Save Private

![spreadsheet_Saved_Private](https://user-images.githubusercontent.com/11938477/201152337-646fefde-36c1-4b0e-a122-6a7ec1586a98.png)

Screenshot Example of click "Duplicate" on Save Private spreadsheet

![spreadsheet_Saved_Private_click_Duplicate](https://user-images.githubusercontent.com/11938477/201152977-03a908ef-1657-44bb-9881-18f545aef182.png)

Screenshot Example of user input correct Password, then click "Verify" on duplicate spreadsheet

![spreadsheet_Saved_Private_click_Duplicate_Verify_Password_on_Duplicate](https://user-images.githubusercontent.com/11938477/201153725-36e4f668-1ee4-4acc-8d87-3bbb827ae4d2.png)

Screenshot Example of Error 404 screen after file was automatically deleted after "Verify" Password

![spreadsheet_Saved_Private_click_Duplicate_Verify_Password_on_Duplicate_Error-404_file_deleted](https://user-images.githubusercontent.com/11938477/201154388-8b29fecb-3c37-4c99-a7f0-007a2fdc0c8b.png)

**Comment by LAlexMHllc** [comment]
"Duplicate" Save Public map is missing spreadsheet content.

Screenshot Example of Saved Public Spreadsheet

![spreadsheet_Saved_Public](https://user-images.githubusercontent.com/11938477/201157104-e6e5b0aa-05dd-443d-9770-c8509960a5bd.png)

Screenshot Example of clicking "Duplicate"

![spreadsheet_Saved_Public_click_Duplicate](https://user-images.githubusercontent.com/11938477/201157122-bd306e0a-eb7c-4bf6-9b1b-36ae396cddfd.png)

Screenshot Example of Duplicate map missing spreadsheet content

![spreadsheet_Saved_Public_Duplicate_missing_spreadsheet_content](https://user-images.githubusercontent.com/11938477/201157141-571cfd0d-15ce-4f80-b705-53ae41c50d71.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
