### ISSUE TITLE
Whiteboard map: "Duplicate" map should function

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1216]
"Duplicate" map from Save Private map; input correct Password for duplicate, then click "Verify"; the Error 404 screen displays (file was deleted).
"Duplicate" map from Save Public map; duplicate map missing whiteboard content.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working for you.
