### ISSUE TITLE
Poll map: "Duplicate" map should function

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1218]
"Duplicate" map from Save Private map; input correct Password for duplicate, then click "Verify"; the Error 404 screen displays (file was deleted).
"Duplicate" map from Save Public map; duplicate map missing all Form content (Incorrect), except it does get a new URL (Correct).

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
