### ISSUE TITLE
Mindmap: New node should have been child of Central Node instead of another node

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1246]
Screenshot Example

![mindmap_new_node_should_have_been_central_Idea_child_2](https://user-images.githubusercontent.com/11938477/203088141-587712c4-58c3-4894-906d-7ec72b3a7033.png)

**Comment by LAlexMHllc** [comment]
NOTE: Same as closed Issue #1137

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
