### ISSUE TITLE
Poll Vote answers should not be in sync after a voter "SUBMIT" when multiple users take Poll Vote at the same time.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1252]
Clicking "SUBMIT" should not automatically update another poll voter's answers in real time. Only the answers a poll voter chooses should remain selected.

ISSUE EXAMPLE
Separate voters taking Poll Vote at the same time. The answers are not the same, when one voter clicks Submit.
After successful Submit, the answer on the other screen automatically updated to match the answer that was submitted.

Screenshot Example 

![poll_vote_screen_multi-voter_collaboration_Submit_clicked](https://user-images.githubusercontent.com/11938477/203367012-932df7b0-aedb-44fe-b2b3-59207c668a16.png)

![poll_vote_screen_multi-voter_collaboration_Submit_clicked_2](https://user-images.githubusercontent.com/11938477/203367035-f155cb8b-0288-419c-83cc-62d3c1f20d19.png)

**Comment by b-solution** [comment]
Hi @LAlexMHllc, If user has already voted then if he changes his name he cannot vote again. If you go in another account or Incognito then you can vote with a new voter.

**Comment by LAlexMHllc** [comment]
Closing, since the forms are no longer in sync, but other issues exist now.
See new related Issue #1281
