### ISSUE TITLE
ToDo: Sometimes a todo Title does not display correctly after delete then Undo/Redo; sometimes missing Date.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1254]
Screenshot Example after delete then Undo

![ToDo_Title_did_not_display_correctly_after_delete_Undo](https://user-images.githubusercontent.com/11938477/203396426-63138fa9-ed10-4fc7-af9e-3c75515aa2ee.png)

________________________________________________________________________________________

Screenshot Example after delete then Redo

![ToDo_Title_did_not_display_correctly_after_delete_Redo](https://user-images.githubusercontent.com/11938477/203396439-8abdf281-69ae-4fb8-bef0-06a44375a9fe.png)

___________________________________________________________________________________________

Screenshot Example of Date missing after Undo delete item

![ToDo_Date_missing__after_Undo_delete](https://user-images.githubusercontent.com/11938477/203399216-830667a6-275f-4e5f-af89-03a798b5c227.png)

**Comment by LAlexMHllc** [comment]
After update, the Date is still missing and delete/undo

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it again and tell me if it is working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
