### ISSUE TITLE
DEV TreeChart and FlowMap: New node should consistently be given default Title; node Title should update with user input instead of default Title.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1257]
Closed Issue #1105 returned

**Comment by b-solution** [comment]
> Closed Issue #1105 returned

@LAlexMHllc Can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Both maps still need to be fixed.

Screenshot Example of TreeChart

![treechart_node_Title_should_automatically_be_given_default_Title](https://user-images.githubusercontent.com/11938477/209707965-0420a888-3a1c-4928-a597-6a3dccd6e770.png)


Screenshot Example of FlowMap

![flowmap_node_Title_should_automatically_be_given_default_Title](https://user-images.githubusercontent.com/11938477/209707979-4776f817-4c06-4b14-bb2e-239f7ed0da1a.png)

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
