### ISSUE TITLE
Should include Contact link for user to get assistance when file is permanently locked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1258]
Screenshot Example

![file_permanently_locked](https://user-images.githubusercontent.com/11938477/203597665-918df295-7853-4943-89c2-2a56f80ad9b5.png)

**Comment by bluenevus** [comment]
I'm not sure I want to be in the business of unlocking locked maps due to failed passwords.  Its encrypted for a reason meaning, we just can't undo this
