### ISSUE TITLE
Pivot Tables: Total markers on graphs should not be less than graphic markers

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1259]
Spreadsheet and Poll Results
Screenshot Example

![spreadsheet_graph_Totals_should_not_be_less_than_graph_markers](https://user-images.githubusercontent.com/11938477/203611490-3c20731f-3d0d-49ea-90c1-0906bff1b4b7.png)

Screenshot Example of how it should look

![spreadsheet_graph_Totals_should_not_be_less_than_graph_markers_2](https://user-images.githubusercontent.com/11938477/203611502-be3cbf34-dd6c-457c-99dd-e5909113c4e7.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![spreadsheet_graph_Totals_should_not_be_less_than_graph_markers_3](https://user-images.githubusercontent.com/11938477/203619661-e56cda75-2726-416e-a89f-1a768fc46e32.png)


Screenshot Example of how it should look

![spreadsheet_graph_Totals_should_not_be_less_than_graph_markers_4](https://user-images.githubusercontent.com/11938477/203619687-e1912ae5-ec8e-4c31-ae83-bda6c37cbec4.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've gone through  [Plotly](https://plotly.com/javascript/bar-charts/#basic-bar-chart) JS and came to know that there is limitation in graph every data will be in corresponding axis and there will be no line created forward therefore it's not possible to create an extra line.

**Comment by LAlexMHllc** [comment]
Closing, as won't fix
