### ISSUE TITLE
Mindmap: Copy/Cut/Paste/Delete buttons should not be enabled when a node is not selected

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1263]
Clicked Copy with node selected, clicked the background, clicked Paste without node selected. Orphan node was created.
Screenshot Example of Copy/Paste without a node selected

![mindmap_paste_without_node_selected_after_copy_click_background_click_paste](https://user-images.githubusercontent.com/11938477/204019374-62381093-4132-4c47-a6c4-be2b439b169f.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example of Cut/Paste without node selected; created orphan.

![mindmap_paste_without_node_selected_after_cut__paste_without_node_selected](https://user-images.githubusercontent.com/11938477/204021404-5cad5f3b-47fd-4134-94ca-5d27ad57996e.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
