### ISSUE TITLE
Poll Map: Clicking "+" should consistently function when the value is less than Allowable selectable options.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1296]
Sometimes clicking "+" does not function.
Screenshot Example

![poll_clicking_increase_allowable_selectable_options_should_consistently_function](https://user-images.githubusercontent.com/11938477/206731880-20f7b57c-947c-40bf-894e-b1c56cf583bf.png)

Screenshot Example where one increased and the other did not

![poll_clicking_increase_allowable_selectable_options_should_consistently_function_2](https://user-images.githubusercontent.com/11938477/206733933-b1a528c8-b8af-43f3-9b17-fbce1875ca3c.png)

**Comment by b-solution** [comment]
@LAlexMHllc This is working fine on my side. Can you test it again?

**Comment by LAlexMHllc** [comment]
Closing, fixed
