### ISSUE TITLE
Map Title should consistently display legibly

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1298]
Screenshot Example when Title is not legible

![poll_map_Title_did_not_display_legible](https://user-images.githubusercontent.com/11938477/206739978-6f3eb740-b987-44b6-848c-ec5e30842991.png)

Screenshot Example when Title is legible on the same map

![poll_map_Title_did_not_display_legible_2](https://user-images.githubusercontent.com/11938477/206740568-1e50be88-406e-446a-8bc3-d90c503dc31d.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
