### ISSUE TITLE
Venn Diagram: Should validate form when submit is clicked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1316]
Screenshot Example

![venn_diagram_should_validate_form_when_submit_clicked](https://user-images.githubusercontent.com/11938477/207119774-7d7c5c11-6d27-4713-9789-c03e68be3100.png)

Should also validate:
- Enter sets with commas: should not be blank; when input separate names by commas, names should exist.
- When filled in, Enter Name of New Set should be unique
- The number selected > 0. Should probably have 1 as the lowest number, since 0 will not display a circle.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it again and let me know if it is working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed

**Comment by LAlexMHllc** [comment]
Should validate:
- Enter sets with commas: when input separate names by commas, names should exist.
- When filled in, Enter Name of New Set should be unique
- Size selector should have 1 as the lowest number, since 0 will not display a circle and cause validation error.

**Comment by LAlexMHllc** [comment]
Closing, since Venn design/function to be redone
