### ISSUE TITLE
Kanban map: Clicking "Add a Task" should consistently display new task box on stage

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1317]
Sometimes there is a delay, and sometimes have to reload to view updates after Add a Task link is clicked

**Comment by LAlexMHllc** [comment]
After last update, still does not consistently function.

**Comment by zachegnermh** [comment]
@b-solution I tested this locally, and it works fine. I think it may be an issue with websockets on a prod server. I see a few similar issues

**Comment by zachegnermh** [comment]
Closing
