### ISSUE TITLE
Mindmap: Cutting a node should consistently remove the node AND its descendants

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1323]
Screenshot Example

![mindmap_cutting_node_should_consistently_delete_node_and_its_children_grands](https://user-images.githubusercontent.com/11938477/208455195-9c267ac3-644a-408d-9bd4-9d5aea04b583.png)

![mindmap_cutting_node_should_consistently_delete_node_and_its_children_grands_2](https://user-images.githubusercontent.com/11938477/208455207-29c7fdd4-1974-4a57-a933-70a23be64653.png)

**Comment by b-solution** [comment]
@LAlexMHllc this is working fine on our side. Kindly test it again and if the issue persists make steps so that in a way we can figure out the issue.

**Comment by b-solution** [comment]
@zachegnermh will you please test it on your side?

**Comment by LAlexMHllc** [comment]
Step 1: Add several nodes to the Mindmap
Step 2: Select a node with descendants
Step 3: Click the "Cut" button with the node still selected
Screenshot Example

![mindmap_step_1_selected_a_node_with_descendants_then_clicked_Cut_button](https://user-images.githubusercontent.com/11938477/208693177-6bc35575-fd8f-406b-bdbf-5f653031d205.png)

![mindmap_step_1_selected_a_node_with_descendants_then_clicked_Cut_button_2_descendants_remained](https://user-images.githubusercontent.com/11938477/208693210-23f7a9f9-81f3-4ac2-a117-42b77ea152e0.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example where the node was Cut, but its arm and descendants remained

![mindmap_example_2_selected_a_node_with_descendants_then_clicked_Cut_button](https://user-images.githubusercontent.com/11938477/208696489-10c5fba3-bec0-443a-b13d-aff0b62d9715.png)

![mindmap_example_2_selected_a_node_with_descendants_then_clicked_Cut_button__arm_and_descendants_remained](https://user-images.githubusercontent.com/11938477/208696518-9a2f03fa-30bf-4086-b0db-34ddb5ca72b1.png)


NOTE: See closed Issue #1313, except in this example the node cut has descendants

**Comment by b-solution** [comment]
@LAlexMHllc I'v fixed this issue, can you please test it again and let me know.
