### ISSUE TITLE
as a user I would like to build an tree map as a type of mindmap

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#135]
just like this 

![image](https://user-images.githubusercontent.com/3675043/130166158-b08fb9ed-6229-4038-89b7-b53344d2e5cd.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/147776930-d976c9dd-1e64-48f7-8932-739cd131e532.png)
