### ISSUE TITLE
Save Document Key modal AND Password Protect modal should consistently display/function correctly for Save Public map.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1351]
After changing map from Save Private to Save Public, sometimes when the Save Document Key modal is reopened, it still displays as Save Private map. Regardless if it displays correctly or not, when the "Save Private" button is clicked, the Password Protect modal displays as Save Private map instead of Save Public map. User should not have to reload/refresh for both modals to display correctly.

Screenshot Example

![save_document_key_modal_and_password_protect_should_consistently_display_correctly_for_Save_Public_map](https://user-images.githubusercontent.com/11938477/209984936-efa307ac-2f66-4545-8a18-1c027e95f943.png)

**Comment by LAlexMHllc** [comment]
Should not have to input Password to delete Save Private map changed to Save Public map. Should not have to reload/refresh.

Screenshot Example

![should_not_have_to_input_Password_to_delete_map_changed_from_Save_Private_to_Save_Public](https://user-images.githubusercontent.com/11938477/209992194-5691f40e-fa27-427c-b5a0-21ad632a4502.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Seems to be fixed for "Change Password" button not displaying after Saved Public, but after confirming "Delete" the Password prompt still displays instead of automatically deleting the map unless user had reload/refresh.

Screenshot Example

![change_Save_Private_map_to_Save_Public_map_1](https://user-images.githubusercontent.com/11938477/210396215-3217b218-b2b1-4722-88a8-bee0cc4306f4.png)

![change_Save_Private_map_to_Save_Public_map_2](https://user-images.githubusercontent.com/11938477/210396227-491f00e8-e359-43b0-bf67-0ded578951a4.png)

![change_Save_Private_map_to_Save_Public_map_3](https://user-images.githubusercontent.com/11938477/210396243-56cef377-0551-4fb4-9d8a-b45b265b76fc.png)

![change_Save_Private_map_to_Save_Public_map_4](https://user-images.githubusercontent.com/11938477/210396254-6486ea24-8765-440e-96b2-2d9c319e6d5a.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it with latest code because it's working good on my side.

**Comment by LAlexMHllc** [comment]
Closing, fixed
