### ISSUE TITLE
Mindmap: Sometimes node disappears after Edit Node Title

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1352]
Screenshot Example

![mindmap_edit_node_Title](https://user-images.githubusercontent.com/11938477/209987932-3ae27031-15b5-434a-a4ce-c69f2e81de5e.png)

![mindmap_edit_node_Title_node_disappeared](https://user-images.githubusercontent.com/11938477/209987943-386afdef-1c8e-4204-b8bc-ee90908f288b.png)

**Comment by b-solution** [comment]
@LAlexMHllc I tested this locally, and it works fine. I think it may be an issue with websockets on a prod server.
