### ISSUE TITLE
Mindmap: Triple click when node is active should not remove the node

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1354]
Screenshot Example

![mindmap_before_node_selected](https://user-images.githubusercontent.com/11938477/209989204-35635c8c-07f3-4fac-9832-af5222acbc96.png)

![mindmap_after_node_selected_before_triple_click](https://user-images.githubusercontent.com/11938477/209989211-84ace51a-f605-48e9-aaa2-f4381e329438.png)

![mindmap_after_node_selected_after_triple_click_disappeared](https://user-images.githubusercontent.com/11938477/209989223-95dd6413-978e-438e-81d0-51e714514aac.png)

**Comment by LAlexMHllc** [comment]
Sometimes after another action, the node that disappeared will reappear.
Sometimes after another action, the arm will also automatically disappear.

**Comment by b-solution** [comment]
@LAlexMHllc I tested this locally, and it works fine. I think it may be an issue with websockets on a prod server.
