### ISSUE TITLE
Mindmap: Node should not automatically disappear after drag 'n drop

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1356]
Screenshot Example before drag 'n drop

![mindmap_selected_node_before_drag_n_drop](https://user-images.githubusercontent.com/11938477/209993565-fe37f298-7e1f-4650-b418-cfecf0a32910.png)

Screenshot Example of node removed after drag 'n drop

![mindmap_node_after_drag_n_drop_automatically_disappeared](https://user-images.githubusercontent.com/11938477/209993571-15c75a86-b3cc-4f70-a949-23e96b0d7c81.png)

Screenshot Example after orphan arm automatically removed after another node selected

![mindmap_node_after_drag_n_drop_automatically_disappeared_orphan_arm_disappeared_after_another_node_selected](https://user-images.githubusercontent.com/11938477/209994004-001af92c-3551-4b8f-9b22-18f382968cf3.png)

Screenshot Example of user drawing another node

![mindmap_node_after_drag_n_drop__user_drawing_another_node](https://user-images.githubusercontent.com/11938477/209994377-b1d24bbd-197c-4b3d-b191-ff831fd8cdb7.png)

Screenshot Example of removed node automatically reappearing after new node added

![mindmap_node_after_drag_n_drop__user_drawing_another_node_removed_node_reappeared](https://user-images.githubusercontent.com/11938477/209994399-5cf3cae2-f59a-4ae8-87b8-08c2fe0fdde3.png)

**Comment by b-solution** [comment]
@LAlexMHllc I tested this locally, and it works fine. I think it may be an issue with websockets on a prod server.
