### ISSUE TITLE
[Kanban] Unable to open

### ISSUE THREAD

**Issue by andrewtran249** [MicroHealthLLC/mSuite#1374]
I am unable to open a new kanban. When attempting to open from the homepage, I am brought to a screen that shows it was previously edited by a user. (see top image)

A different team member attempted to open a kanban and received an error from the homescreen (see bottom image)

![2023_01_05 mSuite Kanban Error](https://user-images.githubusercontent.com/106859528/210816705-ffc9ac2c-d18c-4ea9-b98c-b1ea3772ebec.png)
![2023_01_05 Additional KanBan Error](https://user-images.githubusercontent.com/106859528/210816704-b19c42fb-b967-4461-a937-7cb32fa3acee.png)

**Comment by zachegnermh** [comment]
Hi @andrewtran249, we are currently working through an issue that is causing major bugs in msuite-beta. We hope to have it resolved very soon

**Comment by zachegnermh** [comment]
@andrewtran249 Are you still having these errors?

**Comment by andrewtran249** [comment]
@zachegnermh  I am no longer experiencing these errors, but when entering a tool and attempting to click back to the homepage, the screen gets stuck as seen in the attached image. Thank you
![Screenshot 2023-01-06 120540](https://user-images.githubusercontent.com/106859528/211061592-d74931ec-f857-445c-9c71-3447c755e0ba.png)

**Comment by zachegnermh** [comment]
@andrewtran249 Ok, thanks. We will look into it.
