### ISSUE TITLE
Presentation: Fix bug that reverts edited text after textbox automatically extends beyond the container.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1412]
Currently, user is unable to adjust the width of the textbox (see Issue #1411).
After user edits paragraph, the textbox automatically resizes. Unfortunately, when it automatically resizes beyond the container, the text reverts to pre-edited text.

Screenshot Example 1

![powerpoint_input_text_into_textbox_and_scrollbars_displayed_while_on_focus](https://user-images.githubusercontent.com/11938477/215822170-6cbed1af-82f9-4a66-9237-1bb3b07f44d5.png)

![powerpoint_input_text_into_textbox_and_scrollbars_displayed_while_on_focus__then_beyond_container_for_a_second](https://user-images.githubusercontent.com/11938477/215822216-ab4d4f41-2d75-4724-a9e5-a409ee702032.png)

![powerpoint_input_text_into_textbox__while_on_focus__then_beyond_container_for_a_second_then_text_reverted_to_default](https://user-images.githubusercontent.com/11938477/215822251-05e0ed19-c8d6-419e-8377-ed0cb7d0fe75.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example 2

![powerpoint_edited_text_displays_since_textbox_within_container](https://user-images.githubusercontent.com/11938477/215823327-527dc1f7-22cc-4b25-b8fe-b6ea328d4369.png)

![powerpoint_edit_textbox_reverts_to_default_size_with_scrollbars__edit_text](https://user-images.githubusercontent.com/11938477/215822535-3b5db17a-b5ae-4eed-984e-29a86260c871.png)

![powerpoint_edited_text_displays_for_a_second_beyond_the_container](https://user-images.githubusercontent.com/11938477/215824120-a393ef10-fd71-49ba-924e-d3ee1d597edd.png)

![powerpoint_edit_textbox_content_reverts_to_pre-edit_content_after_textbox_extended_beyond_container](https://user-images.githubusercontent.com/11938477/215822558-1e286571-f953-4d46-bd9c-27034dea38c9.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Closing, fixed
