### ISSUE TITLE
Presentation: "Text with Bullet" should function as "Bulleted List" when clicked, instead of one bullet item. Should also change tooltip.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1413]
Clicking the "Text with Bullet" button only creates one bulleted item and also removes the line returns, so the text displays as one bulleted item.
NOTE: It should function like NotePad.

Screenshot Example

![powerpoint_click_text_with_bullet](https://user-images.githubusercontent.com/11938477/215831205-f4511240-5544-4c29-b927-687582f4389c.png)

![powerpoint_text_with_bullet_only_creates_one_bullet_item](https://user-images.githubusercontent.com/11938477/215831226-889054b9-60fb-48dd-a3b7-7a6ff26fc7af.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example of what is expected for Bulleted List

![presentation_include_bulleted_list](https://user-images.githubusercontent.com/11938477/215860442-fda78cf1-0569-46e3-bd8e-ed8272e4ea94.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Closing, fixed
