### ISSUE TITLE
Presentation: Second slide should have default layout with Title and Body text

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1418]
Screenshot Example

![Presentation_default_second_slide](https://user-images.githubusercontent.com/11938477/215842238-d470756f-fed5-483d-b91e-f0254088b497.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Closing, fixed
