### ISSUE TITLE
Presentation: Should include Numbered List

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1421]
Screenshot Example

![presentation_include_numbered_list](https://user-images.githubusercontent.com/11938477/215859890-a5d17457-7754-45d0-917f-895261227f5f.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it and let me know.

**Comment by LAlexMHllc** [comment]
Closing, since includes Numbered List.
NOTE: See Issue #1440
