### ISSUE TITLE
File Transfer: Should remove Title and unnecessary header bar buttons

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1436]
Files should not be saved to disk, and map should only exist for live session file transfer, so Title and most buttons are not necessary.
Screenshot Example

![file_sharing_should_remove_Title_and_unnecessary_header_bar_buttons](https://user-images.githubusercontent.com/11938477/220658088-e42615f0-17d9-4d89-8079-27198f879eb3.png)

**Comment by bluenevus** [comment]
we should probably keep the chat icon and edit user name icon.  The rest can go but we do need a password protect option though I really don't want so many clicks.  The same link page we are at, is the same link they will use.  just a password option to encrypt and decrypt kind of like so.

https://sendfiles.dev/

**Comment by LAlexMHllc** [comment]
Closing, fixed
