### ISSUE TITLE
Presentation: Should be able to have different text styles within a single text box.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1440]
User should be able to change the text style of selected text within a box, instead of separate boxes for each text style.
Currently, user is unable to change the text style since the style is dependent upon the box style.
Example 1: User should be able to change a bulleted list to a numbered list by selecting the text, then clicking the Numbered List button.
Example 2: Should be able to have paragraph text, numbered list, and bulleted list within the same text box.

**Comment by LAlexMHllc** [comment]
@b-solution   The update includes the ability to change the style of the entire content within a text box by clicking a text style button.
If possible, would prefer to have different styles within a single textbox.
If not possible, then please leave a comment, then close this issue.

**Comment by b-solution** [comment]
Sorry @LAlexMHllc it's not possible, Closing issue.
