### ISSUE TITLE
Presentation map: Map should still function after Saving Private

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1445]
Screenshot Example of save presentation map private

![presentation_items_disappear_and_buttons_stop_functioning_after_Save_Private_1](https://user-images.githubusercontent.com/11938477/220378511-ac3d6a88-ea89-4a09-8685-93beb67410f5.png)

Screenshot Example of map after Save Private

![presentation_items_disappear_and_buttons_stop_functioning_after_Save_Private](https://user-images.githubusercontent.com/11938477/220376159-8d56b451-e087-43c8-9d1f-69d49f7d2d40.png)

After Save Private:
- The left sidebar and main content sections disappear
- The buttons on the header bar stop functioning
- Unable to Edit Title

Items still did not display after clicking refresh/reload.

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Still does not function with same issues

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
