### ISSUE TITLE
Should include password characters requirement on Save Private, Change Password, and Access Key modals

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1482]
Screenshot Example

![save_password_change_password_key_modal_should_include_characters_requirement](https://github.com/MicroHealthLLC/mSuite/assets/11938477/fe8cd9bd-5dd3-46a7-bd48-41834980ac7c)

**Comment by LAlexMHllc** [comment]
Was able to Save Private with special character(s), but then sometimes:
- Was unable to access map
- Was unable to Change Password

**Comment by LAlexMHllc** [comment]
Since special characters for password sometimes causes issues, should exclude special characters from password settings.
When user inputs special character(s), should display validation message, "Special Characters not allowed", on modal.

Screenshot Example

![exclude_special_characters_from_password_and_key__display_validation_message_on_modals](https://github.com/MicroHealthLLC/mSuite/assets/11938477/f2ec99b9-9857-4d9a-9b08-026e237216cd)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again?

**Comment by LAlexMHllc** [comment]
Valid password requirement still does not display on the Password modals

**Comment by LAlexMHllc** [comment]
Closing, fixed
