### ISSUE TITLE
Calendar switch to todo list

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#1505]
I entered dates on a calendar then switched to the todolist feature

What you see in sprints are date ranges I entered so they span multiple days
What I expected was all the events to be subtasks within the multiple date range spans

Instead, they were all major tasks

![image](https://github.com/MicroHealthLLC/mSuite/assets/3675043/b471abb0-bdcc-45c7-bae3-548a766f3e6e)

**Comment by LAlexMHllc** [comment]
Closing, fixed.
Screenshot Example

![Calendar_Switch-to-ToDo_Parent_Child_relationships](https://github.com/MicroHealthLLC/mSuite/assets/11938477/ca1d90a2-a56e-48f1-800b-fa5de31147d6)
