### ISSUE TITLE
calendar switch to todo lis

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#1506]
I created a calendar then switched to the todo view

I expected the list to be in ascending order by date

the dates are all over the place

![image](https://github.com/MicroHealthLLC/mSuite/assets/3675043/487ec79c-b66f-4392-b4f3-d7bc949ca21b)

**Comment by LAlexMHllc** [comment]
Closing, fixed.
Screenshot Example

![Calendar_Switch-to-ToDo_Parent_Child_relationships](https://github.com/MicroHealthLLC/mSuite/assets/11938477/5a174d89-1511-4d26-969a-557a40a4c5bf)
