### ISSUE TITLE
need an admin conf file so that we can configure automatic deletion of files

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#152]
As an admin, I want to be able to configure how long a file will remain inactive until its deleted

By default its 180 days but in that text conf file, I would like to be able to change that timeframe of inactivity.

**Comment by b-solution** [comment]
@bluenevus Do you want me to delete any mindmap from our DB, if it's not open for 180 days?

**Comment by bluenevus** [comment]
that is the default config for the conf file or yml file but I'm looking for the yml file that can configure the amount of days of inactivity that the files are automatically deleted if not opened.  180 days it the default
