### ISSUE TITLE
Calendar map: Event should only be associated with a Sprint that it falls within its timeline

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1533]
Screenshot Example of Event not within any Sprint, yet included in a Sprint.

![event_not_within_sprint_timeline_still_included_in_Sprint](https://github.com/MicroHealthLLC/mSuite/assets/11938477/827459a3-26b4-4584-a145-c4b6422a7570)

_____________________________________________________________________________

Screenshot Example of Event displaying under another Sprint, yet still associated with another Sprint along a different timeline.

![event_not_within_sprint_timeline_still_included_in_Sprint_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/887130af-0566-4ac5-894a-9b74b05af20f)

**Comment by zachegnermh** [comment]
#1535

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.
Screenshot Example

![calendar_event_should_not_be_associated_with_sprint_it_does_not_fall_within_its_timeline](https://github.com/MicroHealthLLC/mSuite/assets/11938477/40dfdc48-be78-45b6-912a-3eda32baff83)
