### ISSUE TITLE
Calendar map: Should consistently be able to update associated color for Event not attached to Sprint

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1538]
For event not attached to sprint, the Event Info/Action Box should consistently include Eye Dropper link; when clicked, display Color Picker.
Screenshot Example

![calendar_event-info-action-box_for_event_not_attached_Sprint_should_include_eyedropper](https://github.com/MicroHealthLLC/mSuite/assets/11938477/c0da8633-6828-4aaa-90d9-3f466efa8ba0)

**Comment by zachegnermh** [comment]
#1535

**Comment by LAlexMHllc** [comment]
Closing, fixed
