### ISSUE TITLE
ToDo map: Drag 'n drop function needs improving.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1559]
Should have better control over parent/child positions.
Screenshot Example

![ToDo_drag-n-drop_parent_when_no_children_exists_became_children_as_well_as_remaining](https://github.com/MicroHealthLLC/mSuite/assets/11938477/a10fec7c-99a3-4a98-b54d-2b24c9abdd46)

**Comment by LAlexMHllc** [comment]
Sometimes the ToDo automatically resets after drag 'n drop.
Screenshot Example

![to-todo__drag-n-drop__todo_reset](https://github.com/MicroHealthLLC/mSuite/assets/11938477/3fb94e89-b9f7-421c-8593-1221d262c7a1)

**Comment by LAlexMHllc** [comment]
Still needs work

**Comment by b-solution** [comment]
#1694 
@LAlexMHllc In the current implementation of drag and drop functionality, we've introduced two distinct actions: dragging a row and creating a child row. To make this process more user-friendly and intuitive, we propose the introduction of explicit icons for each action.

**Proposed Icons**

**Swap Icon**
This icon will represent the action of dragging a row to rearrange its position within the list.

**Create Child Icon**
This icon will represent the action of creating a child row under the selected parent row.

**User Interaction**
When a user hovers over a row, both icons will be visible. The user can then click on the respective icon to perform the desired action.

**Implementation**

**Swap Icon**
When the "Swap Icon" is clicked, the selected row will enter drag mode, allowing the user to rearrange its position within the list.
**Create Child Icon:**
When the "Create Child Icon" is clicked, the selected row will become the parent, and a new child row can be added underneath it.

**Benefits**

**Clear User Intent**
Users can now explicitly choose between rearranging rows and creating parent-child relationships, providing a more transparent user experience.

**Improved Interface**
The addition of specific icons enhances the visual cues, making it easier for users to understand and engage with the drag and drop functionality.

**Comment by LAlexMHllc** [comment]
@b-solution What about drag a child to become a parent function
Screenshot Example

![todo_drag-n-drop_child_node_to_become_parent](https://github.com/MicroHealthLLC/mSuite/assets/11938477/af2078f1-719d-46c9-8e5f-253add4cfd63)

**Comment by LAlexMHllc** [comment]
@b-solution Please proceed with your solution (see comment above)

**Comment by LAlexMHllc** [comment]
Closing, drag n drop improved
