### ISSUE TITLE
ToDo map: After switching back to ToDo from Calendar, all the map functions should consistently work

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1581]
Switched from ToDo view to Calendar view, then back again (without making changes).
Clicking "Delete" should have deleted the corresponding todo.
Clicking "Switch to Calendar" should have changed view.
Clicking Save to input another ToDo should have created another todo.

**Comment by b-solution** [comment]
@LAlexMHllc can you please test it.

**Comment by LAlexMHllc** [comment]
Closing, fixed
