### ISSUE TITLE
ToDo map: Should only display Dates with correct style/format for ToDo

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1615]
After Switch to Calendar from ToDo: Update from all day Event to time range; Switch to ToDo; click Edit ToDo.
When Cancel is clicked, the style/format flashes incorrectly for about a second.
When Save is clicked, the incorrect style/format remains displayed until reload or update.
Screenshot Example

![todo_should_display_correct_style_dates](https://github.com/MicroHealthLLC/mSuite/assets/11938477/fce749f0-3987-4f9d-bf0c-72b7d99beeaf)

**Comment by LAlexMHllc** [comment]
Issue happened after Event with time range was changed to Sprint on the Calendar, then Switch to ToDo.
Edit that Sprint, then click Cancel/Save. The Dates display in incorrect style/format.

**Comment by LAlexMHllc** [comment]
The style/format of dates display incorrectly for about a second after checking/unchecking ToDo.
Screenshot Example

![when_todo_checked_unchecked_dates_display_incorrect_style_format_for_a_second](https://github.com/MicroHealthLLC/mSuite/assets/11938477/f430c365-47c1-4c66-948e-c25a6c597b08)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it and let me know?

**Comment by LAlexMHllc** [comment]
Closing, fixed
