### ISSUE TITLE
Calendar map: Add Recurrence should include Repeat Every "Day" option

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1624]
Screenshot Example

![calendar_add_event_recurrences_should_include_Repeat_Every_Day_option_1](https://github.com/MicroHealthLLC/mSuite/assets/11938477/9192dc1a-1d66-446a-bb31-89819c350f3d)

![calendar_add_event_recurrences_should_include_Repeat_Every_Day_option_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/cd06e87e-1e0d-4f73-a6bd-55f4125b7a67)

**Comment by b-solution** [comment]
@LAlexMHllc I hope you are well. Can you please guide me when we select 1 day and then when we end event occurrence?

**Comment by LAlexMHllc** [comment]
Screenshot Example

![calendar_day_recurrence_1](https://github.com/MicroHealthLLC/mSuite/assets/11938477/285df027-8214-4334-9a82-56d1d54dff6e)

![calendar_day_recurrence_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/cdfc4d20-037a-44f1-b7df-4bbe91a6f2fd)

![calendar_day_recurrence_3](https://github.com/MicroHealthLLC/mSuite/assets/11938477/4c62851b-a9ad-435e-b206-79c3e829201d)

![calendar_day_recurrence_4](https://github.com/MicroHealthLLC/mSuite/assets/11938477/7a339bb4-90dd-418a-9510-4b1bbcf8c1f4)

![calendar_day_recurrence_5](https://github.com/MicroHealthLLC/mSuite/assets/11938477/0e01235d-03a2-4608-b615-8ce54287e261)

**Comment by b-solution** [comment]
@LAlexMHllc I hope you are well. Can you check this func and let me know if you want any changes required?
https://github.com/MicroHealthLLC/mSuite/assets/5988861/1c5681c4-f739-4936-90bb-be6caa2d48cb

**Comment by LAlexMHllc** [comment]
Day Recurrence with "After X Occurrences" - DONE

Day Recurrence should also function with "Never" and "On" selected date, as well.
Screenshot Example

![calendar_repeat_day_should_function_with_Never_AND_On-selected-date_options](https://github.com/MicroHealthLLC/mSuite/assets/11938477/557d9e21-7b4a-4079-8c73-2ba5306caa3f)

**Comment by LAlexMHllc** [comment]
Closing, fixed
