### ISSUE TITLE
Calendar map: Related to "None" should stick for Activity.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1641]
**Update color should not change Related to for Activity.**

Tried to update color for Related to "None" overlapping Activity.
Screenshot Example

![calendar_update_color_for_unrelated_overlapped_activity](https://github.com/MicroHealthLLC/mSuite/assets/11938477/2340bb4e-6d80-4c01-ae60-3292ceb7956c)

Instead, the Activity became related to overlapping Activity.
Screenshot Example

![calendar_update_color_for_unrelated_overlapped_activity_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/395e9fc5-3029-48cb-ad6a-80cd236a9064)

**Comment by LAlexMHllc** [comment]
Sometimes still changes after drag 'n drop.

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again?
