### ISSUE TITLE
there should be only one concept map name to enter field

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#165]
![image](https://user-images.githubusercontent.com/3675043/141486338-4ac17e51-0187-43d0-87ab-5b75d2ca3ec1.png)

**Comment by b-solution** [comment]
The first input field is use for the name of map (mindmap, tree or kanban) by default it's 'Central Idea'.
The second input field is for to get the map with it's unique key. if that key not found it will open the new mindmap.

If you want to change the functionality then from where we can enter unique key of m concept to open it.
