### ISSUE TITLE
entering a concept map name doesn't result in getting into that concept map...its still random url

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#166]
![image](https://user-images.githubusercontent.com/3675043/141486447-913880d0-84b5-4f31-a4aa-d6cc049c0fc0.png)

![image](https://user-images.githubusercontent.com/3675043/141486468-25c4ac47-a31c-4cb9-b827-86c1e137f99d.png)

**Comment by b-solution** [comment]
The 'Unique Key' is different for all maps. I think we should not need to unique the 'name' field.

**Comment by b-solution** [comment]
User can only open the previously saved map by entering unique key to second input field.

<img width="890" alt="Screenshot 2021-12-13 at 4 53 46 PM" src="https://user-images.githubusercontent.com/5988861/145807812-0a53e810-a569-4a61-9364-df0ca5ce203f.png">

**Comment by bluenevus** [comment]
there should be only 1 input field.  the map key which is automatically generated or they entered manually.  So the workflow is if the top field is blank and they click mindmap then you get the unique key generated.  If they enter a name and click the mindmap then that name is the key.  No 2nd field to enter as its confusing

![image](https://user-images.githubusercontent.com/3675043/145833632-2a1d5226-c768-4e67-9ab2-834285fa2383.png)

**Comment by bluenevus** [comment]
this applies to each of the app.  so if the first field is blank and they click kanban, then its automatically generated.  If they enter a name and click kanban that is the name of the key in the url.  Same for treemap.  This way they can either get a unique key generated or create a key by typing the name of the key and clicking the buttons below the text field

**Comment by b-solution** [comment]
We removed the second field and now this will work according to your requirement, only one question is still in my mind that how can we access the old mSuite map using their existing unique key?
![image](https://user-images.githubusercontent.com/5988861/147777118-a51c6dfe-8c67-4096-8a7f-7bbdad6558f7.png)

**Comment by bluenevus** [comment]
this is an example of how it should work https://pad.riseup.net/

one field...type the name and see the url

**Comment by b-solution** [comment]
Url based on entered concept map name in the field
<img width="1277" alt="Screenshot 2022-01-06 at 5 57 23 PM" src="https://user-images.githubusercontent.com/5988861/148388253-2f0a7381-ce7f-46e6-8fc8-7b6f9aeb3911.png">

<img width="1279" alt="Screenshot 2022-01-06 at 5 57 42 PM" src="https://user-images.githubusercontent.com/5988861/148388136-fde7ddf0-c7b3-4ee0-ba14-0664c9b38180.png">
Error shown if length of concept map name is either too short or too long and also the required length of words to create new map.
<img width="1280" alt="Screenshot 2022-01-06 at 6 01 55 PM" src="https://user-images.githubusercontent.com/5988861/148388397-681fbc71-aaeb-4411-8c96-ed259f84d5ce.png">
<img width="1279" alt="Screenshot 2022-01-06 at 6 02 26 PM" src="https://user-images.githubusercontent.com/5988861/148388414-8c03f3cb-ed80-4b29-9375-0ff23417b9dc.png">
<img width="1278" alt="Screenshot 2022-01-06 at 5 56 29 PM" src="https://user-images.githubusercontent.com/5988861/148388460-ae632973-b8e9-4626-9cf1-76213b07527f.png">
Modal also shown if already created then asked in the modal if want to create new with random name or try again or continue with it
<img width="1280" alt="Screenshot 2022-01-06 at 5 57 52 PM" src="https://user-images.githubusercontent.com/5988861/148388691-294537c4-540c-4bbc-9333-c655939ab70d.png">
