### ISSUE TITLE
Sidqik DDoS 

### ISSUE THREAD

**Issue by jldroid19** [MicroHealthLLC/mSuite#1669]
![Screenshot_20230914-230301_Outlook.jpg](https://github.com/MicroHealthLLC/mSuite/assets/10508346/2e83838f-8e15-42dc-9a8e-3374e2d37679)

https://github.com/advisories/GHSA-3qc2-v3hp-6cv8

**Comment by zachegnermh** [comment]
Fix has been started https://github.com/MicroHealthLLC/mSuite/security/dependabot/130
