### ISSUE TITLE
buttons for make private should be conistent

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#167]
it should look like this
![image](https://user-images.githubusercontent.com/3675043/141486632-0d39c6cc-ae04-4d24-b43a-99d038107bf6.png)

but in some it looks like this

![image](https://user-images.githubusercontent.com/3675043/141486617-51bfe8e8-c27f-48ae-a3be-b9ba2ef5a32e.png)

**Comment by b-solution** [comment]
<img width="1438" alt="Screenshot 2021-12-09 at 3 23 16 PM" src="https://user-images.githubusercontent.com/5988861/145378825-c56a6e99-add8-48c6-9b9c-9e12fea9991a.png">

<img width="1440" alt="Screenshot 2021-12-09 at 3 23 33 PM" src="https://user-images.githubusercontent.com/5988861/145378847-36a9ea98-2e2b-45a0-99ac-1d98a93a046a.png">

<img width="1439" alt="Screenshot 2021-12-09 at 3 23 47 PM" src="https://user-images.githubusercontent.com/5988861/145378859-621c1a10-85d2-42a3-aab9-ad05c93098ef.png">
