### ISSUE TITLE
DEV - Calendar map: Clicking the Delete button should delete the corresponding Activity

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1673]
Activity should have been deleted when its corresponding Delete button was clicked. Activity remained, even after reload.
Screenshot Example

![calendar_click_delete_should_delete_activity](https://github.com/MicroHealthLLC/mSuite/assets/11938477/f50b05a1-c24e-474d-9e48-91fe69f8225a)

**Comment by zachegnermh** [comment]
Closing, fixed
