### ISSUE TITLE
Calendar map: When Activity is not related to another activity, its Activity Card should not display "Relationship: None"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1674]
Should be consistent and not display "Relationship: None" on Activity Card when there is no relationship.

Screenshot Example after Update Activity changing from Related to: Activity X to Related to: None

![calendar_map_edit_activity_update_to_relationship_None__displays_on_Activity_Card](https://github.com/MicroHealthLLC/mSuite/assets/11938477/899ece42-a168-48fb-ab4c-31136b24bebf)

**Comment by LAlexMHllc** [comment]
Screenshot Example of Activity without relationship, and its Activity Card does not have "Relationship: None"

![calendar_activity_card_for_node_within_another_timeline_without_Relationship_on_card](https://github.com/MicroHealthLLC/mSuite/assets/11938477/f69f5698-0233-4d53-8949-97f44cb6fbad)

_______________________________________________________________________

Screenshot Example of Activity with Relationship, and Relationship displays on its Activity Card

![calendar_activity_card_for_node_within_another_timeline_with_Relationship_on_card](https://github.com/MicroHealthLLC/mSuite/assets/11938477/69e9e0dc-87e2-4b01-b6f2-1001fc61ea78)

Screenshot Example after Activity gets updated to "Relationship: None", and it displays on its Activity Card

![calendar_activity_card_for_node_within_another_timeline_with_Relationship-None_on_card](https://github.com/MicroHealthLLC/mSuite/assets/11938477/0efe4f9d-d560-44f6-a28a-2599870feecc)

**Comment by LAlexMHllc** [comment]
Screenshot Example of Add Activity without Relationship. "Relationship: None" does not display on the Activity Card

![calendar_map_add_activity_with_Relationship_None__Relationship_not_on_activity_card](https://github.com/MicroHealthLLC/mSuite/assets/11938477/b51ac13a-8015-4c4e-a564-c007a152f4b9)

____________________________________________________________

Screenshot Example of Activity Card with "Relationship: None". After Update Activity to remain Related to: None, the Activity Card does not display "Relationship: None". 

![calendar_map_edit_activity_update_to_remain_relationship_None__not_display_on_Activity_Card](https://github.com/MicroHealthLLC/mSuite/assets/11938477/c4a1b8a0-da88-4d9e-b136-da578a08b5d3)

**Comment by LAlexMHllc** [comment]
Was unable to test due to new Issue #1743

**Comment by LAlexMHllc** [comment]
After updates, the dropdown select displays when "Related to" label is visible, so proceeded with testing.
**Test failed.**
Screenshot Example

![Calendar_map_Relationship_None_should_not_display_on_Activity_Card](https://github.com/MicroHealthLLC/mSuite/assets/11938477/b8eddee2-0252-4e0d-943c-98fb05869cad)

**Comment by b-solution** [comment]
@LAlexMHllc I fixed this issue in #1743. Can you please test it again?

**Comment by LAlexMHllc** [comment]
Closing, fixed
