### ISSUE TITLE
DEV - ToDo map: Clicking Delete icon should delete the corresponding ToDo

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1675]
Screenshot Example

![ToDo_DEV_clicking_delete_button_should_delete_corresponding_ToDo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/d4f984c0-175f-4422-bc50-84679567c7ea)

**Comment by zachegnermh** [comment]
Closing, fixed
