### ISSUE TITLE
QA - Calendar map - Switch to ToDo: Should include all activities on map

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1676]
Screenshot Example

![calendar_QA_with_2_activities_Switch_ToDo_missing_activity](https://github.com/MicroHealthLLC/mSuite/assets/11938477/8292ac08-acc1-4591-bd11-a67269669d8c)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know?

**Comment by LAlexMHllc** [comment]
@b-solution Still does not function correctly
Screenshot Example

![Calendar_Switched-to-To-Do_all_Todos_should_display_1](https://github.com/MicroHealthLLC/mSuite/assets/11938477/b9de7c2f-9f9d-48a6-bc72-b29b4b98a470)

![Calendar_Switched-to-To-Do_all_Todos_should_display_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/709f75bd-fef3-4b22-8ebe-550b5c001370)

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.
Screenshot Example

![Calendar_activity_should_display_on_ToDo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/d9d5b6b5-8d84-4225-9857-79acc7a27dd5)

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
