### ISSUE TITLE
menu bar should have the same options where applicable

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#168]
for example the home button
![image](https://user-images.githubusercontent.com/3675043/141486742-cf10f880-717f-400c-b9e4-b2dc5436c499.png)

and when that home button is clicked, it should result in the same dialog
![image](https://user-images.githubusercontent.com/3675043/141486887-6dabb062-6a17-4526-8998-a0b393012bbc.png)

however, its missing on the other concept maps

![image](https://user-images.githubusercontent.com/3675043/141486935-a5ba67b7-03a2-4171-b5c7-fbde909889ab.png)

really the color scheme, icons, button, button placements, logo etc etc should e the same for each concept map

**Comment by b-solution** [comment]
<img width="1438" alt="Screenshot 2021-12-09 at 3 23 16 PM" src="https://user-images.githubusercontent.com/5988861/145378825-c56a6e99-add8-48c6-9b9c-9e12fea9991a.png">

<img width="1440" alt="Screenshot 2021-12-09 at 3 23 33 PM" src="https://user-images.githubusercontent.com/5988861/145378847-36a9ea98-2e2b-45a0-99ac-1d98a93a046a.png">

<img width="1439" alt="Screenshot 2021-12-09 at 3 23 47 PM" src="https://user-images.githubusercontent.com/5988861/145378859-621c1a10-85d2-42a3-aab9-ad05c93098ef.png">
