### ISSUE TITLE
TreeChart and FlowMap: Should include drag icon on Central Idea node, and should ONLY drag map from central node.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1705]
Currently, unable to drag n drop map since the Central node is missing a drag icon.
Screenshot Example

![treechart_and_flowmap_include_drag_icon_on_main_node](https://github.com/MicroHealthLLC/mSuite/assets/11938477/64ea52e5-aa73-4e35-b4a1-6eda8f93d98a)

**Comment by b-solution** [comment]
@LAlexMHllc Hi the parent node can't move from its position as it is not allowed to move or be dragged.

**Comment by LAlexMHllc** [comment]
Same as Issue #591

**Comment by LAlexMHllc** [comment]
Closing, fixed
