### ISSUE TITLE
sidkiq service failing on msuite dev and msuite qa.  not UI is starting

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#1711]
If its only used for calendar notifications, I think we can just do away with it.

I'm not sure what else uses sidekiq though and how important it may be for other functions say determining when files should be deleted or something like that

**Comment by zachegnermh** [comment]
Hi @bluenevus, we have disabled sidekiq as per requested. Can you please post of a screenshot of the error message?
![image](https://github.com/MicroHealthLLC/mSuite/assets/109542090/c98956bd-c648-4c75-a626-d101f3f58616)

**Comment by b-solution** [comment]
@zachegnermh, please check the worker as well, as some workers are dependent on Sidekiq, such as FileInActiveWorker and DeleteFileWorker. If any service is running, it may generate a bug and check GitHub workflow folder, and review the file 'codeql.yml.
