### ISSUE TITLE
Beta - TreeMap: Should display grandchild node after Add clicked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1723]
Grandchild node did not display after Add node clicked, not even after reload/refresh.
Screenshot Example

![beta_treemap_grandchild_node_not_display](https://github.com/MicroHealthLLC/mSuite/assets/11938477/49a99563-a218-486e-bf43-37980cd6d1de)

**Comment by b-solution** [comment]
<div style="position: relative; padding-bottom: 45.20833333333333%; height: 0;"><iframe src="https://www.loom.com/embed/dc38cf7cd94243adb3dfaa6654416727?sid=4dcbd0ce-e319-41a4-af65-34315e74e71a" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>


Can you please check this.

**Comment by b-solution** [comment]
@LAlexMHllc I hope you are well. It's working well on my side.
https://www.loom.com/share/dc38cf7cd94243adb3dfaa6654416727?sid=9aafb294-d0e3-4ce1-be45-f8f76eca7842

**Comment by LAlexMHllc** [comment]
@b-solution After clicking "Add Child Node" from Central node twice, then clicking "Add Child Node" from the second child node twice, then clicking "Add Child Node" from Central node once more, the map should look like the following screenshot.

![beta_treemap_grandchild_node_not_display_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/d4a1b129-36f1-43dd-81fe-c41c70247715)

**Comment by b-solution** [comment]
@jldroid19 @zachegnermh Could you please check Redis and provide me with the staging link? I want to test there. Thanks!

**Comment by LAlexMHllc** [comment]
Still needs to be fixed
