### ISSUE TITLE
Maps: Input text should not display as random characters

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1730]
Some examples are after submit ToDo; after undo/redo: Mindmap, Kanban, TreeMap, FlowMap, TreeChart, Calendar.

Screenshot Example on ToDo

![todo_random_characters_after_add_todo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/48c27c69-34da-49ec-8bda-dbe56007b112)
____________________________________________________________________

Screenshot Example on Mindmap

![mindmap_random_characters_after_redo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/e40ec745-91b1-4194-87c0-b5e5c226dd69)
____________________________________________________________________

Screenshot Example on Kanban

![kanban_random_characters_after_redo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/da6d902e-7849-41d9-907d-6cb07fc57460)
____________________________________________________________________

Screenshot Example on TreeMap

![treemap_random_characters_after_redo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/52b56ec3-4d23-414e-a3af-da30ee8660ae)
____________________________________________________________________

Screenshot Example on TreeChart

![treechart_random_characters_after_redo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/fbf70c9e-dc5e-4fb6-af99-3ef0bde3e8bf)
____________________________________________________________________

Screenshot Example on Flowmap

![flowmap_random_characters_after_redo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/69466e4c-9bc7-4534-94d4-76afa7f11b73)
____________________________________________________________________

Screenshot Example on Calendar

![calendar_random_characters_after_redo](https://github.com/MicroHealthLLC/mSuite/assets/11938477/73183ced-4c7e-42b6-ad24-eb5ec1635744)

**Comment by b-solution** [comment]
@LAlexMHllc we fixed the issue in the integration branch already when it is in the master it will work well.

**Comment by LAlexMHllc** [comment]
Closing, fixed
