### ISSUE TITLE
ToDo map:  Drag n drop sibling within Parent should just rearrange Child Nodes under that Parent

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1749]
Sometimes drag n drop sibling within Parent should not automatically move Child to another Parent
Screenshot Example

![ToDo_Make-Child_drag-n-drop_Sibling_created_misplaced_child_to_another_Parent](https://github.com/MicroHealthLLC/mSuite/assets/11938477/ac81ac55-ba2a-4937-83d6-d9c6049d974c)

**Comment by LAlexMHllc** [comment]
NOTE: This usually happens when trying to rearrange sibling Child nodes after one of the Children was dragged to become the child of another Parent.

**Comment by b-solution** [comment]
@LAlexMHllc can you please test it.
