### ISSUE TITLE
Calendar map: Should display all of a Parent's Child nodes in a style that indicates Related to it.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1756]
After drag n drop Parent node to become Child node, then Switch to Calendar clicked, the style of that node should have updated to indicate relationship.
Screenshot Example BEFORE drag n drop Parent node to become Child node

![ToDo_BEFORE_drag-n-drop_Parent_to_become_Child_click_Switch-to-Calendar](https://github.com/MicroHealthLLC/mSuite/assets/11938477/8c32d2ff-124b-421f-ae8c-593d5d153bf8)

![ToDo_BEFORE_drag-n-drop_Parent_to_become_Child_click_Switch-to-Calendar_1](https://github.com/MicroHealthLLC/mSuite/assets/11938477/cfad315b-ef7f-4d79-b90b-3da667b4e0be)
____________________________________________________________________________________________

Screenshot Example AFTER drag n drop Parent node to become Child node

![ToDo_AFTER_drag-n-drop_Parent_to_become_Child_click_Switch-to-Calendar](https://github.com/MicroHealthLLC/mSuite/assets/11938477/034ff60d-0c45-4da9-a4a8-0428ec97826a)

![ToDo_AFTER_drag-n-drop_Parent_to_become_Child_click_Switch-to-Calendar_1](https://github.com/MicroHealthLLC/mSuite/assets/11938477/2693247d-6a1c-43eb-afb2-82ad8d8f3a80)

**Comment by b-solution** [comment]
@LAlexMHllc can you please test it.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
