### ISSUE TITLE
Calendar map: Non-related Activities should have consistent background height style

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1757]
Also, the background color was not changed with the Color Picker, so expected a black background.
Screenshot Example after Switch to Calendar from ToDo map

![ToMap_Switch-to-Calendar_Unrelated_Activities_should_have_consistent_background_height_style](https://github.com/MicroHealthLLC/mSuite/assets/11938477/616d5577-5142-4fc8-a41d-6f7902419a60)

**Comment by LAlexMHllc** [comment]
@b-solution Only Parent node should have larger height background, not Child node or unrelated node.

**Comment by b-solution** [comment]
@LAlexMHllc I resolved this issue. Can you please test it.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.
NOTE: This usually  happens after drag n drop on ToDo map.
Screenshot Example

![Calendar_map_Solo_Activity_without_children_should_have_smaller_height_style](https://github.com/MicroHealthLLC/mSuite/assets/11938477/02c56b0f-37b4-4d1f-816f-ad8b7f0b7b27)

**Comment by b-solution** [comment]
Hi @LAlexMHllc, Hope you are doing well. Can you please test it again and let me know?

**Comment by LAlexMHllc** [comment]
Hi @b-solution This happens when objects are created on ToDo, then Switch to Calendar.

Screenshot Example of objects created on ToDo

![ToDo_Switch-to-Calendar_Unrelated_Activity_should_have_smaller_height_background_style_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/52a963f1-7a56-4e61-9ad0-84e93904054a)

Screenshot Example after Switch to Calendar from ToDo

![ToDo_Switch-to-Calendar_Unrelated_Activity_should_have_smaller_height_background_style](https://github.com/MicroHealthLLC/mSuite/assets/11938477/361c9951-047e-44c6-bfb2-f0f9dbb57b54)

Screenshot Example of unrelated Activity created on Calendar displays correctly.
NOTE: Even after Switch to ToDo, then Switch to Calendar, the objects created on Calendar display correctly, and the unrelated objects created on ToDo do not.

![ToDo_Switch-to-Calendar_Unrelated_Activity_should_have_smaller_height_background_style_3](https://github.com/MicroHealthLLC/mSuite/assets/11938477/50725aba-25db-45c6-a055-40dbdf1c0332)

**Comment by MaxVMoons** [comment]
Branch #1753 seems to make all bars the smaller size, even on a new ToDo/Calender mindmap
![image](https://github.com/MicroHealthLLC/mSuite/assets/27288360/1d99ea43-0c92-4319-a38a-4395d96ed091)

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
