### ISSUE TITLE
ToDo map - Switch to Calendar: Child node should have same color as Parent, and its Activity Card should not have Color Picker link

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1760]
Screenshot Example

![ToDo_Switch-to-Calendar__Child_should_have_same_Color_as_Parent_and_no_ColoPicker_link_1](https://github.com/MicroHealthLLC/mSuite/assets/11938477/38d50d9d-0fc1-4138-895e-48348beb5ba8)

![ToDo_Switch-to-Calendar__Child_should_have_same_Color_as_Parent_and_no_ColoPicker_link](https://github.com/MicroHealthLLC/mSuite/assets/11938477/fbaaf763-d1e0-40e3-b237-2dd7d91d13f1)

**Comment by b-solution** [comment]
@LAlexMHllc can you please test it.

**Comment by LAlexMHllc** [comment]
Closing, fixed
