### ISSUE TITLE
ToDo map: Start Date should not display when same day as Due Date

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1766]
Screenshot Example when Save Edit ToDo with Start Date the same as Due Date

![ToDo_Start_Date_should_not_display_when_same_as_Due_Date](https://github.com/MicroHealthLLC/mSuite/assets/11938477/55a0d8bd-fbb6-48ec-a3a6-72c807a1b51e)

**Comment by b-solution** [comment]
@LAlexMHllc Hope you are doing well, Can you please tell me when this error occurs? I have tested it multiple times in the integration branch, and it works fine.


https://github.com/MicroHealthLLC/mSuite/assets/5988861/c1dfa1af-6744-4c55-a077-12eaa6d3a33d

**Comment by LAlexMHllc** [comment]
Issue happens when Start Date is the same as the Due Date before Edit ToDo. User clicks Save without selecting Dates again.
Screenshot Examples

![ToDo_do_not_display_Start_Date_when_same_as_Due_Date](https://github.com/MicroHealthLLC/mSuite/assets/11938477/f4abfd96-c04d-4828-af4c-9ed773a165d8)

**Comment by b-solution** [comment]
Hi @zachegnermh, I hope you are doing well. I have recreated the steps in the integration branch according to the provided test case, and everything appears to be working fine. Could you please test it?

**Comment by b-solution** [comment]
Hey @LAlexMHllc, hope you are doing well. I resolve the issue. Can you please test it again?

**Comment by MaxVMoons** [comment]
Issue seems to be unreproducible with #1776 merge, needs final test from LAlexMHllC.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.
Screenshot Example

![ToDo_start-date_end-date_3](https://github.com/MicroHealthLLC/mSuite/assets/11938477/c10d730b-2170-447b-82db-f7ff3501ef4b)

![ToDo_start-date_end-date_4](https://github.com/MicroHealthLLC/mSuite/assets/11938477/ad19be0d-164c-44e3-9dc0-cbf594287ae3)

**Comment by b-solution** [comment]
Hi @LAlexMHllc, I hope you're doing well. I tested it just like you did before, but it still works fine from my end. I'm unable to reproduce this error.


https://github.com/MicroHealthLLC/mSuite/assets/5988861/bd6f427f-8c4d-4af8-bddb-659b0f38207c

**Comment by b-solution** [comment]
Hi @LAlexMHllc, I hope you're doing well. I tested it just like you did before, but it still works fine from my end. I'm unable to reproduce this error.

Video Example
 

https://github.com/MicroHealthLLC/mSuite/assets/5988861/aabc5ca9-4f65-486d-8094-9030baa37833

**Comment by LAlexMHllc** [comment]
Closing, since it functions fine for @MaxVMoons  and @b-solution . Probably just my connection.
