### ISSUE TITLE
Fix the encryption issue on Beta

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1767]
Screenshot Example

![msuite_characters](https://github.com/MicroHealthLLC/mSuite/assets/11938477/5210010d-51f0-410d-8c40-4d62d743f992)

**Comment by b-solution** [comment]
Hi @LAlexMHllc, I hope you are well. Currently, you are testing in production. But over code in the **integration** branch. Could you please test in **QA or Integration**? If the issue continues there, let me know, and I will take care of it. Thank you!

**Comment by MaxVMoons** [comment]
Issue has been fixed on production with the latest merge, closing
