### ISSUE TITLE
ToDo map: Edit ToDo should display with correct Start Date and Due Date

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1792]
Screenshot Example

![ToDo_start-date_end-date_1](https://github.com/MicroHealthLLC/mSuite/assets/11938477/07ab6fb0-2bce-4d3c-bfbd-4eff2ff238cb)

![ToDo_start-date_end-date_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/8ad7145f-72c3-476f-a825-cbb845ffb3a3)

**Comment by MaxVMoons** [comment]
Lisa, I am unable to recreate this bug. If you may try it again, could you try saving the reverted date? My current guess is that an untimely disconnect from the server happened from your page to the server, which shows a previous saved date. If that was so, then saving that multiday date at the end would show it become a single date until a refresh.

**Comment by b-solution** [comment]
Hi @LAlexMHllc , Hope you're doing well. I am also unable to reproduce this error. Its working fine from my side could you please test it again. 

Thanks

Uploading Screen Recording 2024-03-20 at 08.57.53.mov…

**Comment by b-solution** [comment]
Hi @LAlexMHllc , Hope you're doing well it also works fine from my side will you please test it again?
Video example

https://github.com/MicroHealthLLC/mSuite/assets/5988861/0939a9f8-6b25-4b1d-a61c-5e4afc8d73fd

**Comment by LAlexMHllc** [comment]
Closing, since it functions fine for @MaxVMoons  and @b-solution . Probably just my connection.
