### ISSUE TITLE
Mindmap: Clicking "Continue" on Reset Map modal should reset the map

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#183]
Screenshot Example

![click_reset_button](https://user-images.githubusercontent.com/11938477/141820356-c9e6d4aa-e626-43b4-8dc4-2481a300db0b.png)

![clicking_Continue_on_Reset_Map_modal_should_reset_map](https://user-images.githubusercontent.com/11938477/141820383-f2d7d2c8-357d-4ffd-bee5-00839adbcdc7.png)

**Comment by b-solution** [comment]
<img width="1435" alt="Screenshot 2021-11-18 at 2 52 32 PM" src="https://user-images.githubusercontent.com/5988861/142392388-3349d6fe-364c-42ca-80c6-ab1588c33c20.png">

<img width="986" alt="Screenshot 2021-11-18 at 2 52 40 PM" src="https://user-images.githubusercontent.com/5988861/142392425-1a35723e-f8f3-40f0-a846-831432f577c0.png">

<img width="1440" alt="Screenshot 2021-11-18 at 2 52 09 PM" src="https://user-images.githubusercontent.com/5988861/142392457-86927f56-a699-4f88-9600-9c4c19d26dfb.png">

**Comment by LAlexMHllc** [comment]
Reopening, since clicking Continue of Rest map modal did not reset the map. Afterwards, clicking the Home button did not function. Also, trying to edit the map did not function well.

**Comment by b-solution** [comment]
@LAlexMHllc For me every thing is working in latest master, can you please check it again in latest master. If it's still not work for you please share the console message.

**Comment by LAlexMHllc** [comment]
Screenshot Example of mindmap after clicking Continue on Reset modal

![screen_after_confirm_reset_mindmap](https://user-images.githubusercontent.com/11938477/142660451-78388db5-4241-4312-b827-9478ab24bdcf.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed these issue can you please test it again and let me know if it's not work.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed these issue can you please check it again and let me know if it's not work.
