### ISSUE TITLE
as a user I would like a whiteboard as a type of mindmap

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#186]
like this when you click private board

https://wbo.ophir.dev/?lang=en

real time collaboration is the key

**Comment by b-solution** [comment]
<img width="1271" alt="Screenshot 2021-12-30 at 8 26 05 PM" src="https://user-images.githubusercontent.com/5988861/147765240-bd2344c3-08d6-4180-ae61-6fb9373d50f3.png">

**Comment by b-solution** [comment]
<img width="1277" alt="Screenshot 2021-12-30 at 8 33 28 PM" src="https://user-images.githubusercontent.com/5988861/147765781-c03053f1-5ac4-41ae-9b6c-ab16e50d881e.png">
