### ISSUE TITLE
Tree Map - Should be able to drag N drop nodes

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#208]

**Comment by b-solution** [comment]
https://user-images.githubusercontent.com/5988861/145398399-f15b7ab4-955b-43e5-92bc-3b8efe58e164.mov

**Comment by LAlexMHllc** [comment]
Drag N Drop is difficult

**Comment by b-solution** [comment]
@LAlexMHllc  Do you have any idea in your mind how to make it more simple?

**Comment by LAlexMHllc** [comment]
Drag N Drop sibling to rearrange order is difficult
Screenshot Example

![hard_to_drag_n_drop_siblings](https://user-images.githubusercontent.com/11938477/146214635-5b470efa-68ed-43b7-b480-5711e62630de.png)

**Comment by b-solution** [comment]
@LAlexMHllc there are some limitation in the package we used for Tree map and  this is one of them, If drag and drop between sibling is important, I can spend some extra time on this card.

**Comment by LAlexMHllc** [comment]
@bluenevus  Please respond to comment above

**Comment by bluenevus** [comment]
well leave it for now.  We need to get the rest of the full feature set so we can deploy it to prod
