### ISSUE TITLE
Kanban map - For each column, should include a "+" before each delete "x" icon; when clicked, add column to the right.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#212]
Remove "Enter Stage Title +" column.
Screenshot Example

![remove_enter_stage_title_column](https://user-images.githubusercontent.com/11938477/144118015-c454f140-364f-4792-89d3-e5c196554942.png)

-------------------------------------------------------------------------------------------------------

For each Stage column, include a "+" before the delete "x". When clicked, add a column to the right: should have Title textbox with placeholder text, on focus for user to directly input. After user inputs non-blank Title and clicks out, the "Add a Task" button should be included.
Screenshot Example

![kanban_add_column_right_change_title](https://user-images.githubusercontent.com/11938477/144118545-79f1540c-ec31-44d6-b25e-eca28ab7fe89.png)

**Comment by b-solution** [comment]
<img width="1435" alt="Screenshot 2021-12-07 at 6 28 27 PM" src="https://user-images.githubusercontent.com/5988861/145037794-813674e6-3601-4218-a4db-10c4202b9103.png">
