### ISSUE TITLE
Kanban map - Should be able to change the background color of Stage Column using color picker.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#213]
Color Picker should display when user clicks a Stage column background. Should function like Tree Map.
Screenshot Example

![kanban_click_column_background_Color_Picker_displays](https://user-images.githubusercontent.com/11938477/144122793-0d5c37f2-74af-4b38-b505-5d67fafc587c.png)

**Comment by b-solution** [comment]
<img width="1431" alt="Screenshot 2021-12-09 at 4 31 05 PM" src="https://user-images.githubusercontent.com/5988861/145388830-6ce1f3c0-5455-42c1-b159-5fd482d32262.png">
