### ISSUE TITLE
Should include more padding around child nodes so the relationships are easier to distinguish.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#221]
Screenshot Example before another child of Central Node is added.

![central_node_before_another_child_added](https://user-images.githubusercontent.com/11938477/144646017-99e5a618-8026-488a-bcb1-4f08f25e5713.png)

Screenshot Example after another child of Central Node is added.

![central_node_after_another_child_added](https://user-images.githubusercontent.com/11938477/144646032-165fbba3-3c50-418e-bfb0-65d5d2499256.png)

**Comment by b-solution** [comment]
<img width="1432" alt="Screenshot 2021-12-07 at 2 07 04 PM" src="https://user-images.githubusercontent.com/5988861/144999558-bf9b441f-f01c-41d6-ab28-9d6f47053e0f.png">
