### ISSUE TITLE
as a user I would like real time spreadsheet collaboration with export to xlsx and/or csv

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#224]

**Comment by b-solution** [comment]
@bluenevus How exactly do you want this collaboration to done, like if we take 'Tree map' as example how we cover multiple/nested child nodes to spreadsheet? Please explain a little.

**Comment by bluenevus** [comment]
spreadsheet needs to support basic formulas.  doesn't have to be excel level but basic

**Comment by bluenevus** [comment]
for example https://m18.uni-weimar.de/calc/zx3eiour69vp but even more basic than that.  I mean really basic formulas like basic math e.g. sum etc.  the key is that the spreadsheet is simple as it gets
