### ISSUE TITLE
Mindmap - Should remove white border from show/hide children nodes icon; also position so it does not cut off red circle and node border.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#230]
Screenshot Example

![mindmap_show-hide_icons_remove_white_border_and_position_so_complete_red_circle_displays](https://user-images.githubusercontent.com/11938477/145055648-64d34544-1043-47f8-ad25-96151a9d1cb4.png)

![mindmap_show-hide_icons_left-side](https://user-images.githubusercontent.com/11938477/145055792-20549be2-5cb4-4258-b7eb-40eb65c18692.png)

**Comment by b-solution** [comment]
<img width="751" alt="Screenshot 2021-12-09 at 5 01 05 PM" src="https://user-images.githubusercontent.com/5988861/145393241-95c932c1-a4a6-48ce-b5b4-b4a05db4dc1d.png">

<img width="707" alt="Screenshot 2021-12-09 at 5 01 19 PM" src="https://user-images.githubusercontent.com/5988861/145393263-fd419b17-5fa7-4118-99f5-be2e196ccb70.png">
