### ISSUE TITLE
for consistency can we have the color drop next to the + on treemap vs clicking anywhere on the screen

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#235]
![image](https://user-images.githubusercontent.com/3675043/145474607-9346d8a6-2cfb-420c-911b-7a21bb49043d.png)

in front of the plus like kanban

![image](https://user-images.githubusercontent.com/3675043/145474637-742ca002-9136-48be-9553-983aabec877a.png)

**Comment by b-solution** [comment]
<img width="1440" alt="Screenshot 2021-12-10 at 4 41 15 PM" src="https://user-images.githubusercontent.com/5988861/145569041-0c17a7c3-ef3a-4a1f-8d9f-6cfaf7d94907.png">

<img width="1426" alt="Screenshot 2021-12-10 at 4 42 36 PM" src="https://user-images.githubusercontent.com/5988861/145569050-00969118-b9c7-43d8-89cf-02b5b3a0cbf6.png">
