### ISSUE TITLE
Kanban map - Clicking Cancel on confirm delete on unsaved column should not remove the column

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#240]
Screenshot Example

![click_delete_icon_unsaved_kanban-column](https://user-images.githubusercontent.com/11938477/145866066-ae7cdf58-a560-48f9-88b8-39c090c3f578.png)

![cancel_delete_kanban_column](https://user-images.githubusercontent.com/11938477/145865727-464ca91d-818f-40dc-b736-5d548ac8d62b.png)

![click_delete_icon_unsaved_kanban-column_2](https://user-images.githubusercontent.com/11938477/145866239-5c0580c4-6143-48f2-b2af-c282b7b430e4.png)

**Comment by b-solution** [comment]
<img width="1431" alt="Screenshot 2021-12-16 at 1 37 20 PM" src="https://user-images.githubusercontent.com/5988861/146336991-d726b279-4def-487b-9710-2d2253df0a75.png">

<img width="721" alt="Screenshot 2021-12-16 at 1 37 30 PM" src="https://user-images.githubusercontent.com/5988861/146337074-ebd27c73-ceca-42a0-ac38-520b453648fc.png">

When click on Cancel The unsaved stage should not be deleted:
<img width="1431" alt="Screenshot 2021-12-16 at 1 37 20 PM" src="https://user-images.githubusercontent.com/5988861/146336991-d726b279-4def-487b-9710-2d2253df0a75.png">

When click on Delete The unsaved stage should be deleted:
<img width="1416" alt="Screenshot 2021-12-16 at 1 37 47 PM" src="https://user-images.githubusercontent.com/5988861/146337281-2c57a689-9e7c-4bbe-975f-46d41c8025a3.png">
