### ISSUE TITLE
Kanban map - Clicking Edit on unsaved column should not display partial color picker

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#241]
Screenshot Example

![nonsaved_kanban_edit_should_not_function](https://user-images.githubusercontent.com/11938477/145867976-4339811a-7be0-4754-a9b7-2a4b1b7e7205.png)

**Comment by b-solution** [comment]
<img width="1432" alt="Screenshot 2021-12-16 at 1 37 04 PM" src="https://user-images.githubusercontent.com/5988861/146336903-2b41afed-f3c5-4196-a775-74dbaa76d5c7.png">

**Comment by LAlexMHllc** [comment]
Reopened, since user should not be able to Edit background color until Title is entered (like Tree Map)

**Comment by b-solution** [comment]
<img width="1088" alt="Screenshot 2021-12-29 at 11 32 19 PM" src="https://user-images.githubusercontent.com/5988861/147694181-fcae9034-503e-4599-b622-2d9ba0f30a65.png">

**Comment by LAlexMHllc** [comment]
Reopening, since it should be consistent with Tree Map.
Edit and Add buttons display without Title entered, but click function is not included until Saved with Title.

**Comment by b-solution** [comment]
All buttons displayed but only clickable when title is saved.
<img width="1258" alt="Screenshot 2021-12-30 at 6 03 32 PM" src="https://user-images.githubusercontent.com/5988861/147755129-474772b0-af17-4a69-9971-09134889653c.png">
