### ISSUE TITLE
App Header should be mSuite, not mSuite Maps

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#248]
Screenshot Example

![mSuite-header_should_not_include_Maps](https://user-images.githubusercontent.com/11938477/147784690-ea8591aa-23cd-4217-88f5-13162f45f5bb.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/147826482-dd5b9333-0d9a-4f5a-9ba2-17b56dc696d8.png)
