### ISSUE TITLE
Whiteboard - The position of the drawn triangle and the button icon should match

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#254]
Screenshot Example

![whiteboard_the_position_of_drawn_triangle_and_button_icon_should_match](https://user-images.githubusercontent.com/11938477/148077182-ccaa035c-2a32-4503-9637-db467b23af00.png)

Screenshot Example of correct drawn position

![whiteboard_the_position_of_drawn_triangle_matches_button_icon](https://user-images.githubusercontent.com/11938477/148077966-226b386a-ac8b-40e4-abe6-02030874ffc6.png)

**Comment by b-solution** [comment]
@LAlexMHllc So the user should not be able to draw downward triangles?

like this

![whiteboard_the_position_of_drawn_triangle_and_button_icon_should_match](https://user-images.githubusercontent.com/11938477/148077182-ccaa035c-2a32-4503-9637-db467b23af00.png)

**Comment by bluenevus** [comment]
They can draw it any direction they want

**Comment by LAlexMHllc** [comment]
Sorry. Did not realize the position is drawn according to drag up or down when drawing triangle.
