### ISSUE TITLE
the drawing space should be responsive and resize to fill the screen

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#255]
in the image, the drawing space is fixed and I'm unable to take advantage of the full real estate
![Screenshot 2022-01-04 8 04 48 PM](https://user-images.githubusercontent.com/3675043/148144597-8325c279-61a3-48da-9768-adebe15e673f.png)

**Comment by bluenevus** [comment]
drawing space still doesn't resize 
![image](https://user-images.githubusercontent.com/3675043/148963823-b97cb23d-894d-43f8-9345-87c701d31219.png)

**Comment by b-solution** [comment]
This PR is not merged yet. When I'll merge it I'll let you know then you can test it.

**Comment by b-solution** [comment]
@bluenevus You can test it now.
![image](https://user-images.githubusercontent.com/5988861/148968257-48810bdf-dd1d-406a-98c4-bfea42f030a6.png)
