### ISSUE TITLE
Should display "Did you save the map key?" modal when logo clicked on TreeChart

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#261]
Screenshot Example clicked logo on TreeChart and the index displayed.

![click_logo_on_treechart](https://user-images.githubusercontent.com/11938477/148444502-da6f0f3c-a42f-4820-8bda-e729f7c982c9.png)

Should have displayed "Did you save the map key?" modal
Screenshot Example of modal.

![save_map_key_modal](https://user-images.githubusercontent.com/11938477/148444682-22dbeadf-c9be-47ad-ab1a-fc8b3f6ae5cb.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/148921746-c6d281a3-9838-4fe7-9a19-889b99aa434e.png)
![image](https://user-images.githubusercontent.com/5988861/148921842-4e1f85de-b881-4b46-ba90-17ea3347ac9c.png)
