### ISSUE TITLE
if the real estate does not require scroll bars, they shouldn't be visible

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#262]
![image](https://user-images.githubusercontent.com/3675043/148454250-0ddab85f-fd8e-4970-b851-0cb1cc7d997a.png)

**Comment by bluenevus** [comment]
this is at 1080p but even at 4k these scroll bars always show even though the sizing doesn't need or require them therefore they should not be visible in that case

**Comment by b-solution** [comment]
@bluenevus Can you please test it again. I've fixed this issue. If you do still face this issue let me know.

**Comment by LAlexMHllc** [comment]
Vertical scrollbar needs to be fixed.
Screenshot Example

![whiteboard_vertical_scrollbar_needs_to_be_fixed](https://user-images.githubusercontent.com/11938477/149179479-445b07eb-4b24-4b96-ab8c-2da0f3fe90e8.png)

**Comment by bluenevus** [comment]
scroll bars should show only if its needed because it doesn't have the space in a resize response.  but if it has the space so that no scroll bars show, then we shouldn't see scroll bars.  If scroll bars are needed, it needs to resize in teh space to use the scroll bars.
