### ISSUE TITLE
seems there is space for another icon but the padding or something is forcing a wrap

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#263]
![image](https://user-images.githubusercontent.com/3675043/148574690-8eeb0b83-12e7-41d2-a943-64fd6655877f.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/148958970-e1cc16c9-38a2-448a-b8da-e10f7ed2596c.png)

**Comment by bluenevus** [comment]
shown in incognito mode to ensure no caching

**Comment by bluenevus** [comment]
at 1080p or 4k it still shows an extra space on the right

**Comment by b-solution** [comment]
Can you please test it again. I've fixed this issue. If you do still face this issue let me know.

**Comment by bluenevus** [comment]
it now looks like this 
![image](https://user-images.githubusercontent.com/3675043/149005731-4ab6e3bd-7674-4f36-bc69-71e790f4a94e.png)

the word ended up on the side vs bottom
