### ISSUE TITLE
Would be nice if the exported document font would either match the browser font or at least be sans serif

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#271]
Screenshot Example of Browser Font (sans serif)
![browser_font_is_sans_serif](https://user-images.githubusercontent.com/11938477/149011346-5d94e071-089e-4fc0-977e-2cfa75b7240d.png)

Screenshot Example of Exported Document Font (serif)
![exported_font_is_serif](https://user-images.githubusercontent.com/11938477/149011368-2dcf8629-a1f3-40eb-aac4-0dd8e483510f.png)

**Comment by b-solution** [comment]
Previously we are used 'FuturaPTBook' font-family now i'm changing it to 'sans-serif'.
![image](https://user-images.githubusercontent.com/5988861/149141924-df0d67af-ac40-4a8a-a0de-ae19e74b0df0.png)
