### ISSUE TITLE
Mindmap - Central Idea has font weight bold, which is inconsistent with the other maps

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#274]
Screenshot Example

![mindmap_central_idea_font_weight_bold_inconsistent_with_other_maps](https://user-images.githubusercontent.com/11938477/149182508-0e795fd6-9d7c-4340-8da5-aede4b95f9f5.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/149199883-c8a9e92d-698f-4632-beb0-8be4ed4bde66.png)
