### ISSUE TITLE
White Board Map should include "Text" button and function

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#276]
User should be able to input Text
Screenshot Example

![whiteboard_map_include_Text_button_and_function](https://user-images.githubusercontent.com/11938477/149188909-4c240b76-7576-4ffd-8657-c5d27529d058.png)

**Comment by b-solution** [comment]
https://user-images.githubusercontent.com/5988861/152837099-76a58c6d-c2e2-4ee6-b150-b6af186a4364.mp4

**Comment by LAlexMHllc** [comment]
Font should be sans serif, like the others
