### ISSUE TITLE
as a user I would like the option save the file as public, save the file as private or delete the map when I navigate away orin the app

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#283]
when the user navigates away from the page, there should be 3 options given in the dialog.

1. Save Public.  This will give them the option to save the file without a password and provide them a time period of Inactive Delete in days that will delete the map automatically if inactive for xx days.  The number of days by default should be set in a conf file so that it will display like 90 days.  We also need to set a max in the conf file.  For example, we may not permit files more than 365 days no matter what the user entered and in that case the user needs to know what the max is and now be allowed to enter more than the max inactive delete days.  Saving public doesn't mean its open to the world meaning its a published url whose content can be indexed.  Only the landing page is indexable.  It just means you have to know the url to be able to get to the page but no password or encryption is done to it.
2. Save Private.  This will give them the option to make the file private with a password that ENCRYPTS the map with 256 bit aes encryption or above  and provide them a time period of Inactive Delete in days that will delete the map automatically if inactive for xx days.  The number of days by default should be set in a conf file so that it will display like 90 days. We also need to set a max in the conf file.  For example, we may not permit files more than 365 days no matter what the user entered and in that case the user needs to know what the max is and now be allowed to enter more than the max inactive delete days.
3. Delete.  This will delete the file permanently 

![image](https://user-images.githubusercontent.com/3675043/149380624-4c9ed645-cf02-43a1-812a-18df20d63647.png)

If the person closes the browser or it crashes where they do not get the option, the inactive delete for this type of closure should be configurable in the conf file.  For example, we may want to retain a mistaken closed broswer for 5 days configured in that conf file so they can go back to it and save public or save private with the inactive delete time period in days.

These 3 options need to be in each of the app menu bars located in the same place so they can do the same 3 functions in the app before they navigate away in which the dialog in the image above will not surface because they chose one of the 3 actions they can do.  Save Private with an inactive delete in days, Save Public with an inactive delete in days and encryption password, delete.

This will accomplish a couple of things.  Reduce the amount of junk.  Reduce the amount of files that are not in use.  Finally better secure public vs private maps where the actual use case is not long term storage but a quick need to collaborate where they need it then erased when they are done.

**Comment by b-solution** [comment]
I've worked according to the requirements. I have added sidekiq for schedule jobs. These jobs run on a daily basis.
Default number of days for deletion of file if not opened is 365 days .
![image](https://user-images.githubusercontent.com/5988861/150995366-a4ace2d2-7ef9-4352-8ecb-da685f73c56c.png)
![image](https://user-images.githubusercontent.com/5988861/150995429-ad5c4800-192b-4fe3-a3d7-558a4320c4bd.png)
