### ISSUE TITLE
google captcha to help prevent bots

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#287]
I would like the option if configured in the conf file to have google captcha as a requirement before opening an existing url or generating a new one in the app.  Once captcha has been done and the session is still active, they should not have to do it again unless their session is closed and they open a new one.  Even better their cookies expire

**Comment by b-solution** [comment]
@bluenevus I've added Google captcha.
Can you please update `Google re captcha key` and `Site URL` here.
![image](https://user-images.githubusercontent.com/5988861/160800959-fa7769a9-0b58-4860-bcaf-baf8ed25e8e4.png)
