### ISSUE TITLE
 Please switch to optimist as soon as possible. The trollop gem has been renamed to optimist and will no longer be supported.

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#288]
The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.

**Comment by b-solution** [comment]
@bluenevus I’ve looked into Gemfile and dependencies files we are not using “trollop” gem.

**Comment by bluenevus** [comment]
great
