### ISSUE TITLE
Sometimes when X days is adjusted from 90 on Save Map Key modal, an Alert modal displays

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#301]
Screenshot Example

![sometimes_when_X_days_adjusted_from_90_an_alert_modal_displays](https://user-images.githubusercontent.com/11938477/151605144-2d0a870c-6f72-45b4-8ded-9ccbbb0c4bc9.png)

**Comment by b-solution** [comment]
Can you please test it again. I've fixed this issue. If you do still face this issue let me know.

**Comment by LAlexMHllc** [comment]
Closing, since issue did not occur after several tests today.
