### ISSUE TITLE
Simplify PASSWORD PROTECT modal when password already exists.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#303]
User should not have to fill in the entire form to Save Private with existing password.
Screenshot Example

![Save_Private_reset_password_modal](https://user-images.githubusercontent.com/11938477/151820761-0ff4c5a7-dbd9-48bd-b9a8-9c785af911ce.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/152150092-9ea8da34-cfd4-4b47-94cd-48dcedf55724.png)
![image](https://user-images.githubusercontent.com/5988861/152150144-dea7b703-0817-4302-b434-e11956f4d033.png)
![image](https://user-images.githubusercontent.com/5988861/152150187-3f2bc1ed-72e3-4b2b-9ede-a16db7e3aac3.png)
![image](https://user-images.githubusercontent.com/5988861/152150242-6d22378d-6f39-454e-96ec-09e03b82b53d.png)
