### ISSUE TITLE
PASSWORD Modal should include "Back to Home" button, so user has option to return to Home Screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#304]
Screenshot Example

![PASSWORD_modal_should_include_Back-to-Home_button](https://user-images.githubusercontent.com/11938477/151827313-8316cb8e-6151-4c3e-b39a-97d3c265e198.png)

**Comment by b-solution** [comment]
Added "Back To Home" Button.
![image](https://user-images.githubusercontent.com/5988861/151955929-9637111e-7e90-46c8-88be-72f1fd871fd5.png)
