### ISSUE TITLE
Sometimes the index screen does not completely load, even after reload or restart computer

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#315]
Screenshot Example

![msuite-qa_index](https://user-images.githubusercontent.com/11938477/153010398-78f60555-0a9f-4e32-91d6-1348a6844f8d.png)

**Comment by bluenevus** [comment]
doesn't show up for me either.  blank screen.  tried to clobber the assets, bundle pristine, gem pristine etc etc and still a blank page.  the logs really don't say anything.  You see a get request and it looks like everything is good but nothing shows.  tried in firefox, chrome, edge and incognito modes for all.  Checked permissions on the folders and ruby and they are good also...just a blank page
