### ISSUE TITLE
White Board map: When an element is selected, user should be able to adjust thickness by clicking increase/decrease

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#317]
Screenshot Example

![whiteboard_user_should_be_able_adjust_thickness_of_selected_element_by_clicking_increase_decrease](https://user-images.githubusercontent.com/11938477/153238877-20e78676-f968-4c29-ad19-64fc86a992d0.png)

**Comment by b-solution** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/153374239-09728dc6-753b-4bb3-9a15-a75d981e0b4d.png">
