### ISSUE TITLE
White Board map: Element should stay selected, until user clicks off of it OR adds another object to the board.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#318]
Screenshot Example

![whiteboard_element_should_remain_selected_until_user_clicks_off_of_it](https://user-images.githubusercontent.com/11938477/153238366-7239b05b-3d88-4a5d-aa54-54c421f45799.png)

**Comment by LAlexMHllc** [comment]
NOTE: The element stays selected with shift key, but sometimes adjusting is awkward

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed these issue can you please check it again and let me know if its not work.

**Comment by LAlexMHllc** [comment]
After more than one object is added to the white board, sometimes the new object automatically gets deselected after a second.
