### ISSUE TITLE
all apps in the suite should have a save button located in the same place

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#324]
Its missing the save button and the save button should pop this dialog and return them to the map they are working in since they are working on the map and not navigating away as if they are clicking the logo in the left which is navigating them back to home

![image](https://user-images.githubusercontent.com/3675043/154309132-5b722f40-03c6-4964-a6f8-f304d741db5a.png)

**Comment by b-solution** [comment]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/5988861/155966443-5eb9e444-88f4-4d7d-a80d-0b8bce973adb.png">

**Comment by LAlexMHllc** [comment]
Remove "Save" button from map key modal, and include "Save" button on the header bar in the same position on all maps.
Screenshot Example

![include_Save_button_on_header_bar](https://user-images.githubusercontent.com/11938477/156009351-b87a1aa1-16d3-4b2f-b1d0-ac386fa467da.png)

When the "Save" button is clicked, then display the map key modal.
When the app is saved using the Save button on the header bar, the map should remain displayed, instead of returning to index screen.

**Comment by bluenevus** [comment]
So like microsoft office, there is always a save button.  In our case we are missing that and the microhealth logo isn't a save button, but a way to go back to the home screen.  If the user clicks that, the dialog pops up and they have the option to save private, save public or delete or cancel or close the dialog and stay on the page.  If they click save private or save public or delete they it will do that action and take them back to the home screen. 

However, if they click the save button on each app header page.  That means they are working on the document and want to stay there and not navigate away but just save it because that is the behavior microsoft office taught us even when there is an "autosave".  So we provide that button that launches the same save dialog however, rather than navigating away like clciking the microhealth logo, they save and stay on the page they are working on.

**Comment by LAlexMHllc** [comment]
Screenshot Example of Save Public function

![save-public_function](https://user-images.githubusercontent.com/11938477/156054270-275e35f0-e13b-4a41-972a-08e40a723b69.png)

___________________________________________________________________________________________________________

Screenshot Example of Save Private function

![save-as_show_password_combined_modal](https://user-images.githubusercontent.com/11938477/156054359-455799d0-c5ab-42bd-ab18-04d4439c65ac.png)

**Comment by LAlexMHllc** [comment]
See Issue #364
