### ISSUE TITLE
Clicking "Save Private" should display the PASSWORD modal on Mindmap, just like the other map types

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#326]
Screenshot Example of mindmap screen

![mindmap_screen](https://user-images.githubusercontent.com/11938477/154322069-1f9f288f-3b9c-41ee-bd9c-a58bbfd0bbf5.png)

Screenshot Example of Save Map Key modal
NOTE: Clicking "Save Private" button on Save Key Map modal for mindmap currently does nothing

![mindmap_clicking_Save-Private_button_should_display_Password_modal](https://user-images.githubusercontent.com/11938477/154322101-94466190-77c3-4c7b-be7b-95a43474b6a8.png)

**Comment by bluenevus** [comment]
I don't want to remove the save private button but need a Save button that allows the user to save with the same dialog but return them to the workspace they are working on because they aren't navigating away as if they are clicking the microhealth logo

**Comment by b-solution** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/155522704-966705fc-e0c3-40db-9e29-09f5d2a7c914.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/155522810-582a93be-c463-40bf-b9b9-8f95798c74ab.png">
