### ISSUE TITLE
WhiteBoard Map: "Text" button should have consistent height and line-weight as the others

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#328]
Screenshot Example

![whiteboard_text_button_should_have_consistent_height_line-weight](https://user-images.githubusercontent.com/11938477/154325918-a875270b-01c3-4c9c-9d71-ec07d45c50a7.png)

**Comment by b-solution** [comment]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/5988861/154450353-e5c32a0e-cb1e-4fc3-ae13-4ffedd79aa7e.png">
