### ISSUE TITLE
Tree Chart map: Should be able to change the background color of Central Idea node

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#329]
Screenshot Example

![tree-chart_should_be_able_change_background_color_Central_Idea_node](https://user-images.githubusercontent.com/11938477/154328653-afba3f5d-5c84-46d0-a0ec-9ca74c9e460e.png)

**Comment by b-solution** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/5988861/154795125-16ecc4eb-0647-4843-b4dd-1ba5580c81ff.png">
