### ISSUE TITLE
Kanban map: Should space action buttons like Tree Chart and Tree Map

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#330]
Screenshot Example

![kanban_should_space_action_buttons_on_cards_like_tree-maps](https://user-images.githubusercontent.com/11938477/154331069-b0d74e6c-5b6e-49d1-b639-201b856abc80.png)

**Comment by b-solution** [comment]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/5988861/154449024-76b6c0d2-f468-4dab-af03-ecd3e518c693.png">
