### ISSUE TITLE
after drawing an object in whiteboard, if I select it, I should have an option to increase or decrease its line thickness

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#332]
right now, I can select the thickness before I draw but after I draw and object, there is no way to change the thickness
after drawing an object in whiteboard, if I select it, I should have an option to increase or decrease its line thickness
![image](https://user-images.githubusercontent.com/3675043/154388697-4c45d38a-a970-438f-8a93-112a07a63e35.png)

**Comment by b-solution** [comment]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/5988861/155091060-e08a66ec-062d-4f6f-96fa-3ba4d3d76ca4.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/5988861/155091112-ed9a36b6-5258-4963-a5b3-5768835da9e9.png">
