### ISSUE TITLE
after drawing an object in whiteboard, if I select it, I should have an option to change its color

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#333]
right now, I can select the color before I draw but after I draw and object, there is no way to change the color
after drawing an object in whiteboard, if I select it, I should have an option to change its color
![image](https://user-images.githubusercontent.com/3675043/154388697-4c45d38a-a970-438f-8a93-112a07a63e35.png)

**Comment by LAlexMHllc** [comment]
Same as Issue #321

**Comment by b-solution** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/5988861/154970761-d0d339cc-9550-497c-b8f4-75d549c2179f.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/5988861/154970832-ae911d17-8053-4d46-8391-93a664c578cc.png">
