### ISSUE TITLE
sidekiq getting error when deletings

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#341]
Feb 20 09:33:07 kvm-msuite-qa sidekiq[1032]: 2022-02-20T14:33:07.289Z pid=1032 tid=uv8vc WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[],"class":"FileInActiveWorker","jid":"49e07246dea625243d37b7e9","created_at":1645358405.099464,"enqueued_at":1645367587.2743893,"error_message":"Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`mindmap_production`.`nodes`, CONSTRAINT `fk_rails_4c829c19ff` FOREIGN KEY (`mindmap_id`) REFERENCES `mindmaps` (`id`)): DELETE FROM `mindmaps` WHERE `mindmaps`.`id` = 263","error_class":"ActiveRecord::StatementInvalid","failed_at":1645358410.9157925,"retry_count":8,"retried_at":1645363388.974356},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"args\":[],\"class\":\"FileInActiveWorker\",\"jid\":\"49e07246dea625243d37b7e9\",\"created_at\":1645358405.099464,\"enqueued_at\":1645367587.2743893,\"error_message\":\"Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`mindmap_production`.`nodes`, CONSTRAINT `fk_rails_4c829c19ff` FOREIGN KEY (`mindmap_id`) REFERENCES `mindmaps` (`id`)): DELETE FROM `mindmaps` WHERE `mindmaps`.`id` = 263\",\"error_class\":\"ActiveRecord::StatementInvalid\",\"failed_at\":1645358410.9157925,\"retry_count\":8,\"retried_at\":1645363388.974356}"}

Feb 20 09:33:07 kvm-msuite-qa sidekiq[1032]: 2022-02-20T14:33:07.289Z pid=1032 tid=uv8vc WARN: ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`mindmap_production`.`nodes`, CONSTRAINT `fk_rails_4c829c19ff` FOREIGN KEY (`mindmap_id`) REFERENCES `mindmaps` (`id`)): DELETE FROM `mindmaps` WHERE `mindmaps`.`id` = 263
--

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue. If you do still face this issue let me know.
