### ISSUE TITLE
The Update Color modal should completely display when a Text object is selected and the Color button is clicked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#347]
Screenshot Example

![text-object-selected_color-button-clicked_update-color-modal-should-completely-display](https://user-images.githubusercontent.com/11938477/155160421-954e7a30-d8fc-485f-abd3-138cfe1157af.png)

**Comment by b-solution** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/5988861/155319610-b9a3fd54-ab87-48b2-810e-ebcc0f8f5ca4.png">
