### ISSUE TITLE
mindmaps header and treechart headers are misaligned

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#361]
![image](https://user-images.githubusercontent.com/3675043/156338025-341ff211-7994-4bd4-a811-431ee7407ec7.png)

![image](https://user-images.githubusercontent.com/3675043/156338054-4f7b68b1-b74d-43c8-8516-553adb82dd20.png)

**Comment by b-solution** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/156402609-85da6cb1-fc0f-486c-b4ac-2d66d01bbeea.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/156402673-ec0ae0b3-8a42-40ff-a91a-92bd47842b8a.png">
