### ISSUE TITLE
"Save" button on header bar should display text on hover, like the other buttons

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#362]
Screenshot Example

![save_button_should_display_text_on-hover](https://user-images.githubusercontent.com/11938477/156384139-2806b5d0-adea-432a-b90a-69fd2d80ffde.png)

**Comment by b-solution** [comment]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/5988861/156404845-1cf6ddcd-0cce-4392-96f2-d595d570f14a.png">
<img width="299" alt="image" src="https://user-images.githubusercontent.com/5988861/156404890-719e280a-34b5-47b2-83c7-f82cffe9ca96.png">
