### ISSUE TITLE
Kanban map: Fix update background color of card function

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#363]
Selecting a color on the Color modal should change the background color of the card.
Clicking "Update" should update the background color of the card.
Screenshot Example

![kanban_clicking_update_should_change_card_background_color](https://user-images.githubusercontent.com/11938477/156387461-cc233723-aeaf-4902-9aab-369cf4a3ff19.png)

**Comment by b-solution** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/5988861/156740182-eecbdbaf-70db-48d5-9e51-c622cce27b94.png">
