### ISSUE TITLE
Clicking Logo, then Save Private with Password, should return to Index screen after success message displays

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#364]
Screenshot Example

![logo_save-private_success_should_display_index](https://user-images.githubusercontent.com/11938477/156394453-f12e3455-9411-4ac8-8740-540ea93ac58b.png)

**Comment by LAlexMHllc** [comment]
Reopening, since still needs to be fixed for Tree Chart

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please check it and let me know if its not work.

**Comment by LAlexMHllc** [comment]
Fixed
