### ISSUE TITLE
Should be able to Delete map that was Saved Private

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#371]
Clicked Delete button on modal OR Delete button on header bar; confirmed delete; entered correct Password, then clicked Verify. 
Map should have been deleted, then the Index screen should have displayed.

Screenshot Example

![saved_private_map_should_be_deleted_correct_password_verify_click](https://user-images.githubusercontent.com/11938477/156799170-fbb915da-dd12-415b-8602-bf02ebdebd17.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if its not work.

**Comment by LAlexMHllc** [comment]
Confirmed, fixed
