### ISSUE TITLE
Program Settings Users: Add User(s) to Program form modal missing labels/input fields

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#377]
After last update, the form elements don't display.
Screenshot Example

![program_settings_users_add_user_to_program_form_without_input_fields](https://user-images.githubusercontent.com/11938477/157289746-2504a763-2dad-43bc-8bea-bab649211226.png)

**Comment by bluenevus** [comment]
really this needs to be disabled.  msuite really shouldn't have users and the admin account is only for sidekiq

**Comment by bluenevus** [comment]
I think you meant mpath
