### ISSUE TITLE
Tree Map and Tree Chart: Fix Delete tooltips

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#380]
Screenshot Example of Tree Map

![tree_map_delete_map_tooltip](https://user-images.githubusercontent.com/11938477/157484727-7b16d726-4e16-4148-abfc-c41857cac3c1.png)

Screenshot Example of Tree Chart

![tree_chart_delete_map__delete_node_tooltips](https://user-images.githubusercontent.com/11938477/157484982-cfcfec59-07e5-470f-b789-609d2a3dde8c.png)

**Comment by bluenevus** [comment]
for treechart it should say delete node vs delete map

**Comment by LAlexMHllc** [comment]
Deleting main node will Delete Map
