### ISSUE TITLE
Tree Map: To be consistent, Add Child Node icon should have blue color.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#382]
Screenshot Example

![tree_map_add_chlid_node_color_should_be_blue](https://user-images.githubusercontent.com/11938477/157690949-1bc19c4d-ec12-4375-a3d8-330fbc7cc06f.png)

**Comment by b-solution** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/5988861/157862601-d64176bc-6a35-42f5-958c-233b479a6d24.png">
