### ISSUE TITLE
Tree Chart: To be consistent, tooltip should be "Add Child Node"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#383]
Screenshot Example

![tree_chart_tooltip_should_be_add_child_node_for_consistency](https://user-images.githubusercontent.com/11938477/157692262-e360c22f-3f99-46af-ba95-1f4774db7f0c.png)

**Comment by LAlexMHllc** [comment]
Tooltip should have cap "C" for "Child"
Screenshot Example

![tree_chart_tooltip_should_have_cap_C_for_Child](https://user-images.githubusercontent.com/11938477/158212155-ad88036b-3798-4464-b365-d4f20c1cea08.png)

**Comment by b-solution** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/5988861/158346760-9eb4e1f2-a09a-4451-b668-5a7092222a3a.png">
