### ISSUE TITLE
Tree Chart: To be consistent for new node, the Color Picker and Add Child Node links should display and function dependent upon Title status

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#384]
Screenshot Example of Tree Chart

![tree_chart_new_node_links](https://user-images.githubusercontent.com/11938477/157701986-35c09fdc-9557-4004-bff6-29b22c187722.png)

Should function like Kanban and Tree Map
Screenshot Example

![kanban_tree_map_new_node_color-picker_add_child_node_function_Title](https://user-images.githubusercontent.com/11938477/157702432-03fa8606-4e8e-4fc3-9e09-0cca89e2b88e.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed these issue please let me know if its not work.

**Comment by LAlexMHllc** [comment]
Fixed
