### ISSUE TITLE
White Board: Unable to truly deselect a resized object.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#393]
Even though handles do not display, moving the mouse still changes the object. User had to Reset or Reload.
Screenshot Example

![whiteboard_unable_to_truly_deselect_resized_object](https://user-images.githubusercontent.com/11938477/158431360-5d33a963-75d4-4959-8fab-643efde2bac0.png)

**Comment by LAlexMHllc** [comment]
Even when another object is added to the board and displays selected, the resized object still adjusts as the mouse is moved.
Screenshot Example

![whiteboard_unable_to_truly_deselect_resized_object_2](https://user-images.githubusercontent.com/11938477/158433824-9885244d-de53-4ad2-a853-6ce27f0f0c4c.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed these issue can you please test it again and let me know if it's not work.

**Comment by LAlexMHllc** [comment]
Closing, fixed
