### ISSUE TITLE
White Board: Clicking "Reset" should reset the board

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#396]
Clicking Reset button, with/without an object selected, should clear the board.

**Comment by LAlexMHllc** [comment]
Reopening, since map no longer resets when Reset clicked.
NOTE: Reset button was removed from the sidebar and now displays on the top menu.

**Comment by b-solution** [comment]
@LAlexMHllc In my side every thing is working fine and you can see this in video.
https://user-images.githubusercontent.com/5988861/163532290-0a058e55-3b7b-4350-b4a8-046a97a56eb0.mp4

**Comment by LAlexMHllc** [comment]
@b-solution Reset map does not function for this map, nor several of the other maps. See Issue #440
