### ISSUE TITLE
as a user, I would like to leave comments on a map

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#402]
as a user I would like to leave comments on a map.  as you can imagine the goal is to collaborate real time however, there may be times I just need to collaborate asynchronously.  in this case I need an icon located in the same place in each map to surface comments where I can read comments, reply to comments and create new comments.  I also need a way to mark thumbs up or thumbs down or a checkrmk so people can respond without actually leaving comments so that collaborators can acknowledge they reviewed or read it agreed with it or don't agree with it.  the checkmark is so they can use the comments as sort of a to do list on the map and check that a comment that could be a request or a task as done

**Comment by b-solution** [comment]
@bluenevus i want to ask you one thing and that is the case, whether a user can pass comments or only admins are allowed. Moreover, who is allowed for reactions(thumbs up, thumbs down, checkmark), user or admin or both?

**Comment by bluenevus** [comment]
its for anyone who has access to the map.  So if they don't password protect it, well its anyone.  if they password protect it then its only those that have password.  They really won't know who made the comment because well, there are no users to grab a name but that is for the user to figure out how they want to identify themselves.  The goal is for them to be able to comment so they can discuss next steps or what else they need to do or provide feedback etc

**Comment by b-solution** [comment]
@bluenevus @LAlexMHllc I've added comments option. You may check it now and tell me further about.
