### ISSUE TITLE
unable to rake db:migrate RAILS_ENV=production

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#406]
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json' at line 1: ALTER TABLE `mindmaps` ADD `canvas` json

same db version as the dev and test environments.  the difference is that I haven't updated this in a month so it missed a number of sequential updates.  not sure if that is the cause

**Comment by bluenevus** [comment]
== 20220314100216 AddCanvasToMindmap: migrating ===============================
-- add_column(:mindmaps, :canvas, :json)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json' at line 1: ALTER TABLE `mindmaps` ADD `canvas` json

**Comment by b-solution** [comment]
@bluenevus limitation:: we cannot preserve previous data with json to longtext format.

**Comment by b-solution** [comment]
@bluenevus I've fixed these issue, can you please test it again and let me know if its not work.

**Comment by bluenevus** [comment]
ok so now it worked on msuite in prod that didn't get updated for about a month and missed sequential updates however

other servers that got upgraded ever push for dev and test environments results in this error

Bundle complete! 32 Gemfile dependencies, 132 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
== 20220406113251 AddCanvasToMindmap: migrating ===============================
-- add_column(:mindmaps, :canvas, :longtext)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate column name 'canvas': ALTER TABLE `mindmaps` ADD `canvas` longtext

**Comment by b-solution** [comment]
@bluenevus can you please test it again.

**Comment by bluenevus** [comment]
working
