### ISSUE TITLE
Captcha should be positioned in the middle of the screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#410]
Screenshot Example

![captcha_should_be_positioned_middle_of_screen](https://user-images.githubusercontent.com/11938477/161585136-d430457c-1c3e-48f3-b9f0-0bd2eaf0e387.png)

**Comment by b-solution** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/161900540-00bcbf07-b3da-496c-a78f-7f79b556a5ac.png">
