### ISSUE TITLE
Flow Map: Sometimes after node Title updated, ALL Add Child Node links stop functioning.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#412]
Added child nodes to main node; then updated main node text. ALL Add Child Node links stopped functioning.
Screenshot Example

![flow-chart_after_update_central_idea_text_all_add_child_node_click_should_still_function](https://user-images.githubusercontent.com/11938477/161591256-1c41fd60-8fc0-476c-99b2-3c6642e98e2f.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/162189314-835933a3-8558-4b19-a37a-4023193fbaee.png)
![image](https://user-images.githubusercontent.com/5988861/162189406-d93db842-7c58-4525-9d78-343f38a6db5d.png)
