### ISSUE TITLE
Flow Map: Titles of default nodes should have blank instead of underscore

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#414]
To be consistent, default text should have blanks instead of underscores.
Screenshot Example

![flow-chart_node_title_should_have_blank_instead_of_underscore_by_default](https://user-images.githubusercontent.com/11938477/161595066-a8869d19-5787-4fd8-9a98-8e8865f10a3f.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/162189328-924f1626-5426-45cf-9835-4abdcfebf15a.png)
![image](https://user-images.githubusercontent.com/5988861/162189396-636753f3-6478-4467-bbe5-1ffa8a5d360e.png)

**Comment by LAlexMHllc** [comment]
Replace underscore on default nodes with blank space.
EXAMPLE: Default text for main node should be "Central Idea"
EXAMPLE: Default text for child node should be "Title Here"

**Comment by LAlexMHllc** [comment]
Closing, fixed
