### ISSUE TITLE
Flow Map: Icon on button and link node should match

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#417]
The arrow heads do not match for Link To. Only one direction for Dotted Link.
Screenshot Example

![flow-chart_icon_on_button_and_link_node_should_match](https://user-images.githubusercontent.com/11938477/161602141-4eeabbf9-f53b-4463-85fe-14f10fb90172.png)

**Comment by b-solution** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/5988861/161706055-e141f55f-14e8-4c94-9632-3a50932600e0.png">
