### ISSUE TITLE
Flow Map: Non-alphanumeric characters should not change to underscore when Title updated.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#423]
Title should accept non-numeric input, just like Tree Chart.
Screenshot Example

![flow-map_non-alphanumeric_characters_should_not_become_underscore_when_Title_updated](https://user-images.githubusercontent.com/11938477/161801557-88cda2f1-6ae9-4e35-a1aa-9efdb94fa6d3.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/162189288-02ac57e1-28ae-407c-a095-475cd8cb9466.png)
![image](https://user-images.githubusercontent.com/5988861/162189415-64fd84ac-eae9-45cd-8736-36fb6ae9ae30.png)
