### ISSUE TITLE
Flow Map: Node should not have arrow pointing to itself

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#424]
Screenshot Example

![flow_map_with_node_that_has_loop_arrow](https://user-images.githubusercontent.com/11938477/161835999-c78b0333-a265-4c6c-b273-e442aca2e997.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/162189280-2f3b2919-72a2-438a-a3d3-32132cf86c38.png)
![image](https://user-images.githubusercontent.com/5988861/162189420-b7093705-f85f-4445-bd74-43f29e00b6af.png)
