### ISSUE TITLE
All maps should include Reset button on top menu

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#432]
Screenshot Example

![all_maps_include_reset_button_top_menu](https://user-images.githubusercontent.com/11938477/162476734-910d7424-58fb-4a70-9628-e37c342e3f89.png)

WhiteBoard map: Should remove the Reset button from sidebar menu, and include Reset button on top menu bar.
Screenshot Example

![whiteboard_remove_reset_from_sidebar_and_include_on_top_menu](https://user-images.githubusercontent.com/11938477/162477380-337215b6-3c79-479f-8f98-eeebcd3ec99f.png)

**Comment by b-solution** [comment]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/5988861/163119057-2e4eeedb-18ab-40ca-8304-d95b5d18151a.png">
