### ISSUE TITLE
Update the message that displays when a shared map is open for more than one user, and the map gets deleted.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#443]
After a user confirms/deletes the map, the following message displays for the other user(s)
Screenshot Example

![were_sorry_message_after_open_map_deleted](https://user-images.githubusercontent.com/11938477/164085890-458013a2-9697-4f0a-b423-6639025f0fab.png)

Change message to, **"The file you were working on was deleted by a user."**

**Comment by b-solution** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/165243309-a6c76736-44f2-476f-8a83-a5e1667966a5.png">
