### ISSUE TITLE
ToDo: User should be able to edit dates

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#450]
Screenshot Example

![todo_should_be_able_edit_dates](https://user-images.githubusercontent.com/11938477/167881782-bc0a1248-9344-4465-8b8e-91674cb9be48.png)

**Comment by LAlexMHllc** [comment]
Edit Parent Due Date - DONE
Edit Child Due Date - Still needs to be fixed when Parent does not have Due Date

Screenshot Example

![should_be_able_edit_select_different_Due_Date_for_Child_ToDo_when_Parent_without_Due_Date](https://user-images.githubusercontent.com/11938477/169131542-d8079568-670a-4300-abde-496b15fb2a42.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
