### ISSUE TITLE
todo has a number of scroll bars even though there is no need for them on the page size

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#455]
it would make sense to have them there if the page is responding to different resolutions but if its not, there should be no scroll bars

![image](https://user-images.githubusercontent.com/3675043/168305560-c02c267b-20a2-4a50-a04b-4b316769d059.png)

**Comment by bluenevus** [comment]
ther is an outer frame scroll bar and an inner frame scroll bar and neither are on a page size that would require it

in general, there should NEVER be double scrollbars.  Thats just hard to do from a user stand point particularly on a list this simple

**Comment by LAlexMHllc** [comment]
There should be no scroll bars unless the screen is:
- too small
- resized, and responding to smaller dimensions

Screenshot Example with unnecessary horizontal and vertical scroll bars

![ToDo_with_unnecessary_scrollbars](https://user-images.githubusercontent.com/11938477/169092796-02fbb033-81af-4756-81aa-60144014a01f.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
The scrollbars do not display when needed.
Screenshot Example of missing vertical scrollbar

![ToDo_missing_vertical_scrollbar_when_ToDo_height_greater_than_browser_height](https://user-images.githubusercontent.com/11938477/169547863-cfcb852f-c32a-4eb5-903f-adf9d2c9b8ab.png)

Screenshot Example where ToDo list should have minimum width to display correctly with a horizontal scrollbar for narrow browser widths

![ToDo_missing_horizontal_scrollbar_with_better_layout_narrow_width](https://user-images.githubusercontent.com/11938477/169549225-6d2bdcd8-3e2c-4318-827e-1f98fcbcbf16.png)
