### ISSUE TITLE
ToDo: Since Date is not required, should be able to remove existing Date

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#457]
Edit Parent or Child
Screenshot Example

![ToDo_since_Date_not_required_should_be_able_remove_Date](https://user-images.githubusercontent.com/11938477/168874039-eb0c8f8b-2557-48c4-89cc-4ee6acd2c31c.png)

**Comment by b-solution** [comment]
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/5988861/169022159-ab60bc0e-435b-480f-889d-dcaeefa32a96.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/5988861/169022562-5679be1e-ab15-4ac4-b672-c2e6a437ef44.png">
