### ISSUE TITLE
ToDo: Should not be able to save entry without Title filled or with blank(s)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#458]
Screenshot Example

![ToDo_entry_should_not_save_without_Title_filled_or_with_blanks](https://user-images.githubusercontent.com/11938477/168645087-1c26d460-2d98-4631-ac48-99b5d1b476b0.png)

**Comment by b-solution** [comment]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/5988861/169032837-c9de8cbc-8b4f-4790-a2a6-d7e1f323711b.png">

**Comment by b-solution** [comment]
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/5988861/169037182-957e4150-4f73-4062-9070-0e94881c7070.png">

**Comment by LAlexMHllc** [comment]
Reopening, since should only be able to save Edit ToDo with non-blank Title.
Screenshot Example

![should_only_be_able_save_Edit_ToDo_with_non-blank_Title](https://user-images.githubusercontent.com/11938477/169363367-6fc2a759-15df-453d-89a1-694d1cfa4826.png)
