### ISSUE TITLE
ToDo: Adding a Child to Parent with Status = Complete should have changed the Status to Incomplete (unchecked)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#459]
Screenshot Example

![adding_child_to_Parent_with_status_Complete_should_have_changed_to_Incomplete](https://user-images.githubusercontent.com/11938477/168650003-663f522e-7900-4a8d-8cbf-70e1c63ed9c8.png)

**Comment by b-solution** [comment]
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/5988861/169025623-1312bfb7-ddd7-4e92-baeb-a686631ab9f1.png">
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/5988861/169026961-d6cddd62-0229-48d6-a0ae-18aafddc0130.png">

**Comment by LAlexMHllc** [comment]
Reopening, since last update removed Parent/Child auto-check relationship

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.
