### ISSUE TITLE
ToDo: Changing the Parent's status to Incomplete (unchecked) should not change the status of its Children

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#460]
Screenshot Example

![changing_Parent_status_to_Incomplete_should_not_change_status_of_its_Children](https://user-images.githubusercontent.com/11938477/168652078-6b551588-430e-4fe4-af10-3878b9715c15.png)

**Comment by b-solution** [comment]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/5988861/169028464-8383fe1b-2e80-47a1-b062-84b2d7ed0aed.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/5988861/169028668-cca6e873-ca86-4639-b104-df7d8ad69264.png">

**Comment by LAlexMHllc** [comment]
Reopening, since last update removed Parent/Child auto-check relationship

**Comment by LAlexMHllc** [comment]
Closing, fixed
