### ISSUE TITLE
ToDo: Deleting the only Child with status Incomplete, given other Child(ren) have status Complete, should update the Parent's status to Complete

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#461]
Screenshot Example

![deleting_only_child_with_status_Incomplete_when_others_Complete_should_update_Parent_status_Complete](https://user-images.githubusercontent.com/11938477/168657441-e75c112f-385a-4039-b672-b2d7fe2218f0.png)

**Comment by b-solution** [comment]
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/5988861/169024023-36c565ff-6f71-4c98-8afe-8fba3d43d826.png">
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/5988861/169024189-f680d87b-6a8c-4939-a6df-0e4fea706381.png">

**Comment by LAlexMHllc** [comment]
Reopening, since last update removed Parent/Child auto-check relationship

**Comment by LAlexMHllc** [comment]
Closing, do not fix. Frank does not want checking all Children to check Parent.
