### ISSUE TITLE
Actionable Filter should include Children

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#462]
Screenshot Example

![Actionable_Filter_should_include_Children](https://user-images.githubusercontent.com/11938477/168659098-c214816b-e1ed-465b-a344-14afac19a8d4.png)

**Comment by b-solution** [comment]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/5988861/169029470-1d3bfa3b-400f-40cc-8290-56b0e6ad2823.png">
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/5988861/169029698-0f6e351e-2863-483e-bea1-3c110f3a916a.png">
