### ISSUE TITLE
All Maps: Checkmarks and buttons should display on Export Files

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#463]
Screenshot Example of Browser

![ToDo_in_browser](https://user-images.githubusercontent.com/11938477/168661213-43c191b8-11bc-4e85-9383-2bfbda48e4c2.png)

Screenshot Example of Export PDF

![ToDo_Export_PDF](https://user-images.githubusercontent.com/11938477/168661653-7620e77a-2cb3-413b-8fa8-e637f83f288d.png)

Screenshot Example of Export PNG

![ToDo_Export_PNG](https://user-images.githubusercontent.com/11938477/168661724-67d9b2bd-d4d2-4188-b2ab-3524ce4cfd60.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example of Kanban Map

![kanban_export_without_button_images](https://user-images.githubusercontent.com/11938477/168665141-228904f6-d180-4655-b651-ddbea86b05f3.png)


Screenshot Example of Tree Map

![tree_map_export_without_button_images](https://user-images.githubusercontent.com/11938477/168664432-5ff858cd-8b8b-4e3e-8c33-8d402aa595f2.png)

Screenshot Example of Tree Chart

![tree_chart_export_without_button_images](https://user-images.githubusercontent.com/11938477/168664898-d6690264-ce9b-4db6-8f3b-b7b03a4d4ad2.png)

Screenshot Example of Flow Map

![flow_chart_export_without_button_images](https://user-images.githubusercontent.com/11938477/168664923-7f80cf0f-f4f2-4bfd-953e-01792bdae3e8.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
![DEhkYPBHkUJXZVU](https://user-images.githubusercontent.com/5988861/196917346-2ff7414a-e752-4b1e-b87b-afb2ecd627b3.png)
![6Ix0n6MvzUHxRRh](https://user-images.githubusercontent.com/5988861/196917361-cece97bc-7c0e-4494-a200-391f8a3d2119.png)
![DRDif9UBqmhcYJ7](https://user-images.githubusercontent.com/5988861/196917375-96e8cce5-a170-4940-8717-6ce729f226eb.png)

![pKQwhfSvCyj7W0Y](https://user-images.githubusercontent.com/5988861/196917329-eaf0dbf2-b043-4e1e-a7a3-c080b6cbf947.png)
![sNkb44g2l35VjGF](https://user-images.githubusercontent.com/5988861/196917284-e6642511-3c52-445b-af0c-e603812a4b81.png)
