### ISSUE TITLE
ToDo: Cancel icon should be different than Delete icon

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#465]
Screenshot Example

![ToDo_Cancel_icon_should_be_different_than_Delete_icon](https://user-images.githubusercontent.com/11938477/168835394-c8df762d-eb1a-472f-b2b2-95fb0b2b063c.png)

**Comment by LAlexMHllc** [comment]
Maybe an image with a circle with a slash through it for Cancel icon

**Comment by LAlexMHllc** [comment]
Prefer a different icon than "X" for Cancel

**Comment by b-solution** [comment]
@LAlexMHllc I've change the icon can you please check it and let me know.
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/5988861/169495947-4b456024-ad5e-4843-9651-abd30138583d.png">

**Comment by LAlexMHllc** [comment]
Saved Parent and Child ToDos should have an "X" for Delete, to be consistent with the rest of the Maps in the App.
Edit ToDo for Parent and Child should have consistent "Cancel" icon.
The trash can icon is usually used for Delete, not Cancel, so preferably use a circle with a slash through it (fa-ban) for Cancel .

**Comment by LAlexMHllc** [comment]
Closing, fixed
