### ISSUE TITLE
Should be able to Cancel or Reset a new Parent ToDo

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#466]
Screenshot Example

![should_be_able_cancel_or_reset_new_Parent_ToDo](https://user-images.githubusercontent.com/11938477/168869829-9034d4c9-3164-48f1-b0f4-3ae10f1c9915.png)

**Comment by b-solution** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/169275303-6b01bc99-61da-4350-a2fa-212740885ac3.png">

**Comment by LAlexMHllc** [comment]
Closing, fixed
