### ISSUE TITLE
ToDo forms: Change checkmark icon to Save icon

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#475]

**Comment by b-solution** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/169497382-09c3f0f8-77f1-42a9-b601-0ad53cde6c46.png">

**Comment by LAlexMHllc** [comment]
Would prefer fa-save

**Comment by b-solution** [comment]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/5988861/169770748-834e6094-55c8-4575-bf81-18e1237fc5b9.png">
