### ISSUE TITLE
ToDo: A Parent without a Due Date with a Child with a Due Date should display after a Parent with an earlier Due Date

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#477]
Screenshot Example

![ToDo_Parent_without_Due-Date_with_child_with_Due_Date_should_display_after_Parent_with_earlier_Due-Date](https://user-images.githubusercontent.com/11938477/169146367-431a17a7-f19e-4a4f-8cf7-d1f31ee43bce.png)

**Comment by bluenevus** [comment]
We dont want to constrain user with rules.  The rquirement really needs to allow users to drag and drop to reorder vs us enforcing an order beyond sequential entry of what you see is what you get
