### ISSUE TITLE
ToDo: Clicking toggle to "Actionable" should hide checked ToDos, NOT uncheck all

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#483]
Screenshot Example

![clicking_Actionable_should_hide_checked_ToDos_NOT_uncheck_All](https://user-images.githubusercontent.com/11938477/169346642-96e86f9f-0d0a-4b48-beaa-2762a217e4ab.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
