### ISSUE TITLE
ToDo: Text on the toggle should be easier to read

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#486]
Screenshot Example

![ToDo_text_on_toggle_should_be_easier_to_read](https://user-images.githubusercontent.com/11938477/169371833-457588ac-61e4-4260-ae0e-5c4f4ce00da1.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed design. Let me know if you want other sort of design.

**Comment by LAlexMHllc** [comment]
Closing, fixed
