### ISSUE TITLE
landing page should be responsive.  no matter what the resolution, there is a scroll bar and I have to scroll rather than everything just fitting on the page

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#487]
landing page should be responsive.  no matter what the resolution, there is a scroll bar and I have to scroll rather than everything just fitting on the page

![image](https://user-images.githubusercontent.com/3675043/169424299-25980a7f-8fb2-46fd-9f46-068a1c3c77a1.png)

**Comment by LAlexMHllc** [comment]
The boxes should be the same size, but just resize or shuffle to fit on a smaller screen.
Screenshot Example

![index_responsive_layout_expect](https://user-images.githubusercontent.com/11938477/170314881-c433afad-6744-4d64-9dbb-07712431b14c.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.
