### ISSUE TITLE
Whiteboard: The Color Picker should only adjust/update a selected object

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#494]
Screenshot Example after Circle clicked to include circle on the whiteboard, then clicked Color to display Color Picker

![whiteboard_Color_Picker_should_adjust_update_the_selected_object](https://user-images.githubusercontent.com/11938477/169595621-ee2138ae-c6df-4091-97b3-cf8914bcb7ae.png)

**Comment by LAlexMHllc** [comment]
Sometimes user has to deselect object, then select object to adjust/update with Color Picker

**Comment by LAlexMHllc** [comment]
Screenshot Example where no object is selected, yet the color was updated by the Color Picker

![whiteboard_color_picker_should_not_update_non-selected_object](https://user-images.githubusercontent.com/11938477/175075995-6c11cd10-8eed-4d56-b576-cbbe5e4f13aa.png)

**Comment by LAlexMHllc** [comment]
Still needs work. Sometimes an unselected object still gets adjusted.

**Comment by LAlexMHllc** [comment]
@b-solution  Still not fixed.

**Comment by b-solution** [comment]
@LAlexMHllc I have Fixed this issue. Please retest it again.

**Comment by LAlexMHllc** [comment]
Closing, fixed
