### ISSUE TITLE
ToDo Date should always display in the correct format

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#499]
Removed a Date from Edit ToDo; then same date displayed on another ToDo below the form in wrong format.
Screenshot Example

![Edit_ToDo_remove_Date__date_displayed_in_wrong_format_on_ToDo_below](https://user-images.githubusercontent.com/11938477/169873803-dbd02a67-410d-462d-95cc-f2cf99e4c3c3.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![ToDo_incorrect_Date_format_Displays](https://user-images.githubusercontent.com/11938477/169877744-e7f680d8-963d-44d4-ae55-5df4c985a3cc.png)

**Comment by LAlexMHllc** [comment]
When a Date is selected/changed without Save or Cancel clicked on an Edit ToDo, then another ToDo is selected to Edit, the Date displays incorrectly on the previously selected ToDo. User has to reload for the saved inputs to display.

**Comment by LAlexMHllc** [comment]
Still not fixed. See comment above self-assigned

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please let me know if its not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
