### ISSUE TITLE
Notepad: Clicking "B" active should change selected text to Bold

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#520]
Screenshot Example

![notepad_bold_type_should_function](https://user-images.githubusercontent.com/11938477/171192544-2ff6dbce-b3bf-4056-95e3-20e4952a61bd.png)

**Comment by b-solution** [comment]
@LAlexMHllc It's working good.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed
Screenshot Example

![notepad_bold_type_should_function_2](https://user-images.githubusercontent.com/11938477/174349129-7301f108-5c07-4bde-92c4-a1d9b7886a6d.png)

**Comment by andrewtran249** [comment]
confirming text does not bold on any font

**Comment by bluenevus** [comment]
same here...doesn't work

**Comment by b-solution** [comment]
@LAlexMHllc @andrewtran249 @bluenevus Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Text changed to Bold for my test

**Comment by LAlexMHllc** [comment]
Reopening, since issue returned after last update.
Screenshot Example

![notepad_text_styled_B_should_be_bold_2](https://user-images.githubusercontent.com/11938477/190670119-22614f4a-fd10-4f69-a9ab-261643b3ce02.png)
