### ISSUE TITLE
Index screen: Map selector container should be center horizontally

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#521]
Screenshot Example

![index_layout_map_selector_container_should_be_horizontally_centered](https://user-images.githubusercontent.com/11938477/171193556-c72aacf5-4c64-4272-8bad-03372399c4b0.png)

**Comment by b-solution** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/171371480-0b693d33-7be8-4c16-a67f-68932d90c139.png">
