### ISSUE TITLE
Beta disclaimer

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#525]
We need a badge across the top of the site that says Beta.  Preferably we can turn it on and off under admin or settings.  Preferably we can put the text in the badge.  Like you see below on a number of websites that advertise fork me however, it needs to say Beta Disclaimer or even better, we can configure the text and hyperlink to a page hosted by the system vs external site that we can put content in to show the beta disclaimer

![image](https://user-images.githubusercontent.com/3675043/171470257-abe73ab9-39c3-44a4-82b4-d67f58735f75.png)
so it will look like so
![image](https://user-images.githubusercontent.com/3675043/171470900-69e6a2a5-fa27-44de-b1ea-7896c799826b.png)

of course not say fork me on github but allow us to put the text we want which for now is Beta Disclaimer and hyperlink to a page we can configure in settings to actually have the disclaimer content shown.  The page that it will surface with url "/about" will need the same header as the landing page with the logo in the upper left so users can get back home

I imagine when we go out of beta, the badge will be gone and it will simply be an about page with an about link.  However, when we go back into beta, I have a setting to get the badge back vs about link if that makes sense

**Comment by b-solution** [comment]
@bluenevus I've added Beta disclaimer as you instruction can you please test it and let me know if its need you any changes.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5988861/171850421-95951f2b-686f-4684-be7d-0a301bd3d9b1.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/171850251-c6327596-c0e2-401f-ad1d-7d9d19f0a4d8.png">

**Comment by b-solution** [comment]
@bluenevus I've added can you please check it and let me know. :) 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/172190667-ab7c780d-236d-4b68-9293-34eec8df8a10.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/172190821-d641c6a9-7fc5-4bee-882b-94cec824e606.png">
