### ISSUE TITLE
as a user I would like to pivot the data from a spreadsheet in issue 224

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#530]
https://github.com/MicroHealthLLC/mSuite/issues/224  will provide a spreadsheet which the user can enter data or copy and paste data or have the data entered via the poll feature here https://github.com/MicroHealthLLC/mSuite/issues/529

and display this report.
![image](https://user-images.githubusercontent.com/3675043/171690917-667bb462-7f9f-4181-9c3c-ca703f6ec866.png)

ideally the dashboard is just a collection of editable reports so there aren't multiple steps.  you just add a report and if its one report then you just see the one editable report above.  If its 2 reports, its another row of the report like so

![image](https://user-images.githubusercontent.com/3675043/171691750-9d6b653a-6cd7-4c30-b1e1-c9e77cccbacf.png)

then if there is 3, it just keeps going so the user can simply keep adding them or remove them or move them around and reorder by drag and drop

**Comment by b-solution** [comment]
@bluenevus I think this one is **MRMS** issue.
