### ISSUE TITLE
links to About, Help, Terms, Privacy in the header bar

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#536]
I need some links in the upper right hand corner in the header that will open a new tab so they can go to a temporary About, help, terms of service and privacy policy page.  Specifically links to About, Help, Terms, Privacy in the header bar

that url needs to be configurable here please
![image](https://user-images.githubusercontent.com/3675043/171868040-b9947c1a-989d-4070-bb7c-f7a84be498eb.png)

in the Help link for example, I would configure the above to go here https://github.com/MicroHealthLLC/mSuite/wiki/User-Guide

**Comment by b-solution** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/172202626-6fb429f0-3ead-4080-9978-ebb35c1e809a.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/172202728-52b8d9d7-be05-4830-82a0-d9788412f71a.png">

**Comment by bluenevus** [comment]
I changed them in the titles but these should launch in new tab like the beta link does...open in new tab

![image](https://user-images.githubusercontent.com/3675043/172205732-fbc88cd3-096c-4147-b311-327ee07f9072.png)
