### ISSUE TITLE
Real time collaboration should function on all maps

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#537]
Does not function on:

- Mindmap
- Kanban
- Notepad

**Comment by bluenevus** [comment]
notepad seems to work.  you just have to wait til it autosaves in like a second or two.  However, mindmaps and kanban realtime collab doesn't work anymore

![image](https://user-images.githubusercontent.com/3675043/171919848-8214a37a-cc8c-4402-9b08-793611a27bfa.png)

**Comment by b-solution** [comment]
@bluenevus It's working fine on my side can you please test with latest code and let me know if it's not working.

**Comment by bluenevus** [comment]
just mindmap and kanban not working
![image](https://user-images.githubusercontent.com/3675043/172395392-3484f836-9ce0-44e7-a616-2bd9f3a510df.png)

![image](https://user-images.githubusercontent.com/3675043/172395600-7f2d208a-e2ea-4449-b139-1fedb8a1d182.png)

but the rest works as you can see in whiteboard below
![image](https://user-images.githubusercontent.com/3675043/172395859-14ac17cc-9e49-4582-bda0-7e380d4e9f74.png)

**Comment by bluenevus** [comment]
Could mindmap and kanban use a different websocket url than the rest because nginx expects it to be 

location /cable 

and proxy pass

proxy_pass https://msuite/cable/;

it works properly on the rest.  just mindmap and kanban doesn't work

**Comment by bluenevus** [comment]
so just to confirm, I created a link with just puma NO nginx and can confirm real time collaboration isn't working with mindmaps or kanban

![image](https://user-images.githubusercontent.com/3675043/172648031-5d34d75a-c08d-4df0-861b-ccb5bd618bf2.png)


![image](https://user-images.githubusercontent.com/3675043/172648262-2b3b9a6c-000f-466d-8a11-d8f1255a5cf2.png)

**Comment by b-solution** [comment]
I have fixed this issue. Will you please test it and tell me if the issue remains?

**Comment by b-solution** [comment]
@bluenevus I have fixed this issue. Please test it.

**Comment by bluenevus** [comment]
kanban works though.  YAY!!!!!

![image](https://user-images.githubusercontent.com/3675043/172861187-ba2d06cf-d33f-45de-b9e7-2973d34870e6.png)

**Comment by bluenevus** [comment]
YAY, we are back in business
