### ISSUE TITLE
treemap scrunches what was there before to enter new values vs what you see is what you get

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#539]
I added a node and expected it to look like this

![image](https://user-images.githubusercontent.com/3675043/171967806-f1f1370d-ac61-4b0d-988e-1741e4868c15.png)

but it looked like this...see the left hand side...that is everything crunched

![image](https://user-images.githubusercontent.com/3675043/171967788-75e41a15-4371-4b52-8a47-0ea1f9a2e298.png)

**Comment by bluenevus** [comment]
sometimes it scrunches and there is no getting it back and now it just says like this with cats collapsed and no way to get it back without clicking refresh on the screen

![image](https://user-images.githubusercontent.com/3675043/171968552-09da047c-2a77-43aa-9ffa-a4337a389ec1.png)

here is an example of me adding something to cats and it scrunches to the right
![image](https://user-images.githubusercontent.com/3675043/171968601-08314d0f-d414-4f51-bdaf-b874f28d8ad5.png)

here it collapsed some boxes in the middle and I had to click refresh
![image](https://user-images.githubusercontent.com/3675043/171968627-26ef074c-6aa7-4bb2-99c5-772ac5268fd4.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this, please test it and let me know if it's not working.
