### ISSUE TITLE
editing a node should have the same box with white background as adding a node

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#540]
this is what the box looks like when adding a node...its what you expect that tells you to enter info here

![image](https://user-images.githubusercontent.com/3675043/171968453-f80d6cce-8948-48bc-b4ed-b501217ce79b.png)

however if you click to edit, it doesn't activate it the same way with the white text box.  instead it remains what looks like you cant edit but you can

![image](https://user-images.githubusercontent.com/3675043/171968496-d086e7ef-5cdf-45e5-8858-f5af50e1d04c.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, please let me know if it's not working.
