### ISSUE TITLE
Comments modal: The "Edit" option should always be visible when the drop-down is displayed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#548]
Screenshot Example

![comments_modal_should_always_be_able_to_view_Edit_when_drop_down_is_displayed](https://user-images.githubusercontent.com/11938477/172226847-20bc4d78-10f5-475f-8bc9-f162eed83ae3.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please test it again.
