### ISSUE TITLE
Comments modal: Should be able to Edit or Remove a Reply

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#549]
Screenshot Example

![should_be_able_to_edit_or_remove_a_reply_to_Comment](https://user-images.githubusercontent.com/11938477/172232978-420f64b4-a27b-49b3-bd6d-3f44ff227d9b.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please test it again.
