### ISSUE TITLE
BETA Banner should fit within header section to avoid overlay on maps

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#554]
Screenshot Example

![BETA_banner_should_fit_within_header_section_to_avoid_overlay_map](https://user-images.githubusercontent.com/11938477/172405450-cc40f90f-37f7-41ef-99da-dbb3d1b9ceb9.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please test it again and let me know if its not working.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/172556928-854f6610-655a-406e-89d0-ef489e5a86a2.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/172557011-79d69721-68c5-43af-b14c-182d71a3b529.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/172557098-5a4b7ca4-fbfd-40e7-aaab-f4fb15003970.png">
