### ISSUE TITLE
there should be no edit button or save button.  it should be automatic

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#557]
low friction meaning less clicks.  you want to add words, you should be able to simply start typing and it saves.  You can have an indicator of editing just like notepad but then it needs to save automatically

![image](https://user-images.githubusercontent.com/3675043/172417217-ef79cfbb-de89-4aef-9cbe-d4cb3112ebad.png)

There are too many clicks to get to the point of editing then having to click save

![image](https://user-images.githubusercontent.com/3675043/172417372-1371c19b-a313-4ce0-920b-c6284abaffb8.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this one please check it and let me know if you need any changes.

**Comment by bluenevus** [comment]
I have a ticket for just removing the edit button.  you have automatic save but the user still has to click the edit button to edit or add info
