### ISSUE TITLE
scrollbars on comments should only show if needed but here its not but yet it shows

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#559]
![image](https://user-images.githubusercontent.com/3675043/172419046-257dea1b-b0b6-43a2-89be-0cfcabbd7b44.png)

![image](https://user-images.githubusercontent.com/3675043/172419077-f433d5af-940f-4638-881a-e846ab2b5db1.png)

this is the first time it was needed and as you can see the vertical bar is now active but the horizontal bar is not and not needed so should be gone

![image](https://user-images.githubusercontent.com/3675043/172419353-3a973920-27e1-4ef8-a2b3-236d9ca5c3d8.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, please test it again.
