### ISSUE TITLE
comments should behave like text messages

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#560]
I expected the newest comment to show on the bottom then having to scroll up for history.  That is every new comment or the latest is at the bottom like teams, like zoom, like facebook etc etc.  However, its reversed.  Newest comment should be at the bottom and you should start the user at the newest comment which is the bottom and the screen should scroll so the user stays at the bottom and has to scroll up to get history much like your sms messages or any chat program.  The workflow is backward and counterintuitive

![image](https://user-images.githubusercontent.com/3675043/172419866-a1e9b187-83cb-4ba7-9176-4db8e71f6867.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, please test it again.
