### ISSUE TITLE
Clicking Reset on Kanban should display default view

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#561]
Screenshot Example

![kanban_clicking_Reset_should_display_default_view](https://user-images.githubusercontent.com/11938477/172467411-4cd42b61-5fe4-4ec7-936f-7526726812f1.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Default Stage background is light grey, not white.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please test it again and let me know if it's not working.

> Default Stage background is light grey, not white.
