### ISSUE TITLE
mindmap edit box closes constantly sometimes while typing but always on a carriage return when I expected it to go to the next line vs close the box

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#569]
1. as I am typing the box closes randomly
2. if I hit carriage return to go the the next line, the modal closes when it should carriage return

![image](https://user-images.githubusercontent.com/3675043/172656727-a961e0b2-6be7-4590-b5d7-6a2604caee65.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this, can you please test it again and let me know if it's not working.
