### ISSUE TITLE
since file upload is disabled, the paper clip icon doesn't make sense.  it should be just a comment icon on mindmaps

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#571]
we no longer need a paperclip and comment icon.  we only need one because they only get to comment not upload

So there should be one icon, the comment bubble and if there is no comment, it can remain gray.  However, if there is a comment, we need to change the color to something like green or blue that indicates there is a comment someone has there

![image](https://user-images.githubusercontent.com/3675043/172657868-21f48765-8ec2-4c2e-883e-fa77a9f96d06.png)

**Comment by bluenevus** [comment]
still there 
![image](https://user-images.githubusercontent.com/3675043/174803483-a727af1a-2e16-4ff7-b619-00f0c764b798.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
