### ISSUE TITLE
to start a line should start at the beginning of the line where the cursor is.  The line starts in weird random places

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#578]
so just like mindmap, where the cursor is is where the user expect the line to start.  However, that is where the line ends and the line starts in some random place in the upper left. 

What you see is what you get expects the line to start where the cursor is then drag the line to its deestination or end where the cursor ends up

![image](https://user-images.githubusercontent.com/3675043/172861999-9592a710-7e6d-4020-ac25-8d90ae290077.png)

**Comment by b-solution** [comment]
@bluenevus Can you please test it with latest pull and let me know.

**Comment by bluenevus** [comment]
doesn't work.  the line ENDS where the cursor is instead of line STARTs where the cursor is.  if you were tot take a pencil and draw a line...that is the experience you expect.  you click the cursor, drag the line.  but that is not what is happening.  you click and drag but the line start in some weird location and ends where the cursor is so its not possible to draw a line between 2 objects because it never starts where your cursor is 
![image](https://user-images.githubusercontent.com/3675043/173376297-0f7bdc50-0d1e-444c-8fb2-4ba5a4515603.png)

**Comment by b-solution** [comment]
@bluenevus will you please retest it with latest code.

**Comment by b-solution** [comment]
@bluenevus Can you please test again.
