### ISSUE TITLE
White Board: Line should become selected when user clicks it

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#580]
Line does not become selected when clicked, until another non-Line object gets deselected.
Screenshot Example

![whiteboard_newly_drawn_line_should_become_selected_onclick](https://user-images.githubusercontent.com/11938477/172874446-4856407b-8047-4bd1-beba-ee7978f14c8a.png)

![whiteboard_newly_drawn_line_should_become_selected_onclick_2](https://user-images.githubusercontent.com/11938477/172878228-b36ebb94-8d20-4a64-8e6c-ec804bf1c4d4.png)

**Comment by bluenevus** [comment]
yeah...its really hard to select the line.  I have to click a million times to get lucky and select the line
