### ISSUE TITLE
what ever the last color picker chosen should be what the color picker is when I launch it

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#588]
so the problem is that after completing a map, I want to change colors of multiple boxes.  The problem is that it doesn't remember what I picked last.  So I have to copy and paste the hex code.  That is high friction for a user that just wants to make sure the boxes are a specific color based on what was used

![image](https://user-images.githubusercontent.com/3675043/173099447-f637881d-0bb7-470a-a097-e1840422faa8.png)

I mean you can add the last 5-10 boxes what ever fits that the user can select on what they previously used so they can just pick that and reuse the color they previously applied to a box.  It simply needs to be easy to reuse a color they already picked or applied to previous places in the app.  I mean anywhere in the app.  Treemap is the most problematic but its just hard to use the color picker everywhere because you can't reuse colors unless you copy and paste the hex which is HIGH HIGH friction for users.

![image](https://user-images.githubusercontent.com/3675043/173099877-3b0eba36-fab2-4214-bb64-3b26d492233d.png)

**Comment by bluenevus** [comment]
I don't see the recent colors in color picker though it was pushed

![image](https://user-images.githubusercontent.com/3675043/173611763-ed35e17d-cddf-4a2f-8c6e-a0cc9dbc3930.png)

**Comment by b-solution** [comment]
@bluenevus Can you please test with latest code.
