### ISSUE TITLE
drag and drop handle of central idea for flowmap and treechart should be the only place to click to start the drag and drop process...not anywhere on the box

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#591]
everytime I click central idea (where it says start her) anywhere it drags the node and its hard to stop dragging it until I put it back.

We need handles on the node like the subnode you have here where only when they click that it instantiates the drag and drop.  This will prevent the constant accidental drags everytime I clcik the box to edit central idea here

![image](https://user-images.githubusercontent.com/3675043/173101866-eb5958ea-6508-471f-9dae-460c9f8641cc.png)

**Comment by bluenevus** [comment]
so the problem is that its click and drag but what happens is if you click it it will drag around even when you are not holding down the mouse button to drag it.  I mean click is the feature to hold means you have to hold onto the mouse button.  the problem is that any place you click on the box even the sub node will hold on to the entire node and subnode and drag it around even if you're not clicking to hold.  just a single click

**Comment by LAlexMHllc** [comment]
Closing, fixed
