### ISSUE TITLE
there should be an indicator that comments exist

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#592]
i can imagine most of the time comments won't be used so there needs to be some indicator that there are comments.  For example, maybe the color should be something different.  Rather than blue, make it orange or green if there are comments

![image](https://user-images.githubusercontent.com/3675043/173106288-3317ca18-ca72-4374-a3c4-3c8a6b92ced8.png)

the point is that it should be easy to tell that something is different leading the user to say hey, whats going on, hover over and its says "new comments" which they may never had known unless it was obvious from the difference in color from the rest of the icons in the menu or difference in color meaning there are comments and a * meaning new comments since last viewed.

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue please test it again and let me know if it's not working.
