### ISSUE TITLE
The content of this menu should be icons on the chat

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#595]
![image](https://user-images.githubusercontent.com/3675043/173116951-ffc6fea7-8d78-43f3-b956-59345c5bf22c.png)

should have an edit, remove, reply icon etc so they don't have to do multiple clicks for common tasks and do away with ... menu
![image](https://user-images.githubusercontent.com/3675043/173116987-0f2eca35-befc-4745-8680-0bf927ff4dab.png)

Also the buttons might be too close because if I click ... I get the emoticons.  Conversely sometimes wh I click the emoticon icons, I get the ... menu items.  its quite unforgiving

![image](https://user-images.githubusercontent.com/3675043/173117423-300bf1fe-2dfb-4f2e-b630-ea4eb5e26d6d.png)

**Comment by b-solution** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/5988861/173592201-f119357e-f644-41ff-8c64-ef46ad56a137.png">

**Comment by bluenevus** [comment]
I don't see those icons and it shouldn't be behind a ... menu...just want those icons on the chat so we can save them an extra click they don't need to do.  right now its a 2 step process.  removing the ... menu and just putting the icons will make it a one click process
![image](https://user-images.githubusercontent.com/3675043/173610704-4cfd11d8-9573-4972-950c-aa01a01d84c5.png)

**Comment by b-solution** [comment]
@bluenevus Can you please test it again, I've fixed this issue.
