### ISSUE TITLE
for the whiteboard when you want to select an object I expected to click a hand icon but learned you have to unclick

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#598]
for the whiteboard when you want to select an object I expected to click a hand icon but learned you have to unclick

every paint program has what you see below, the hand that will allow me to select or grab.  Some just show a mouse cursor.  I was looking for that so I can select an object.  I learned you have to unclick pencil to then click an object.  That is ok but we need to also have what users are accustomed to seeing.  that hand or mouse cursor to select an object in whiteboard

![image](https://user-images.githubusercontent.com/3675043/173124847-2c70bdde-363a-4569-9194-fe2233c8a2f8.png)

**Comment by b-solution** [comment]
@bluenevus I've added selection tool. Kindly test it and let us know if this is working like you desired.

**Comment by bluenevus** [comment]
That works.

**Comment by bluenevus** [comment]
the problem is if you click select, it can't have anything else selected.  As you can see here, I clicked the line, then went to hit select, the line was still selected and as you can see it drew more line

![image](https://user-images.githubusercontent.com/3675043/173612627-dcabed98-579a-4a30-be53-b2114eacedbb.png)

**Comment by bluenevus** [comment]
also the select should be the top icon because the rest have to do with drawing.  The increase and decrease should be below that because that will change what the user selected.  The rest are drawing icons so they should go after 

Select, increas, descrease, pencil, line, etc etc redo, undo so that its logical on where the are drawing icons and what are not
