### ISSUE TITLE
the line icon in whiteboard should be different than the pencil.  it should be a line

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#599]
![image](https://user-images.githubusercontent.com/3675043/173125091-9f02e6e3-dc52-4e73-9173-0281bd6bf69e.png)

its the same icon when something more like this was expected

![image](https://user-images.githubusercontent.com/3675043/173125133-a6296472-65c2-4b25-a761-44a2379b8b28.png)

**Comment by b-solution** [comment]
@bluenevus I've changed the icon, can you please check it and let me know.
