### ISSUE TITLE
FlowMap, TreeChart, TreeMap, Kanban, and ToDo: Put more space before "x", since confirm delete node function will be removed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#603]

**Comment by bluenevus** [comment]
the purpose is to reduce the chance of accidental delete since confirmation is being removed in #602

**Comment by b-solution** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/180737920-3c7558cb-9d11-4e66-af94-ff5776683343.png">
