### ISSUE TITLE
WhiteBoard: "Select" should be active after new object added to board

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#616]
Screenshot Example

![whiteboard_Selected_link_should_be_active_after_new_object_added_to_board](https://user-images.githubusercontent.com/11938477/173628944-845aa2de-6fae-4091-888b-3170e5f14726.png)

**Comment by LAlexMHllc** [comment]
Still needs to be after "Text" object added to board
Screenshot Example

![clicked_Text_so_Select_should_be_active_when_Text-Object_added_to_board](https://user-images.githubusercontent.com/11938477/173872547-6490638b-a926-4fab-b936-22353f788cb3.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again
