### ISSUE TITLE
Color Picker should not save duplicate recently used colors

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#618]
Screenshot Example

![color_picker_saves_duplicate_recently_used_colors](https://user-images.githubusercontent.com/11938477/173633346-fc54f8a2-5206-44c1-93bd-cf9bf9decde8.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, please test it again and let me know if it's not working.
