### ISSUE TITLE
WhiteBoard - Object should become deselected by: clicking anywhere that is not the object; or unclicking the hand grab icon.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#621]

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
When "Select" (hand grab icon) is inactive, no object should be selected
Screenshot Example

![whiteboard_object_should_not_be_selected_when_SELECT_is_inactive](https://user-images.githubusercontent.com/11938477/173857189-16157ff1-7e2c-41f7-ab6c-686858805d73.png)

**Comment by andrewtran249** [comment]
[Test]
I worked with a team of 5 including myself to recreate the chart seen here within whiteboard: [DiSC Wheel_13JUN22.pdf](https://github.com/MicroHealthLLC/mSuite/files/8912552/DiSC.Wheel_13JUN22.pdf)

I was able to create the diagram and 4 quadrant letter labels. The 4 remaining members were tasked with recreating the smaller circles containing initials and placing them on the diagram in their respective positions.

[Outcome]
- the app could not distinguish who was attempting to use which tool
- various users attempted to create circles and text boxes simultaneously
- circles and text boxes dragged onto the diagram became undone without action from a user
- these issues persisted with multiple users attempting to use the same tools as well as when 2 users attempted to use 2 different tools simultaneously

**Comment by b-solution** [comment]
@LAlexMHllc @bluenevus I've fixed this issue. Will you please retest it.

**Comment by LAlexMHllc** [comment]
Object should become deselected by: clicking anywhere that is not the object; or unclicking the hand grab icon - DONE
