### ISSUE TITLE
notepad: from time to time the cursor will go back to the beginning of the document and keep going back

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#631]
As I am typing and what looks like the document goes from editing to saving, the cursor jumps from wherever it is to the beginning of the document. Its not all the time. I'm not sure when or why it does that. But from time to time, where I expected to cursor to remain where I'm at as I'm typing, It will go to the beginning of the paragraph. Its a hit or miss when that happens and the only thing I can say is that its seems to be as its toggling between editing and saving.  But its not all the time but when it happens...it does so in fits where you can't do anything because it will keep taking you back to the top at the beginning of the paragraph.

![image](https://user-images.githubusercontent.com/3675043/173869804-d3f3304b-96f0-4bae-871d-95b8779cb5d0.png)

**Comment by bluenevus** [comment]
I linked it to #635 because this problem of the cursor jumping to the beginning of the document happens as the bounce goes down from 1000ms to 750ms and at 10ms it was unbearable.

**Comment by b-solution** [comment]
@bluenevus can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
@b-solution  Still needs to be fixed

**Comment by bluenevus** [comment]
it happens primarily when you do real time collaboration.  Just tested it myself.  And the cursor jumps to the beginning of the document.

**Comment by b-solution** [comment]
@bluenevus  @LAlexMHllc I have fixed this issue. Please tell me if it's not working for you
