### ISSUE TITLE
Notepad: Should not be more than one step behind being in sync after text style changes

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#635]
Screenshot Example

![notepad_applying_text_style_changes_more_than_one_step_behind_being_in_sync](https://user-images.githubusercontent.com/11938477/173900534-3c150747-dbfd-4c8d-8091-9291151f1c14.png)

**Comment by bluenevus** [comment]
I think some of the issue is when do you pause to save so it looks like its waiting for a few seconds of pause to initiate a save.

**Comment by bluenevus** [comment]
it doesn't let me type at all.  the cursor doesn't move to the right but stays at the start position so I'm always at the start like so

![image](https://user-images.githubusercontent.com/3675043/174103729-5cf12d1b-8786-4a65-beeb-d12f86c24467.png)

**Comment by bluenevus** [comment]
its so bad right now I can't type anything at all.  the cursor will remain at the start position like the image above.  as I type stuff is being erased and that is without collaborating.  its simply not working

**Comment by bluenevus** [comment]
@bilel-kedidi @bilel-kedidi  I reverted v-debounce:10ms to v-debounce:1000ms

**Comment by b-solution** [comment]
@bluenevus Can you please test it again and let me know if it's not working.
