### ISSUE TITLE
Spreadsheet: Real time barely functions

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#647]
Screenshot Example

![spreadsheet_real_time_barely_functions](https://user-images.githubusercontent.com/11938477/174337450-52cfd632-c950-4183-86aa-dbacb4d59871.png)

**Comment by bluenevus** [comment]
didn't work at all for me...I didn't even get some things to sync.  Only syncs with a manual refresh
![MicrosoftTeams-image](https://user-images.githubusercontent.com/3675043/174337284-146d46a2-897a-484a-b9b9-0ddca2c527c4.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know if it's not working.
