### ISSUE TITLE
Spreadsheet: User should have option to download Excel, csv, png, or pdf

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#651]
Screenshot Example

![spreadsheet_downloads](https://user-images.githubusercontent.com/11938477/174357863-2bfd05f0-988d-4389-9dd3-da5d159bc585.png)

**Comment by bluenevus** [comment]
png and pdf as an option is fine too but definitely need excel and csv and the export in the same place that all apps are located

**Comment by LAlexMHllc** [comment]
Then make the current button function as expected to download png or pdf.
Include another export button for text; when clicked, display modal for user to choose Excel or csv.

Screenshot Example

![spreadsheet_downloads_2](https://user-images.githubusercontent.com/11938477/174386693-d7dd45ff-aaf1-4ca2-80ae-b62c17323639.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
1. Clicking "Cancel" on Export X modal should cancel/Close modal.
2. The file downloaded when Excel button is clicked has an error when opened.

Screenshot Example

![spreadsheet_download_X_modal_issues](https://user-images.githubusercontent.com/11938477/175060733-61074fc7-c744-4081-adf3-bb54cbcde964.png)

**Comment by b-solution** [comment]
@bluenevus I'v fixed this issue, can you please test it again and let me know if it's not working.
