### ISSUE TITLE
sidekiq is going to redis on 127.0.0.1 even though cable.yml configured redis to use a remote host

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#654]
sidekiq is going to redis on 127.0.0.1 even though cable.yml configured redis to use a remote host

sidekiq.service doesn't have anything calling redis and neither does sidekiq.yml So I'm not sure where its configured to go out to 127.0.0.1 vs where cable.yml is pointing

![image](https://user-images.githubusercontent.com/3675043/174395783-d4045e8a-a2a6-488e-aa93-8d86b5923e40.png)

**Comment by bluenevus** [comment]
this is also happening with the new calendar function.  its not reading cable.yml for its redis connection.  please address so anything calling redis is using cable.yml config

**Comment by bluenevus** [comment]
the calendar aspect is not fixed.  its still going to 127.0.0.1 for redis and NOT reading cable.yml for the redis connection url

**Comment by b-solution** [comment]
@bluenevus Can you please test it.
