### ISSUE TITLE
Mindmap: The Description box should remain open until the user clicks Close. Text should be automatically saved every 1000 ms OR when Close clicked.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#665]
Screenshot Example

![mindmap_Description_save_close](https://user-images.githubusercontent.com/11938477/174824831-73705b5a-f376-4db6-b188-8f1c817b4387.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this, can you please test it again and let me know if it's not working.
