### ISSUE TITLE
Kanban: Action buttons for newly added Stage should have default colors

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#667]
Screenshot Example

![kanban_added_stage_action_buttons_changed_from_default_color](https://user-images.githubusercontent.com/11938477/174864950-53866e6d-2203-422b-880a-e8789caff581.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
