### ISSUE TITLE
whiteboard: as a users I would like to change the layer of an object forward or backward

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#673]
objects seem to be drawn in layers.  as such I would like to 

1. Send Backward
3. Bring Forward

which will bring an object one layer forward or send an object one layer back

**Comment by b-solution** [comment]
@bluenevus I've this feature. Please test it and let me know if its working for you

**Comment by b-solution** [comment]
@bluenevus I've added this feature. Kindly test it and let me know if it is working for you.

**Comment by LAlexMHllc** [comment]
The Forward/Backward feature works.
Would prefer if the object would remain selected after forward/backward click, so the user does not have to reselect the object.

**Comment by b-solution** [comment]
@LAlexMHllc If the select remain. User will not be able to see changes there fore we have to do this, if you want us to do like you want we will do but it will cause this.

**Comment by LAlexMHllc** [comment]
Closing, fixed
