### ISSUE TITLE
Mindmap: When trying to edit node title, sometimes removed characters will automatically display again

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#686]
Screenshot Example

![mindmap_removing_node_Title_characters_automatically_displayed_again](https://user-images.githubusercontent.com/11938477/176021730-98eefc00-8ac4-4667-adea-43efc9aa7f6b.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Better, but still needs work. When inputing, sometimes a single letter that was entered will display for a second, then disappear. When removing, sometimes a single removed letter will reappear after a second,

**Comment by LAlexMHllc** [comment]
Seems to be fixed on Central Node.
Still needs to be fixed for Child Node.

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
I probably just need to type slower
