### ISSUE TITLE
TreeChart and FlowMap: Clicking Delete node should delete that node and its descendants

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#699]
When delete is clicked on a node that has a descendant without title, only that descendant gets deleted.
Screenshot Example on TreeChart

![treeChart_clicking_Delete_Node_should_delete_node_and_its_children](https://user-images.githubusercontent.com/11938477/176718372-62a9cf6a-5e07-4aec-b19b-9599eda126d5.png)

Screenshot Example on FlowMap

![FlowMap_clicking_Delete_Node_should_delete_node_and_its_descendants](https://user-images.githubusercontent.com/11938477/176729073-fa899a57-4312-4ba7-8abe-658cb0d9acbd.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
