### ISSUE TITLE
Notepad map: Alignment button should be active dependent upon selected text

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#717]
Screenshot Example

![spreadsheet_alignment_selector_should_include_drop-down_icon](https://user-images.githubusercontent.com/11938477/178015258-66f02233-f29b-4001-b31a-786b1eec294b.png)

**Comment by b-solution** [comment]
@LAlexMHllc I have changed some design. Please tell me if it's not working for you

**Comment by LAlexMHllc** [comment]
Only one alignment should be active a time for selected text or input text.
Screenshot Example

![notepad_only_one_alignment_active_at_a_time_for_selected_or_input_text](https://user-images.githubusercontent.com/11938477/182199944-58e82d15-a819-4ae1-96ab-809d10dd56a4.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example that active alignment buttons don't always apply to selected text

![notepad_text_alignment_buttons_active_when_text_selected](https://user-images.githubusercontent.com/11938477/182457776-f50113cc-6c59-43f3-af9c-e82805118436.png)

**Comment by LAlexMHllc** [comment]
NOTE: Changed Title of issue, since drop-down was replaced with alignment selector buttons

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
