### ISSUE TITLE
Since users collaborating on a map may be assigned to fill in a Node Title, duplicate default node title should not be allowed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#720]
After deleting a node, sometimes a node included after Add Child Node clicked has a duplicate default title. This may cause an issue when users collaborate.
Screenshot Example

![new_node_Title_should_not_have_duplicate_default_name](https://user-images.githubusercontent.com/11938477/178787778-099c12ff-50b2-407d-93c5-fe7483d5e4df.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Will you please test it.

**Comment by LAlexMHllc** [comment]
After deleting a node, new node numbers are too high. Probably should just increment each new node number by 1, even after a node was deleted. Don't repeat a number already used, regardless if the node number was used for a deleted node.
EXAMPLE
Existing node numbers are 1 through 10. User deletes nodes with number 4 and 5. The next node added should be Node Number 11.

Screenshot Example

![treechart_node_numbers_too_high](https://user-images.githubusercontent.com/11938477/179837713-049d0761-8877-4543-9e7a-542fbcd5ae16.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example where no nodes were deleted, yet the Title node number is too high.
Should just increase the next Add Child Node Title number by 1, whether any node was deleted on not.

![node_Title_number_too_high_should_just_increment_by_1_each_Add_Child_Node_click](https://user-images.githubusercontent.com/11938477/180238374-eaf73d7c-4a1a-4566-bd66-3d97cd621bfa.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Closing, fixed
