### ISSUE TITLE
TreeMap: Sometimes after deleting a node, the Node Title Error modal will display when Add Child Node is clicked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#721]
Screenshot Example
![treemap_sometimes_node_title_error_displays](https://user-images.githubusercontent.com/11938477/178779642-335887d2-ca71-47a7-93fc-9def7854b29b.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this. Can you please test it again.
