### ISSUE TITLE
Spreadsheet: Fix the start of Row 1, since overlaps with column header row

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#727]
Screenshot Example

![spreadsheet_fix_start_of_row_1__issues_seen_on_downloads](https://user-images.githubusercontent.com/11938477/179532399-93797bda-1d08-474d-a8ab-355b6c5cd03a.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
