### ISSUE TITLE
Notepad: Ordered List numbers and Unordered List bullets should be the same size as corresponding text

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#731]
Screenshot Example

![notepad_ordered_and_unordered_lists_should_be_same_size_as_text](https://user-images.githubusercontent.com/11938477/179793590-11c735c2-39bb-44bf-a427-38522f5c41e5.png)

**Comment by b-solution** [comment]
@LAlexMHllc I have fixed this issue. Please tell me if it's not working for you

**Comment by LAlexMHllc** [comment]
Still needs to be fixed for Large and Huge text
Screenshot Example

![notepad_fix_size_of_lists_for_Large_and_Huge](https://user-images.githubusercontent.com/11938477/182198086-d3a8de2c-2a96-4930-a51d-d745c79be486.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Bullets with Text size Huge should be larger and centered vertically
Screenshot Example

![notepad_Huge_bullets_should_be_larger_and_vertically_centered](https://user-images.githubusercontent.com/11938477/191042869-8fbd7fb6-ccf8-4515-99c9-8aac378ec997.png)

**Comment by LAlexMHllc** [comment]
Numbered List still needs to be fixed for Text size Small (too large) and Huge (too small)
Screenshot Example

![notepad_Small_and_Huge_numbered_list_needs_to_be_fixed](https://user-images.githubusercontent.com/11938477/191044453-f6335526-11ea-426c-9698-260c2a47ba89.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please again test it.

**Comment by LAlexMHllc** [comment]
Size Huge for Bulleted List and Numbered List - DONE

Size Small for Numbered List - Still needs to be fixed
Screenshot Example

![notepad_numbered_list_size_Small_fix](https://user-images.githubusercontent.com/11938477/191303415-a8ccbdd3-dfd6-4b75-b323-e92813be8f85.png)

**Comment by LAlexMHllc** [comment]
After further testing, the issue occurs sometimes when scaling from one Font Size to another.
Screenshot Example when scaling does not display correctly

![notepad_numbered_and_bulleted_list_change_Size_sometimes_does_not_scale_correctly](https://user-images.githubusercontent.com/11938477/192549001-8c7af432-d031-4a58-b309-0488e961c3ca.png)

Screenshot Example when scaling does display correctly

![notepad_numbered_and_bulleted_list_change_Size_Normal_to_Large_CORRECT](https://user-images.githubusercontent.com/11938477/192549084-9e11f2a6-6c91-4aa0-900f-c4daf89cc538.png)

**Comment by b-solution** [comment]
@LAlexMHllc It's working good, Can you please check it again and let me know if it's not working for you.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/196169874-08822cb6-0511-4b55-bc66-317f24fba81e.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/196169714-f008ff76-7c94-4a78-b55d-0f58ea8dabbf.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/196169989-0b56f5b1-510a-42b9-9427-1c4f9eb9d67f.png">

**Comment by LAlexMHllc** [comment]
When the size selected is not "Normal", then another size is selected, the numbers and bullets do not consistently match the selected text size.
EXAMPLE
When the text is size "Small", then the user selects size "Large"

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
