### ISSUE TITLE
Spreadsheet: Fix column sort icons

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#733]
Screenshot Example

![spreadsheet_fix_column_sort_icons](https://user-images.githubusercontent.com/11938477/179815062-17f36143-e747-495e-8b42-2521e7f2e7eb.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Sort icons still look the same

**Comment by b-solution** [comment]
@LAlexMHllc Can you please suggest any icon you want.
<img width="813" alt="image" src="https://user-images.githubusercontent.com/5988861/180221863-7a4294d8-e5e2-4fea-9d8d-5900d23281e3.png">

**Comment by LAlexMHllc** [comment]
@b-solution The issue is the direction of the sort icon does not match the sorted results.
triangle up should be for ASC sort
triangle down should be for DESC sort

Screenshot Example

![spreadsheet_sort_arrows](https://user-images.githubusercontent.com/11938477/180229290-b95bce69-82c7-4ff3-ab06-1dbb8cf7acae.png)

**Comment by b-solution** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/5988861/180941082-38412a06-9c6c-4391-8f35-79ecd5804e47.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/5988861/180941094-9ac831df-cfbe-4067-a563-d4ebd396db64.png">
