### ISSUE TITLE
replace microhealth logo with msuite logo

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#735]
![mSuite-color-horizontal@4x](https://user-images.githubusercontent.com/3675043/179848576-283e755c-b646-4fc7-a08a-155b7854983d.png)
![mSuite-color-stacked@4x](https://user-images.githubusercontent.com/3675043/179848589-3822eeb5-885a-489c-9c96-17301ae6e87a.png)

replace favicon too please

**Comment by bluenevus** [comment]
![mSuite-logo-only@4x](https://user-images.githubusercontent.com/3675043/179849090-abe9a22d-e7ca-417b-9ba5-5246967c7300.png)

logo only for favicon and stuff

**Comment by bluenevus** [comment]
[favicon_package_v0.16.zip](https://github.com/MicroHealthLLC/mSuite/files/9144759/favicon_package_v0.16.zip)

**Comment by bluenevus** [comment]
![mSuite-color-stacked](https://user-images.githubusercontent.com/3675043/179849620-05871701-da71-4aa8-b7e4-1e0b181be84e.svg)

svg versions if you need it

![mSuite-color-horizontal](https://user-images.githubusercontent.com/3675043/179849624-40953141-b621-4ec7-b9ff-69cd1032f05e.svg)

**Comment by b-solution** [comment]
@bluenevus I've changed the logo and favicon as you wished please see the image and let me know if you wanted the same. If it's ok for you, I'll update.
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/5988861/179924448-e833d77d-920e-4262-b845-91a06eedc84f.png">

**Comment by bluenevus** [comment]
that looks good to me.  can you make the msuite a bit bigger to fit into the space better?

**Comment by b-solution** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/5988861/180191593-f5540b29-17c5-4681-92f7-652551776036.png">
