### ISSUE TITLE
TreeChart and FlowMap: Fix issues with Toggle descendants shown/hidden

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#739]
1. Descendants should only be shown/hidden when the Toggle icon is clicked, instead of anywhere else on the node.
NOTE: The toggle icon does not change direction unless it is clicked.
2. The color of the children node text should not change after being toggled shown/hidden
3. The color of the node connector lines should not change color after being toggled shown/hidden

Screenshot Example

![treechart_flowmap_Toggle_issues](https://user-images.githubusercontent.com/11938477/180235554-4609f31d-7bc5-4b2c-82dc-32cdf5dea15b.png)

**Comment by b-solution** [comment]
@LAlexMHllc can you please retest it and let me know if its not working for you.
