### ISSUE TITLE
TreeMap: Should put more space between node Title and its children, so Title will be easier to read

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#741]
Screenshot Example

![treemap_should_put_more_space_between_node_Title_and_its_children](https://user-images.githubusercontent.com/11938477/180268653-d8a5460f-b799-4519-9bc4-b9ed295415cf.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've added more space between nodes, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Update did not fix the issue; only caused issue of unfilled space.
Screenshot Example

![treemap_spacing_issue](https://user-images.githubusercontent.com/11938477/180498422-e741413a-c84e-4d2b-a72a-5535e964e0a6.png)

**Comment by b-solution** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/181764615-1292e2e1-c9cc-4867-8a1d-16693df5733e.png">

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.
Screenshot Example

![treemap_with_more_space_between_Title_and_child_nodes_3](https://user-images.githubusercontent.com/11938477/181781574-1762f248-a685-498a-ad0d-de1d256fb57c.png)

**Comment by LAlexMHllc** [comment]
Should be able to fit two lines for Title.
Screenshot Example

![treemap_need_room_for_2_line_Title](https://user-images.githubusercontent.com/11938477/182421345-4328215d-a67e-485c-823d-6001664fc5ce.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
