### ISSUE TITLE
When "Cancel" is clicked on the Color Picker, the styles for the node action buttons should revert

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#742]
Screenshot Example

![Color_Picker_Cancel_clicked_node-style_buttons_should_have_reverted](https://user-images.githubusercontent.com/11938477/180271752-1d1b9f60-6bfd-40a2-98de-305a2b067abb.png)

**Comment by b-solution** [comment]
@LAlexMHllc I have fixed this issue. Please test it and tell me if it is working for you.
