### ISSUE TITLE
TreeMap: Clicking "Cancel" after selecting coordinated color should function

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#743]
Clicked color coordination for map, then clicked "Cancel" button. Node colors did not revert.
Screenshot Example

![treemap_clicking_cancel_should_function_after_selecting_color-coordinated](https://user-images.githubusercontent.com/11938477/180273874-b16abaea-1d34-47bb-b483-5fe7e8f0a167.png)

Even after clicking "Reset", the Color Picker stayed open. Clicking "Cancel" still did not function,
Screenshot Example

![treemap_clicking_cancel_should_function_after_selecting_color-coordinated_2](https://user-images.githubusercontent.com/11938477/180274707-f1d61aa1-e307-434c-a63d-d510110b3645.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue.
