### ISSUE TITLE
Spreadsheet: Not editing for a few minutes, yet map still in Editing mode instead of Saved mode

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#744]
Screenshot Example

![spreadsheet_not_updating_several_minutes_yet_still_editing_mode](https://user-images.githubusercontent.com/11938477/180283563-15b53d63-428d-42f5-9873-7f718a848ebf.png)

**Comment by b-solution** [comment]
@LAlexMHllc I'v fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, since Save displays after enter or tab key is pressed
