### ISSUE TITLE
Spreadsheet: Deleting selected rows and columns should stick

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#746]
Selected row(s), then selected "Delete selected rows". The rows are temporarily removed, then the default number of rows displays again.
Screenshot Example

![spreadsheet_delete_selected_rows](https://user-images.githubusercontent.com/11938477/180302671-24c94c0b-7c27-49f2-9939-f815bf36b3b6.png)

![spreadsheet_delete_selected_rows_returns_default_after_a_few_seconds](https://user-images.githubusercontent.com/11938477/180295304-70d6d6f3-91af-45f0-8fee-daed3418ff36.png)

**Comment by LAlexMHllc** [comment]
When user Saves the map after inserting/deleting, then shares the link, the other user will see the default column/rows.
When the user that removed the rows/columns reloads the browser, the spreadsheet displays with default column rows, even when not collaborating in real time.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixes this issue, Can you please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Deleted rows and column, clicked Save. When reload clicked, the columns and rows reverted.

**Comment by LAlexMHllc** [comment]
Closing, fixed
