### ISSUE TITLE
oath2 1.4x is at end of life and needs upgrade to version 2

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#751]
You have installed oauth2 version 1.4.10, which is EOL.
No further support is anticipated for the 1.4.x series.

OAuth2 version 2 is released.
There are BREAKING changes, but most will not encounter them, and upgrading should be easy!

**Comment by b-solution** [comment]
Hey @bluenevus, we're not using **oauth2** in mSuite.2
