### ISSUE TITLE
TreeMap: All nodes should have action buttons

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#752]
Screenshot Example

![treemap_some_child_nodes_missing_action_buttons](https://user-images.githubusercontent.com/11938477/180499775-68390cfe-0b9b-43ea-a999-ac4b8d1ede35.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
