### ISSUE TITLE
TreeMap: After clicking "Add Child Node" when several children exists, made some children invisible (not shown)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#753]
Screenshot Example before Add Child Node clicked again.

![treemap_with_5_child_nodes_before_another_add_child_node_click](https://user-images.githubusercontent.com/11938477/180503749-59e83f72-e8e7-4d38-b49c-7be25af09268.png)

Screenshot Example after Add Child Node clicked again, some child nodes are not visible.

![treemap_with_5_child_nodes_after_another_add_child_node_click_some_children_not_visible](https://user-images.githubusercontent.com/11938477/180503814-3ab93ad9-b515-4ba6-afc0-ac8d579c165f.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
