### ISSUE TITLE
Whiteboard: Clicking "Cancel" on Color Picker should not remove the selected object.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#758]
Sometimes clicking "Cancel" on Color Picker removes the selected object.
Screenshot Example

![whiteboard_clicking_Cancel_on_ColorPicker_should_not_remove_object](https://user-images.githubusercontent.com/11938477/180828995-f542f236-cb39-435a-a45d-66c67312508b.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please check it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
