### ISSUE TITLE
Kanban: Should fix new Stage default Title

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#759]
Screenshot Example

![kanban_fix_new_stage_default_title](https://user-images.githubusercontent.com/11938477/180831277-56f0c45f-b1d2-45d6-9f69-fb7986a22f73.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
"Stage NaN" was not used for Title in today's test, but the Stage # should still start from 1 (example: "Stage 1") when new map is created or Reset is clicked.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
