### ISSUE TITLE
Whiteboard: Object added to board should display on shared map

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#760]
Object does not consistently display on shared map after being included on the board, then getting deselected.
Screenshot Example

![whiteboard_text_added_should_display_on_shared_map](https://user-images.githubusercontent.com/11938477/180835208-1cc5c398-2472-4e90-acb5-c3866cd212e8.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![whiteboard_sometimes_missing_newly_deselected_object](https://user-images.githubusercontent.com/11938477/180836912-623cb6bb-b41d-4e07-a845-bf28660f205f.png)

**Comment by LAlexMHllc** [comment]
Both users added an object to the board, and neither object displays on the other user's screen.
Screenshot Example

![whiteboard_sometimes_missing_newly_deselected_object_2](https://user-images.githubusercontent.com/11938477/180839496-54db70a9-11a9-4c04-9dda-bb69ab0b98c7.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
