### ISSUE TITLE
Whiteboard: Position of updated object should display on shared screen.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#762]
Sometimes changing object position does not update on shared screen.
Screenshot Example

![whiteboard_changed_object_position_did_not_update_shared_screen](https://user-images.githubusercontent.com/11938477/181087095-3042988d-febb-4beb-b1f3-221e8c8c61ae.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
