### ISSUE TITLE
Whiteboard: Object should not be selected when "Select" button is inactive

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#763]
Screenshot Example

![whiteboard_object_should_not_be_selected_when_Select_button_inactive](https://user-images.githubusercontent.com/11938477/181089353-58982887-5145-4b80-a98c-72a40dbcea26.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
