### ISSUE TITLE
Whiteboard: Clicking "Cancel" on the Color Picker should not deselect the object

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#764]

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Now if you create a new object the map in real time will be one step behind but it will match its steps afterwards. So in this way, i think it will be okay. Can you please test and let me know.

**Comment by LAlexMHllc** [comment]
Clicking Cancel on Color Picker did not deselect object on latest test
