### ISSUE TITLE
TreeMap: Node buttons should not overlap Title.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#766]
Screenshot Example

![treemap_node_buttons_should_not_overlap_title](https://user-images.githubusercontent.com/11938477/181263731-1aafbb55-0de5-431c-b8aa-f88ce1a18944.png)

**Comment by b-solution** [comment]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/5988861/181274914-8f7f266a-b161-46a6-aa74-b7f05fef9cf3.png">

@LAlexMHllc If I set title like this, will it be okay for you?

**Comment by LAlexMHllc** [comment]
@bluenevus Please respond to comment above

**Comment by LAlexMHllc** [comment]
Title should remain centered, and just break to more lines as needed.

**Comment by bluenevus** [comment]
like carriage return...but we should limit to 2 lines because it can't be a sentence

**Comment by LAlexMHllc** [comment]
Should move the Title down so that the buttons will not overlap the title when the container is narrower width.
Screenshot Example
NOTE: Same screenshot from Issue #741.

![treemap_with_more_space_between_Title_and_child_nodes](https://user-images.githubusercontent.com/11938477/181566068-bb7c605b-e7c9-4d23-9ec1-23efd615e46b.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it and let me know.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/181763960-a0cc0ce4-e2cc-4786-a281-1809b6c5b2d8.png">

**Comment by LAlexMHllc** [comment]
Still need more space between node buttons and Title
Screenshot Example

![treemap_still_needs_more_space_between_node_buttons_and_Title](https://user-images.githubusercontent.com/11938477/181780295-8260d6ce-86a7-4ea5-85b6-481e7b72c4a9.png)

**Comment by LAlexMHllc** [comment]
Still needs more space
Screenshot Example

![treemap_more_space_between_node_buttons_and_Title](https://user-images.githubusercontent.com/11938477/182211531-ac972d77-c140-4e34-8b91-afd8393b3677.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/5988861/182314160-0dfb2c8b-47b4-435f-8ae5-d71f07e07d07.png">

**Comment by LAlexMHllc** [comment]
Closing, fixed
