### ISSUE TITLE
Whiteboard: Object displayed selected as if invisible (or white), and Color Picker did not display correctly afterwards.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#776]
Screenshot Example

![whiteboard_text_displayed_invisible_color_picker_did_not_display_correctly](https://user-images.githubusercontent.com/11938477/182201807-7e4c308b-7921-4866-9281-ebca97c051e6.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Screenshot Examples with some steps that can lead to this issue

![whiteboard_white_previously_selected_after_Text_1](https://user-images.githubusercontent.com/11938477/182931770-446fbdb5-7379-42cc-9bf2-04388ae67504.png)

![whiteboard_white_previously_selected_after_Text_2](https://user-images.githubusercontent.com/11938477/182931825-694d13ee-e8a6-4cf5-9f4e-93ef3cbf10e6.png)

![whiteboard_white_previously_selected_after_Text_3](https://user-images.githubusercontent.com/11938477/182931850-5ad88e4f-5218-4d7e-b2d3-acac70e4010c.png)

![whiteboard_white_previously_selected_after_Text_4](https://user-images.githubusercontent.com/11938477/182931875-1750a025-ab58-4b55-a497-a40ffa2d470d.png)

**Comment by LAlexMHllc** [comment]
Closing, since seems fixed
