### ISSUE TITLE
Kanban map: Updated stage attributes should be in sync while users collaborate in real time

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#779]
Screenshot Example

![kanban_updated_stage_attributes_should_be_in_sync_on_collaboration](https://user-images.githubusercontent.com/11938477/182443336-a730eb8b-e0ea-4dff-a7d0-add7d3b348f1.png)

**Comment by LAlexMHllc** [comment]
After updating a stage Title, the stage Title on the shared screen updated as well, but also reverted the background color.
Screenshot Example

![kanban_after_updating_stage_Title__shared_screen_updates_but_reverts_to_default_background_color](https://user-images.githubusercontent.com/11938477/182445065-49be5835-0701-4038-a4b4-41b19a9952d3.png)

**Comment by b-solution** [comment]
@LAlexMHllc It’s working good on my side, you may have a look on demo.

https://www.loom.com/share/e069a97070034178b4a6d0e0f5cec8bb

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.
Screenshot Example

![kanban_stage_backgroundColor_change_not_in_sync](https://user-images.githubusercontent.com/11938477/182898711-e74dfe5b-91f3-4e71-ad8b-f14981e38bac.png)

**Comment by LAlexMHllc** [comment]
When Reset is clicked, the Stage background colors should also reset on the shared map for other users.
Screenshot Example

![kanban_stage_backgroundColor_change_not_in_sync_after_Reset](https://user-images.githubusercontent.com/11938477/183667724-cc743cb0-83de-4ab4-aaf5-178b6cc835ed.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Still does not consistently update background on shared screen, and still does not always change background colors to default after Reset on shared screens.
Screenshot Examples

![kanban_backgrounds_should_update_all_screens_real_time_collab](https://user-images.githubusercontent.com/11938477/186688799-29b2b45a-e4be-497a-ab47-3163665a0e37.png)

![kanban_backgrounds_should_revert_default_after_reset_clicked_real_time_collab](https://user-images.githubusercontent.com/11938477/186689316-045921a0-51ca-4d75-a5a7-a905cb1d9f35.png)

**Comment by LAlexMHllc** [comment]
Closing, since seems fixed
