### ISSUE TITLE
When browser reload is clicked on map screen, sometimes the index screen displays instead; even when map was saved.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#780]
Screenshot Example

![clicking_browser_reload_on_map_screen_should_reload_map_instead_of_displaying_index](https://user-images.githubusercontent.com/11938477/182654402-14f5933b-7a65-4a16-94b9-10762861ade1.png)

**Comment by b-solution** [comment]
@LAlexMHllc It’s working good on my side, you may have a look on demo.
https://user-images.githubusercontent.com/5988861/182807590-b8c3a21e-68ff-4c76-b6df-500d921bb000.mp4

**Comment by b-solution** [comment]
@LAlexMHllc It’s working good on my side, you may have a look on demo.
https://www.loom.com/share/b23bfce727c24c389d62ccc940f2dab6

**Comment by LAlexMHllc** [comment]
Click a map box on the index.
On map screen Save Public.
Click reload.
After screen reloads, click reload again.

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Still not fixed

**Comment by b-solution** [comment]
@LAlexMHllc can you please test it again.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
