### ISSUE TITLE
[Notepad - Numbered List] In an indented lettered subsection, a subsequent return from a blank subsection does not reset to a numbered list in the next line (Microsoft Word behavior)

### ISSUE THREAD

**Issue by andrewtran249** [MicroHealthLLC/mSuite#785]
![image](https://user-images.githubusercontent.com/106859528/182897778-b8a2ec3e-0a11-4139-8c44-ecbb288cf2ee.png)

**Comment by b-solution** [comment]
Notepad serves as a basic text editor and lacks many of the advanced formatting features available in word processors such as Microsoft Word. Consequently, certain formatting behaviors, particularly those related to numbered and bulleted lists, may not be as sophisticated in Notepad as in dedicated word processing software.
To achieve specific behaviors in Notepad, users may need to manually perform certain tasks, as demonstrated in the provided demo video. For example, to create a numbered list where each item automatically generates a subsequent sub-item, you can follow these steps:

- Begin by typing '1.' Notepad will automatically recognize it as a numbered list.
- After entering the content for the first item, press the 'Tab' key. This action signals Notepad to create a child item under the initial number.
- Proceed to type the content for the second item, and Notepad will intuitively recognize it as a sub-item (e.g., 'a.').
- Notepad's behavior extends further in list creation. After entering a sub-item, such as 'a.,' pressing the 'Enter' key will prompt Notepad to intuitively recognize and generate the next sub-item as 'b.' This automatic inference continues, simplifying the list creation process.
- Additionally, if you choose to delete a sub-item, Notepad dynamically adjusts and interprets the sequence. For instance, removing 'b.' will signal Notepad to recognize the subsequent line as the next item under the primary number. This flexibility in interpretation extends to subsequent lines, making it user-friendly and adaptable.

https://github.com/MicroHealthLLC/mSuite/assets/5988861/2b6e53f1-65f4-484d-a9b6-a7c59ad47f9a

**Comment by LAlexMHllc** [comment]
@andrewtran249  Included more detail in User Guide https://github.com/MicroHealthLLC/mSuite/wiki/User-Guide#numbered-list-bulleted-list-and-multilevel-list-indent-and-outdent

**Comment by LAlexMHllc** [comment]
Closing, since this is not MS Word. See User Guide.
