### ISSUE TITLE
Spreadsheet: Selected columns or rows should remain selected when the context menu displays

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#788]
Selected columns or rows should remain selected when the context menu is displayed, regardless of the order of selection.

Screenshot Example for columns

![spreadsheet_multi-selected-consecutive_columns_should_remain_selected_when_context_menu_displays](https://user-images.githubusercontent.com/11938477/183101688-51bf18bf-2da5-46e0-b71f-8ee1b8eb6d28.png)

Screenshot Example for rows

![spreadsheet_multi-selected-consecutive_rows_should_remain_selected_when_context_menu_displays](https://user-images.githubusercontent.com/11938477/183101674-c26bfe47-2d4c-49b2-a4fb-c5883596da68.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
The order of selected columns/rows makes a difference whether all the columns/rows remain selected whenever the context menu displays. See the screenshots above.

**Comment by b-solution** [comment]
@LAlexMHllc Actually, the issue we are facing is, when we select column/row top to bottom or left to right (in a forward way) the functionality works perfectly as it is available in the free version of the jspreadsheet-ce package. On the other hand, when we select a column/row from bottom to top or right to left (in a backward way) the context menu unselects the selected columns/rows. That feature is available in the paid version of the jspreadsheet-ce package.

**Comment by LAlexMHllc** [comment]
Closing, since feature is only available in the paid version.
