### ISSUE TITLE
Sometimes when reload was clicked while collaborating on a map, the shared screen returned to index.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#790]
Screenshot Example

![reload_clicked_while_collaborating_caused_index_display_on_shared_map](https://user-images.githubusercontent.com/11938477/183128528-25c65a7f-696c-4610-aa1e-4f03120ad891.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again, I've fixed this issue.

**Comment by LAlexMHllc** [comment]
Closing, fixed
