### ISSUE TITLE
Kanban map: Background colors for Stages should update according to selected color scheme

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#791]
Whether collaborating in real time or not, color scheme updates for Stages do not function correctly.

Screenshot Example after updating without collaboration in real time.

![kanban_select_color_scheme_ColorPicker_did_not_update_correctly](https://user-images.githubusercontent.com/11938477/183674182-04a8fe0b-f83e-419d-8111-04337702ecd3.png)

__________________________________________________________________________________________________________

Screenshot Example after updating and Reset during real time collaboration.

![kanban_select_color_scheme_ColorPicker_click_Update_1](https://user-images.githubusercontent.com/11938477/183674351-921a478b-aba2-4ca9-8038-6d7c156d52ac.png)

![kanban_select_color_scheme_ColorPicker_click_Update_2](https://user-images.githubusercontent.com/11938477/183674413-15e786e3-127c-4949-b837-0c9abf9b353b.png)

![kanban_select_color_scheme_ColorPicker_click_Update_3](https://user-images.githubusercontent.com/11938477/183674461-2a781d93-0cc1-4bf5-a90f-2b255b69c1d7.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
