### ISSUE TITLE
Update top menu buttons and move position of Editing/Edited text below.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#796]
Top menu buttons on ALL maps

![top_menu_button](https://user-images.githubusercontent.com/11938477/184215104-44fec206-80db-4a61-96ca-2be7ef01fe03.png)

1. Make top menu buttons smaller by decreasing padding around icons. The icon size is fine, just don't need as much white space.
2. Change color of button icons on hover (like Comments button), instead of displaying text.
3. Include button description in tooltip on hover (like Comments button). 
For "Save" button, tooltip should be "Expires date". (example: Expires Sun Jul XX 2022)
See Issue #594
5. Move editing text below the top menu buttons. "Lasted Edited by User" should display far right. Since more than one user can be editing at once, text should be, "Editing by: User 1, User 2, User 3".

Screenshot Example

![top_menu_button_changes_edited_text_below](https://user-images.githubusercontent.com/11938477/184176691-ff91ef73-c7d1-46bd-9e22-ddc130e20dd0.png)

Screenshot Example of button normal and on hover color with tooltip (like Comments button)

![exports_regular_and_on_hover_color_with_tooltip](https://user-images.githubusercontent.com/11938477/184183301-ce413c33-5567-4c40-8941-e583d1773b1d.png)

**Comment by LAlexMHllc** [comment]
Button size and padding still need to be fixed (smaller). Leave the size of button icons alone.
Fix tooltip for Save icon; abbreviate day and month, fit on one line.
Should have consistent space below buttons for Edit lines. Map should not jump around when Edit Line(s) are shown/hidden.

Screenshot Example

![top_menu_button_changes_edited_text_below_2](https://user-images.githubusercontent.com/11938477/184404177-a8ac2346-df62-4c17-9ceb-80640d20b8b4.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if anything update :) .
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/184474608-361adf72-196e-4be1-9698-e6610e7e2a63.png">

**Comment by LAlexMHllc** [comment]
Closing, fixed
