### ISSUE TITLE
WhiteBoard: New object should actually be included on all shared maps

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#799]
Screenshot Example where new object did not actually get included until it got deselected, and therefore did not display on shared maps.

![whiteboard_new_object_not_included_on_shared_yet_edited_by_displays_1](https://user-images.githubusercontent.com/11938477/184377569-51f20a0e-45b0-4e77-b25c-7aa548f1cfe3.png)

![whiteboard_new_object_not_included_on_shared_yet_edited_by_displays_2](https://user-images.githubusercontent.com/11938477/184377642-17dadc18-0264-4155-8119-432861e6da72.png)

![whiteboard_new_object_not_included_on_shared_yet_edited_by_displays_3](https://user-images.githubusercontent.com/11938477/184377666-32995232-1173-49d9-8187-bbaa47fd9e1c.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example where new object was deselected and still did not display on shared map until "Select" button was clicked inactive.

![whiteboard_new_object_not_included_on_shared_yet_edited_by_displays_6](https://user-images.githubusercontent.com/11938477/184394323-35094b45-6587-493a-91b3-14f0be8a3f39.png)

![whiteboard_new_object_not_included_on_shared_yet_edited_by_displays_7](https://user-images.githubusercontent.com/11938477/184394351-29a16b40-686c-4d7b-94f8-2cfc2bcdbc10.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Please test it and let me know if it is working for you.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed after last update.
Screenshot Example where Text was included on one screen flashed displayed on the shared screen, then disappeared from shared screen.

![whiteboard_text_flashed_onto_shared_screen_then_disappeared](https://user-images.githubusercontent.com/11938477/184898954-3c36334f-bd43-4831-b866-6ac7a4226bae.png)


NOTE: For another test, after clicking Text, the object displayed on shared screen, then disappeared from all shared maps.

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
