### ISSUE TITLE
WhiteBoard: Clicking Confirm Reset should reset shared maps in real time

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#805]
Screenshot Example

![whiteboard_userA_clicks_confirm_Reset_success_but_shared_map_did_not_reset](https://user-images.githubusercontent.com/11938477/184650995-2fcd16b3-1166-4d77-a40d-c8d05325fe53.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it again and let me know if it is working for you

**Comment by LAlexMHllc** [comment]
Still does not consistently Reset all shared maps

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
