### ISSUE TITLE
All maps: Edit Text should not display until an actual change was made to the map.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#817]
Edit Text displays before actual changes to the map:
- For all maps, when Title is clicked.
- Mindmap: When canvas background is clicked, or a top menu button is clicked.
- Whiteboard: When canvas background is clicked.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this, Can you please test it again.

**Comment by LAlexMHllc** [comment]
TreeChart and FlowMap should not update Editing By and Last Edited By text when node Title was not updated (like TreeMap)

Screenshot of TreeMap (CORRECT)

![treemap_does_not_udpate_edited_when_node_Title_not_updated](https://user-images.githubusercontent.com/11938477/191325032-ddf1a665-e486-4ba4-9fac-436988aeb403.png)

Screenshot of TreeChart (INCORRECT)

![treechart_should_not_udpate_edited_when_node_Title_not_updated](https://user-images.githubusercontent.com/11938477/191325805-07c98f7e-39e0-4a09-b161-bb303730fa9e.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
