### ISSUE TITLE
Notepad: Input not in sync on shared map

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#821]
Missing words, transposed characters, and missing attributes.
Screenshot Example

![notepad_not_in_sync_transposed_characters_missing_words_and_attributes](https://user-images.githubusercontent.com/11938477/185157665-ce64cf3b-3fcc-4e89-b088-55a1d23ba469.png)

**Comment by LAlexMHllc** [comment]
User created map, input text, styled text, clicked Save, then shared URL.
The word was missing letters and all styling.
Screenshot Example

![notepad_not_in_sync_cut_off_word_letters_none_of_the_attributes_after_Save_map_then_share_URL](https://user-images.githubusercontent.com/11938477/185416898-386dc060-dee6-4d0f-b468-701a69cc8c52.png)

**Comment by bluenevus** [comment]
It was sycncing somewhat before the last notepad update.  It completely stopped syncing after the last notepad update.  The only way it syncs between two users is a manual refresh
