### ISSUE TITLE
TreeMap: When node "Title" is not in edit mode, the background should be transparent.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#822]
User clicked on Title, then clicked off of Title. Should function like TreeChart and FlowMap.
Screenshot Example

![treemap_node_Title_background_color_should_be_transparent_when_not_Edit_mode](https://user-images.githubusercontent.com/11938477/185199059-f209886f-9708-432d-a05d-2ad32873b2bd.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.
The last node Title clicked off still remains white, until another node Title is clicked, map edit, save, etc. occurs.
Screenshot Examples

![treemap_node_Title_background_color_should_be_transparent_when_not_Edit_mode_2](https://user-images.githubusercontent.com/11938477/185412327-f4dd5249-fd25-4b83-af31-1c489262f81a.png)

**Comment by LAlexMHllc** [comment]
When a node Title is in edit mode and the user clicks anywhere outside of the main parent node  (examples: header area, white margins around main parent node), the Title exits edit mode, but the background remains white, instead of changing to transparent.

Screenshot Example of node Title in Edit mode

![treemap_node_Title_background_color_should_be_transparent_when_not_Edit_mode_3](https://user-images.githubusercontent.com/11938477/185940433-a62b822e-165c-4390-81b6-05c8b25b0145.png)

Screenshot Example after user clicked off node Title in an area outside of main parent node.

![treemap_node_Title_background_color_should_be_transparent_when_not_Edit_mode_4](https://user-images.githubusercontent.com/11938477/185940836-b34b10b0-98eb-428e-bc76-96823ed49813.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Closing, fixed
