### ISSUE TITLE
Spreadsheet: Missing "Rename this column"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#834]
User used to be able to Rename a Column Header.
Screenshot Example

![Spreadsheet_rename_this_column](https://user-images.githubusercontent.com/11938477/186727535-4d63cf3f-7848-4aac-a0ae-e83049294c14.png)

Screenshot Example of missing Column selector "Rename this column"

![spreadsheet_missing_Rename_this_column](https://user-images.githubusercontent.com/11938477/186728240-c11d78c6-71c9-43dd-af33-cd207a4d645d.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
