### ISSUE TITLE
Kanban: Clicking "Reset" when collaborating in real time should reset all shared maps

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#838]
Screenshot Example

When Reset is clicked, the Stage background colors should also reset on the shared map for other users.
Screenshot Example

![kanban_stage_backgroundColor_change_not_in_sync_after_Reset](https://user-images.githubusercontent.com/11938477/183667724-cc743cb0-83de-4ab4-aaf5-178b6cc835ed.png)

**Comment by LAlexMHllc** [comment]
For this Example, the screen which "Reset" was clicked did not reset, but the shared screen did reset.
When a "Color Picker" button was clicked on a Stage node, the Color Picker did not display; the background reverted to default color after link was clicked a second time.
When a "Delete" Stage link was clicked, that Stage was not removed on that screen, but was removed on the shared screen.
Screenshot Example

![kanban_clicked_Reset_on_shared_map_1](https://user-images.githubusercontent.com/11938477/187267224-459ff200-73f2-4a8f-a82f-4c9d1be20c26.png)

![kanban_clicked_Reset_on_shared_map_2](https://user-images.githubusercontent.com/11938477/187267245-fcc1d59d-bba7-408c-8d63-8754611dd8fb.png)

![kanban_clicked_Reset_on_shared_map_3](https://user-images.githubusercontent.com/11938477/187267282-1009d470-e323-4300-9c16-e5006ef5feb7.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it again and let me know if it is working for you.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
