### ISSUE TITLE
Calendar: Should include "Undo" and "Redo" buttons on header bar

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#846]
Screenshot Example

![header_buttons_undo_redo](https://user-images.githubusercontent.com/11938477/187727733-e9897188-882d-4e7f-9606-e9e82b3d5b68.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've added undo and redo, can you please test it and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Closing, since Undo and Redo buttons exist on header bar
