### ISSUE TITLE
Calendar: Should always have option to include Time with Date on Event Forms

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#848]
Sometimes unable to include Time with Date on Event Forms
Screenshot Example

![calendar_sometimes_unable_to_include_Time_on_Event_Forms](https://user-images.githubusercontent.com/11938477/187740347-2335d3cf-4591-4868-9211-c782ad3839e8.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
