### ISSUE TITLE
unable to add a node to a mindmap

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#851]
after working on a mindmap, I left the mindmap and came back to it later and it doesn't allow me to add any more nodes giving me this console error

![image](https://user-images.githubusercontent.com/3675043/187823139-07d46c93-3957-429b-8e93-3c83d744db95.png)

**Comment by b-solution** [comment]
@bluenevus, will you please retest it with latest pull and tell me if it is not working for you. I've tested this issue and found that there is not any error on my side.

**Comment by LAlexMHllc** [comment]
I was able to add nodes on my tests.

**Comment by bluenevus** [comment]
doesn't work.  if you pull from the central idea it will work, if you pull from a node off the central idea you get the error and it also depends on how big the tree is.   Any resizing of the screen will mess up the pull definitely browser and to a lesser degree using the zoom tool

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
