### ISSUE TITLE
mindmap central idea not updating

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#852]
if i type something in central idea for the mindmap sometimes it just doesn't update and stays central idea

othertimes it will save then you can't edit it and it stays what ever it saved

sometimes I can come back and it will update the central node but after updating it, I cant edit it again

**Comment by LAlexMHllc** [comment]
Sometimes Central Idea text is not updated when map is saved. When user clicks reload browser, the old central node text displays.

**Comment by LAlexMHllc** [comment]
Closing, since seems fixed
