### ISSUE TITLE
Mindmap: Fix node attachment error and wrong node attachment issue caused as a result of the error.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#860]
Fix error that displays after failed attempt to attach node to Child Node: "Cannot read properties of null (reading 'left')"
Fix child attachment to wrong node error

Screenshot Example of active child node that user wants to attach add Child Node

![mindmap_user_tries_to_draw_from_child_node_1](https://user-images.githubusercontent.com/11938477/188172847-425ba87b-b7e2-47c0-9f3d-030eec8982ba.png)

Screenshot Example of error that displays when Child Node attachment fails

![mindmap_error_Cannot_read_properties_of_null_reading_left](https://user-images.githubusercontent.com/11938477/188173104-805bd2da-3dac-4ac1-a1fb-1e729640a6d0.png)

Screenshot Example of active Main Node user tries to attach Child Node to after failed attempt to attach to Child Node

![mindmap_user_tries_to_draw_from_main_node_1_after_null_reading_left_error_for_child_node](https://user-images.githubusercontent.com/11938477/188173329-06a6990d-aaff-4ccd-801b-27b8687e9772.png)

Screenshot Example of Child Node that got attached to the previously active Child Node that caused the error instead of the Main Node

![mindmap_user_tries_to_draw_from_main_node_1_gets_attached_to_child_node_that_caused_error](https://user-images.githubusercontent.com/11938477/188173478-71b1bca0-9d2f-4440-a299-0970b498c427.png)

**Comment by LAlexMHllc** [comment]
See related Issue #859

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working for you. :)

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
