### ISSUE TITLE
Calendar: Update default Start Time and End Time on Add Event Form

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#867]
Screenshot Example of Add Event when displayed with "Month" view selected
Start Time should have current time displayed in 15 minute block as default time
End Time should be 15 minutes past the Start Time as default

![calendar_Month_view_double_click_to_Add_Event_default_Start_make_CurrentTime_End_make_plus15min](https://user-images.githubusercontent.com/11938477/188709236-aa9fb405-cbb6-4c49-909a-0ec6159e2418.png)

For "Week" and "Day" views, when Add Event form displays when Time area was clicked: The Start Time should display the time clicked (as 15 minute block), with End Time that time + 15 minutes as default.
When "All Day" spot was clicked, then Start Time and End Time should remain 00:00 as default.

Screenshot Example of "Week" view

![calendar_Week_view_double_click_to_Add_Event_default_Start_make_CurrentTime_End_make_plus15min_except_AllDay](https://user-images.githubusercontent.com/11938477/188709254-fade8ae7-08bb-4f61-8706-834d7270430d.png)

Screenshot Example of "Day" view

![calendar_Day_view_double_click_to_Add_Event_default_Start_make_CurrentTime_End_make_plus15min_except_AllDay](https://user-images.githubusercontent.com/11938477/188709264-1ebdd6f4-9b92-40bf-a8b3-63e9baf56cfb.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, see related Issue #900 and Issue #901
