### ISSUE TITLE
Calendar - Month view: Should display more than one entry at a time on Events Listing modal that displays when # more link is clicked.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#868]
Screenshot Example

![calendar_click_more_link_modal_should_display_more_than_one_entry_on_list_at_once](https://user-images.githubusercontent.com/11938477/188725286-abdb2287-49c0-4c5f-a050-133ef8b3f577.png)

Screenshot Example of more than one Event on the Listing

![calendar_click_more_link_modal_should_display_more_than_one_entry_on_list_at_once_2](https://user-images.githubusercontent.com/11938477/188727859-d808bdfb-fc05-4c90-b2f7-39e8d77cff95.png)

**Comment by bluenevus** [comment]
only applies to the month view because the others pick the time on the week view or the day view correctly right now

**Comment by LAlexMHllc** [comment]
Should include close button "X" on modal. Should style Date/Day like single event display.
Screenshot Example

![calendar_click_more_link_modal_should_display_more_than_one_entry_on_list_at_once_3](https://user-images.githubusercontent.com/11938477/188910306-fe3f55d9-05cd-4793-8804-2254216f9c2e.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
