### ISSUE TITLE
Spreadsheet: Deleting selected column(s) should stick

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#873]
Screenshot Example

![spreadsheet_Delete_selected_columns_should_stick](https://user-images.githubusercontent.com/11938477/188947236-08bc9c9a-1a7c-4616-87b4-9792dece307f.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
