### ISSUE TITLE
Spreadsheet: Fix inconsistent behavior when user tries to input into cell.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#874]
Sometimes inputting into selected cell is difficult.
- Sometimes characters typed into active cell does not display until user clicks off. 
- Sometimes characters display, then disappear when the cell is active; content displays after cell is inactive.
- Sometimes all characters clicked do not display after user finishes inputting into cell.
- Sometimes cell content disappears, even after map saved.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
