### ISSUE TITLE
Spreadsheet: Selecting "Insert a new column before/after" should stick

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#875]
Selecting Insert a new column before/after temporarily inserts the column, then the spreadsheet removes the column.
Screenshot Example

![spreadsheet_insert_a_new_column_before_after_should_stick](https://user-images.githubusercontent.com/11938477/188954404-0ec43a9b-2428-492e-9e76-f30e2e79103c.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
