### ISSUE TITLE
configure failed password lockout time

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#878]
after X number failed password attempts, as an administrator under settings I would like to configure the lock out period of that document such as 15 minutes.  So I would have a setting for the number of failed password attempts that allows me to also configure the duration of lockout.

I would also like to be able to configure the number of lockout events on the document that results in a permanent lock of the file.  That is I can configure the quantity of lock out events in a specific time period that will permanently lock out the file that can only be unlocked under administration but still cannot change the document password because only the owner can know that and if they don't, its simply lost and unrecoverable because there are no such things as password resets on a file for security purposes.

**Comment by zachegnermh** [comment]
Fixed
