### ISSUE TITLE
when performing a poll the system errors out

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#883]
$
I, [2022-09-09T11:23:43.243504 #50314]  INFO -- : [e2075428-e763-4a94-940e-d50d4ab8a09a] Processing by MindmapsController#update as JSON
I, [2022-09-09T11:23:43.243585 #50314]  INFO -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   Parameters: {"name"=>"this_is_a_test_poll", "mindmap"=>{"canvas"=>"{\"title\":\"te$
D, [2022-09-09T11:23:43.246521 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[36mMindmap Load (0.4ms)^[[0m  ^[[1m^[[34mSELECT  `mindmaps`.* FROM `mindma$
D, [2022-09-09T11:23:43.248076 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[35m (1.1ms)^[[0m  ^[[1m^[[35mBEGIN^[[0m
D, [2022-09-09T11:23:43.249337 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[36mMindmap Exists (0.4ms)^[[0m  ^[[1m^[[34mSELECT  1 AS one FROM `mindmaps$
D, [2022-09-09T11:23:43.251392 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[35m (1.3ms)^[[0m  ^[[1m^[[35mCOMMIT^[[0m
D, [2022-09-09T11:23:43.252501 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[35m (0.6ms)^[[0m  ^[[1m^[[35mBEGIN^[[0m
D, [2022-09-09T11:23:43.253086 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[36mCACHE Mindmap Exists (0.0ms)^[[0m  ^[[1m^[[34mSELECT  1 AS one FROM `mi$
D, [2022-09-09T11:23:43.254763 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[36mMindmap Update (0.7ms)^[[0m  ^[[1m^[[33mUPDATE `mindmaps` SET `updated_$
D, [2022-09-09T11:23:43.260213 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[35m (5.1ms)^[[0m  ^[[1m^[[35mCOMMIT^[[0m
D, [2022-09-09T11:23:43.260585 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a] [ActionCable] Broadcasting to web_notifications_channel1170: {:message=>"Mindmap Upd$
D, [2022-09-09T11:23:43.266680 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[36mActiveStorage::Attachment Exists (0.4ms)^[[0m  ^[[1m^[[34mSELECT  1 AS $
D, [2022-09-09T11:23:43.267854 #50314] DEBUG -- : [e2075428-e763-4a94-940e-d50d4ab8a09a]   ^[[1m^[[36mNode Load (0.4ms)^[[0m  ^[[1m^[[34mSELECT `nodes`.* FROM `nodes` WHERE $
I, [2022-09-09T11:23:43.268598 #50314]  INFO -- : [e2075428-e763-4a94-940e-d50d4ab8a09a] Completed 200 OK in 25ms (Views: 0.4ms | ActiveRecord: 10.4ms)
I, [2022-09-09T11:23:49.278185 #50313]  INFO -- : [bc286757-53fa-4d48-8e49-1d6977da90c7] Started PATCH "/msuite/80zh5ApVCqbBPg4.json" for 72.66.6.217 at 2022-09-09 11:23:49 $
I, [2022-09-09T11:23:49.279318 #50313]  INFO -- : [bc286757-53fa-4d48-8e49-1d6977da90c7] Processing by MindmapsController#update as JSON
I, [2022-09-09T11:23:49.279420 #50313]  INFO -- : [bc286757-53fa-4d48-8e49-1d6977da90c7]   Parameters: {"name"=>"this_is_a_test_poll", "mindmap"=>{"canvas"=>"{\"title\":\"te$
D, [2022-09-09T11:23:49.281851 #50313] DEBUG -- : [bc286757-53fa-4d48-8e49-1d6977da90c7]   ^[[1m^[[36mMindmap Load (0.5ms)^[[0m  ^[[1m^[[34mSELECT  `mindmaps`.* FROM `mindma$
I, [2022-09-09T11:23:49.282610 #50313]  INFO -- : [bc286757-53fa-4d48-8e49-1d6977da90c7] Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.5ms)
F, [2022-09-09T11:23:49.283168 #50313] FATAL -- : [bc286757-53fa-4d48-8e49-1d6977da90c7]
F, [2022-09-09T11:23:49.283213 #50313] FATAL -- : [bc286757-53fa-4d48-8e49-1d6977da90c7] TypeError (no implicit conversion of String into Integer):

![image](https://user-images.githubusercontent.com/3675043/189386052-cc9e2510-3a06-44c1-a7a4-f9784e2c3db5.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know if it's not working.
