### ISSUE TITLE
show results on poll keeps spinning but doesn't display any data

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#884]
![image](https://user-images.githubusercontent.com/3675043/189386330-064b6fa9-f9ed-4ff4-b370-a5d52a432a71.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Closing, since Poll Results displays
