### ISSUE TITLE
the poll url should be automatically generated

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#886]
the reules for creating a unique url is way to complicated.  greater than 10 characters, less than 20 and its too complicated for users, so this should be an automatic url

![image](https://user-images.githubusercontent.com/3675043/189386970-f24ca459-f488-4f9f-8834-779b2439e335.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
