### ISSUE TITLE
poll should be responsive rather than require scroll bars partciularly when the resolution is as high as 1080p

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#887]
![image](https://user-images.githubusercontent.com/3675043/189387745-ea68f3fa-f427-4f96-816a-4ecfc660afd8.png)

**Comment by bluenevus** [comment]
not sure why its iframed but I expected to scroll on the page vs scroll within a frame on the page so we can capitalize on the real estate

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know if it's not working.
