### ISSUE TITLE
there shouldn't be 2 poll titles

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#888]
the title as on every map is the title.  we only need a black box for a description that isn't required and we should grab the title of the poll from the typical location users enter a title

![image](https://user-images.githubusercontent.com/3675043/189388120-c5cbb692-398a-4f0d-83ec-83cfa9328158.png)

**Comment by bluenevus** [comment]
this should be the poll title 
![image](https://user-images.githubusercontent.com/3675043/189388159-0f7ae96e-2e79-4376-bafc-bb489631bf94.png)

then we can remove this 
![image](https://user-images.githubusercontent.com/3675043/189388197-ce3502ca-e43c-4144-8fb2-14c581c52b42.png)


and just leave a box like so that says description that isn't required. 

![image](https://user-images.githubusercontent.com/3675043/189388251-615dc56b-33b2-4599-b552-08142555a54d.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know if it's not working.
