### ISSUE TITLE
Poll map: Error displayed on User Poll screen generated after "FINALIZE" button clicked on Poll Collaborator screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#894]
Screenshot Example

![poll_clicked_finalize_error_screen_displayed](https://user-images.githubusercontent.com/11938477/189423493-8ef3b5f6-c3e9-4ab1-b3fe-17ef207686d2.png)

**Comment by bluenevus** [comment]
The button should read "Launch Poll"
