### ISSUE TITLE
Calendar: Should remain displayed in "Week" or "Day" view when selected, even when events do not exist.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#899]
When no event exists, selecting "Week" or "Day" view only displays as expected for a second, then returns to "Month" view.

Screenshot Example when "Week" view is selected

![calendar_user_selected_Week_view_when_no_events_exist](https://user-images.githubusercontent.com/11938477/189701349-308f01a9-08d2-4046-8299-eaa47ed4f2af.png)

![calendar_should_remain_in_Week_view_when_selected](https://user-images.githubusercontent.com/11938477/189701385-4bd47754-8f3f-4b0e-9b57-45baee683ad4.png)

_____________________________________________________________________________________________

Screenshot Example when "Day" view is selected

![calendar_user_selected_Day_view_when_no_events_exist](https://user-images.githubusercontent.com/11938477/189699080-46c16fde-82e9-4c58-8ae3-2785e7dd8857.png)

![calendar_should_remain_in_Day_view_when_selected](https://user-images.githubusercontent.com/11938477/189699879-6020be9e-95f4-4dd2-aa02-c6001ae50458.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
