### ISSUE TITLE
Calendar - Add Event Form: Change default End Time to one hour past Start Time

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#901]

**Comment by LAlexMHllc** [comment]
Month view: Add Event - DONE

Week and Day view: Add Event - Still Needs To Be Fixed

**Comment by b-solution** [comment]
@LAlexMHllc In week view and day view this is a feature that user can create event of custom time gap by dragging on the time grid do you want me to remove it and rather force user to only be able to get a one hour gap between start time and end time on Add Event Form?

**Comment by LAlexMHllc** [comment]
@b-solution User should not be forced to only have one hour gap on Week and Day views.
The default End Time should just be set at one hour gap past default Start Time. User should still be able to adjust both times on the form. User should still be able to drag Event on the time grid to adjust times as well.

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Closing, fixed
