### ISSUE TITLE
Poll map: Poll URL should be required

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#910]
Screenshot Example

![poll_url_should_be_required](https://user-images.githubusercontent.com/11938477/189941951-598ea49d-7001-424b-bdf5-99a2d93f4a85.png)

**Comment by bluenevus** [comment]
the url should be automatically generated, random and like the rest of mpath, they can't change it because its a security problem with urls that users can guess

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
