### ISSUE TITLE
Poll map: Preview mode should display Description text (when exists); and only allow maximum selected options for questions.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#911]
Screenshot Example of Poll Form

![poll_form_test_1_description_and_Q1](https://user-images.githubusercontent.com/11938477/189948575-89450a48-dcfd-49c1-bb3c-c9c478b43d75.png)

![poll_form_test_1_Q2](https://user-images.githubusercontent.com/11938477/189948603-4f9cee46-d26e-4893-890c-b087c84d7998.png)

Screenshot Example of Poll Preview

![poll_form_test_1_preview](https://user-images.githubusercontent.com/11938477/189949028-eb9946fb-f8e6-4a81-b4bd-2742818e9d95.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
When Description text exists, included in Preview - DONE

Maximum allowable selected options on Preview - Still needs to be done

Screenshot Example

![poll_preview_maximum_allowable_selected_options](https://user-images.githubusercontent.com/11938477/190242726-e321f673-9306-4eb2-82a4-0dc89158e606.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Can only select one radio button per question  - DONE

Can still select more than Allowable selectable answers - Still needs to be fixed
Screenshot Example

![poll_preview_maximum_allowable_selected_options_2](https://user-images.githubusercontent.com/11938477/191330950-3c7fffb6-8b33-461a-861d-91aa26cc75aa.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
