### ISSUE TITLE
Poll map: Clicking "LAUNCH POLL" should allow a user to take the Poll, instead of displaying message, "TIME FOR VOTES IS UP !!!"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#912]
Screenshot Example

![poll_preview_click_LAUNCH_POLL](https://user-images.githubusercontent.com/11938477/189950691-a3f79b9a-29bf-45f5-be96-fbd58b516b7e.png)
![poll_user_message_POLL_TIME_IS_UP_message](https://user-images.githubusercontent.com/11938477/189950886-559cd370-7bab-4af2-ba24-6145059c3b80.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, since message no longer displays
