### ISSUE TITLE
Notepad: Clicking "B" active should change selected text to Bold

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#921]
Issue returned after last update.
Screenshot Example

![notepad_text_styled_B_should_be_bold_2](https://user-images.githubusercontent.com/11938477/190670119-22614f4a-fd10-4f69-a9ab-261643b3ce02.png)

**Comment by bluenevus** [comment]
see the original issue that was fixed previously.  https://github.com/MicroHealthLLC/mSuite/issues/520

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again.

**Comment by LAlexMHllc** [comment]
Closing, fixed
