### ISSUE TITLE
as a user, I would like to take any document that I created and duplicate it into a new document and new url

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#922]
If someone takes the time to create a document in any of the maps as a template, they may want to reuse it to create a new document with others filling it in.  For example, they create a calendar for a process.  They may want to use that to create a new calendar based on a template they created

so if an icon was here to duplicate or create new from the existing 
![image](https://user-images.githubusercontent.com/3675043/190682868-a65331db-701b-4bdc-9e9c-c99f8a234d2c.png)

they would get a new tab with the same document and content in a new url to use and modify so they don't have to keep creating something very similar from scratch or change their "template" version

**Comment by b-solution** [comment]
@bluenevus @LAlexMHllc, We have removed duplicate functionality from Treechart, Treemap, Flowmap and Todo because their behaviour was not as expected while duplicating them. We are working on it after fixing them we will again re publish this functionality.

**Comment by b-solution** [comment]
> @bluenevus @LAlexMHllc, We have removed duplicate functionality from Treechart, Treemap, Flowmap and Todo because their behaviour was not as expected while duplicating them. We are working on it after fixing them we will again re publish this functionality.

I've fixed this issue for all maps, @LAlexMHllc Can you please test it and let me know if it's not working.
