### ISSUE TITLE
calendar view display 2 lines

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#923]
Given there appears to be space for one more extra line, can we add one more line so you can at least see 2 items on the calendar view

![image](https://user-images.githubusercontent.com/3675043/190685023-fba2774f-672c-47d8-b10b-d7761ed89add.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
MONTH VIEW
- When 2 events are on the same day: Both events are listed on that day, without # more link
- When 3+ events are on the same day: Only two events are listed on that day, with (total - 2) more link

Screenshot Example of what is expected

![calendar_Month_view_with_2_or_more_events_same_day](https://user-images.githubusercontent.com/11938477/191311504-dab66158-4ee0-4d3a-9b3b-40d1b04ca42a.png)

**Comment by LAlexMHllc** [comment]
Closing, since updates just loaded and issue was fixed
