### ISSUE TITLE
Notepad: During real time collaboration, when user scrolls down the screen, the map should not automatically return to the top of the screen.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#925]
Screenshot Example before user scrolls to bottom of screen

![notepad_before_user_scrolls_to_bottom_of_screen](https://user-images.githubusercontent.com/11938477/190708098-f3dd523b-9aa5-435c-a314-ff552d8fefd3.png)

Screenshot Example after user scrolled to the bottom of the screen

![notepad_after_user_scrolls_to_bottom_of_screen](https://user-images.githubusercontent.com/11938477/190708103-af2dd3b0-f832-418a-9f1a-ce76e7bba5be.png)

Screenshot Example after screen automatically jumped back to the top after a second; so user is unable to add/edit input below what is in view.

![notepad_after_user_scrolls_to_bottom_of_screen_2](https://user-images.githubusercontent.com/11938477/190709174-616c5346-8432-45c2-8b78-1ead0452d922.png)

NOTE: User can scroll using vertical scrollbar, the arrow down key, or the page down button,

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issues can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
