### ISSUE TITLE
Notepad: During real time collaboration, "Editing and Last Edited" text keeps updating, even when none of the users are editing.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#926]
More than one user has the map open at the same time. After one of the users inputs, the "Editing and Last Edited" text keeps adjusting, even when none of the users continue to edit the map.

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and if the issue remains can you please mention the steps in detail by which you encountered this problem. Thanks

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
