### ISSUE TITLE
Poll Results: Should not include result "null" for answer option(s) not selected; when no expiration date, just put "None"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#939]
Screenshot Example

![poll_results_should_not_include_null_for_nonselected_answer_options__use_None_for_no_expiration](https://user-images.githubusercontent.com/11938477/191290203-4c868bbe-8dc3-4f03-a1d9-9413e0b08d35.png)

**Comment by LAlexMHllc** [comment]
Poll text has "None" when there is no Expiration Date - DONE

The Answer Options that were not checked still need to be part of the Poll Results
Screenshot Example
So for this Poll Results: the first Question should have 1 for Yes and 0 for No; the second Question should also include 0 for each color that was not checked.

![poll_map_all_answer_options_should_be_included_in_Poll_Results](https://user-images.githubusercontent.com/11938477/192021436-7f3c5e8e-0586-49ea-a521-6503f1bc55c9.png)

**Comment by b-solution** [comment]
> @LAlexMHllc, Are you looking something like this?
> 
> <img alt="image" width="912" src="https://user-images.githubusercontent.com/5988861/199017583-ba47ea96-77bd-41a8-a53f-399bd78a88e1.png">

@LAlexMHllc I am confused about your answer can you please describe in detail with examples of what you want.
Currently if there are answers that are not selected by anyone taking the poll those answers will be shown in the None column and user can see them, as you can see in the screenshot above

**Comment by LAlexMHllc** [comment]
Yes, should include all answers.

![current_poll_results_missing_answers_not_selected](https://user-images.githubusercontent.com/11938477/199264733-6fd1e37c-a0cf-4ee6-b781-cba1b5f830de.png)

**Comment by b-solution** [comment]
@LAlexMHllc Kindly guide me about this task what exactly you want.

**Comment by LAlexMHllc** [comment]
@bluenevus  If the way it function now is fine, then this issue can be closed. Otherwise, how do you want this to function?

**Comment by LAlexMHllc** [comment]
@b-solution Using "None" as in your screenshot is fine.

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it and let me know if it is working for you

**Comment by b-solution** [comment]
@LAlexMHllc this has been already done.

> > @LAlexMHllc, Are you looking something like this?
> > <img alt="image" width="912" src="https://user-images.githubusercontent.com/5988861/199017583-ba47ea96-77bd-41a8-a53f-399bd78a88e1.png">
> 
> @LAlexMHllc I am confused about your answer can you please describe in detail with examples of what you want. Currently if there are answers that are not selected by anyone taking the poll those answers will be shown in the None column and user can see them, as you can see in the screenshot above

**Comment by LAlexMHllc** [comment]
It is AGREED that non-selected poll answer options SHOULD display with "None", as in your screenshots.
Currently, poll answer options that were not selected do not display under Poll Results.

Screenshot Example

![poll_results_without_all_options_and_None](https://user-images.githubusercontent.com/11938477/210813827-c70968ed-5cc1-4412-8364-4ee16766898d.png)

**Comment by LAlexMHllc** [comment]
Closing, since "None" exists for answer options unselected after last push
