### ISSUE TITLE
as a user, I would like to change the color of the  highlight on the calendar

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#941]
![image](https://user-images.githubusercontent.com/3675043/191322974-d2490540-7592-4469-81d4-226ce948765d.png)

right now its defaulted to green but would like to change the color on edit

![image](https://user-images.githubusercontent.com/3675043/191323131-14e96198-fbfb-41db-bc23-e01e0c25cc5c.png)

![image](https://user-images.githubusercontent.com/3675043/191323183-c7ad5b52-a541-402b-9a7b-df39092054f7.png)

**Comment by b-solution** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/192209437-c225d3e0-c396-4bf4-ba77-350e311c5481.png">
@LAlexMHllc Can you please test this.

**Comment by LAlexMHllc** [comment]
Closing, fixed
