### ISSUE TITLE
on the to do list if I navigate away from one item to the next, I shouldn't have to click save...that should be automatic

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#945]
![image](https://user-images.githubusercontent.com/3675043/191552755-85b6a94d-ffb0-4af6-bd27-f65cbea88353.png)

**Comment by bluenevus** [comment]
it will not let me pass until I click the green save button.  Hitting carriage return does nothing when it should just save when I go to the next task or click save or hit the carriage return

**Comment by LAlexMHllc** [comment]
Closing, fixed
