### ISSUE TITLE
in kanban for an oversized list, the horizontal scroll doesn't show up at the bottom

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#951]
![image](https://user-images.githubusercontent.com/3675043/191858445-0883e60b-d0b9-4cd3-92d9-15266577eb80.png)

no way to get to the additonal stages

**Comment by b-solution** [comment]
@LAlexMHllc

**Comment by b-solution** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/192292163-928dfbe5-2c71-419e-af78-8beaa8f68e9d.png">

**Comment by LAlexMHllc** [comment]
Closing, fixed
