### ISSUE TITLE
anywhere there is a text box, I'm unable to click my mouse to a position, I have to use the keyboard to navigate

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#952]
every text box with text a user is able to click to a position in the text box, in front of a letter, after a letter after a word, before a word.  However that isn't possible. you have to use your keyboard

also, in these text boxes you can't highlight anything  with the mouse.  double click doesn't work I can pull the cursor over a word to highligh and its in just about every textbox in every type of map making editing really hard

![image](https://user-images.githubusercontent.com/3675043/191859922-194960f8-2a93-4cf6-b29f-ef7f70cbe1f6.png)

**Comment by b-solution** [comment]
@bluenevus @LAlexMHllc I've worked on this, can you please test it again and let me know if it's not working.
