### ISSUE TITLE
Poll map - New Poll and Poll Vote screens: Download file should include Title and user answers

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#956]
Can not tell which radio is checked for answer
Even though there is a difference between checked answers and unchecked answers when more than one allowable option is selected, it's hard to see.

Screenshot Example

![poll_map_dowloaded_file](https://user-images.githubusercontent.com/11938477/192017466-4a725501-a34e-4665-9afa-3146819f957d.png)

**Comment by LAlexMHllc** [comment]
Export Image or PDF sometimes does not function, regardless if Poll Form or Poll Results are displayed.
Screenshot Example

![export_pollmap_image_or_pdf_loop](https://user-images.githubusercontent.com/11938477/197041090-dc55f9b6-a2e0-48f5-afe3-0e56bdbf7266.png)

**Comment by LAlexMHllc** [comment]
Poll map - New Poll - FIXED

Poll map - Poll Vote: Image nor PDF got created/downloaded - Still needs to be fixed
Screenshot Example

![poll_vote_click_export](https://user-images.githubusercontent.com/11938477/198357663-42311bc5-8dbb-47c8-9aa5-24d26111e916.png)

![poll_vote_click_export_2](https://user-images.githubusercontent.com/11938477/198357683-1cace028-5c08-4eef-b66f-29de7b1b6a38.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Please test it and tell me if it is working for you.

**Comment by LAlexMHllc** [comment]
Closing, fixed
