### ISSUE TITLE
Calendar map: Event Forms should require Title with both Times selected OR All Day checked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#957]
Since event does not successfully submit without Title AND ((Start Time and End Time filled in) OR (All Day checked)), the "Add" and "More Options" buttons should be disabled without them.

Screenshot Example of buttons enabled without Times selected or All Day checked

![calendar_event_form_buttons_should_remain_disabled_without_Title_and_either_both_Times_or_All_Day](https://user-images.githubusercontent.com/11938477/192043553-7437b422-4ddd-4431-b10d-0094b38ddbed.png)

![calendar_Event_Form_should_require_Times_filled_or_All_Day_checked_for_buttons_to_be_active](https://user-images.githubusercontent.com/11938477/192042267-df4e50d8-7f77-4a27-8e57-22fd050f64aa.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Closing, fixed
