### ISSUE TITLE
Calendar map: Since "Description" is not required, clicking enabled "More options" button should display the Add Recurrence modal

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#958]
Screenshot Example

![calendar_Event_Form_Add_Occurrence_should_display_without_Description_filled_when_More_Options_clicked](https://user-images.githubusercontent.com/11938477/192042577-a5592216-bf09-46ac-b9a4-25754d7b9222.png)

**Comment by LAlexMHllc** [comment]
See related Issue #957

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this already can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
