### ISSUE TITLE
Calendar map: Save Recurrence of multi-day event should save as multi-day event instead of single-day event

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#965]
Screenshot Example

![calendar_click_edit_multi-day_event](https://user-images.githubusercontent.com/11938477/192346932-98e00f15-abec-42d4-b9c7-1d07ba37f301.png)

![calendar_click_edit_multi-day_event_clicked_More_options](https://user-images.githubusercontent.com/11938477/192346963-58c4d44f-99e2-4019-bde9-008d980789b7.png)

![calendar_click_edit_multi-day_event_clicked_More_options_1_Month_Continue](https://user-images.githubusercontent.com/11938477/192346997-6ccb7571-b624-4e19-9029-dfaafdfa4963.png)

![calendar_click_edit_multi-day_event_clicked_More_options_1_Month_Continue_update](https://user-images.githubusercontent.com/11938477/192347034-a59dfbeb-2139-4e41-ac7c-b6e00834a037.png)

![calendar_multi-day_event_recurrence_should_save_as_multi-day_instead_of_1_day](https://user-images.githubusercontent.com/11938477/192347095-7b007a5c-8fb3-4d23-963c-cc6eb3488d32.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, Can you please test it again and let me know if it's working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
