### ISSUE TITLE
[MindMap] Hide and Reveal Child Node Glitch

### ISSUE THREAD

**Issue by andrewtran249** [MicroHealthLLC/mSuite#966]
The hide and reveal function in MindMap is inconsistent. It will more often require multiple clicks to both hide and reveal child nodes.

https://user-images.githubusercontent.com/106859528/192600527-fbd69d59-0c9b-4519-acdc-65ba1c4cb7b2.mp4

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Can you please test it again and let me know if it's not working.
