### ISSUE TITLE
Kanban map: Background color of Stages should persist after drag 'n drop

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#970]
Screenshot Example of drag 'n drop STAGE 2

![kanban_drag_n_drop_stage_should_keep_background_color_on_shared_screen](https://user-images.githubusercontent.com/11938477/192863177-2aba2dbc-d6dd-4f44-943e-23e0875abba4.png)

_______________________________________________________________

Screenshot Example after drag 'n drop STAGE 2 again

![kanban_drag_n_drop_stage_should_keep_background_color_on_shared_screen_2](https://user-images.githubusercontent.com/11938477/192864819-3effc8e9-57fe-4562-97e2-44fc5e012ae8.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, fixed
