### ISSUE TITLE
Notepad map: Clicking "Continue" to confirm "Reset" should reset map(s)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#974]
Screenshot Example

![notepad_click_Continue_to_confirm_Reset](https://user-images.githubusercontent.com/11938477/193064520-26e46458-a4f6-4ebc-becf-6a5e65f4e66f.png)

![notepad_click_Continue_to_confirm_Reset_2](https://user-images.githubusercontent.com/11938477/193064531-d502ed26-668f-4380-a561-f5d79fcefdb3.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.
