### ISSUE TITLE
Notepad map: Possible to fix display of formula for download file?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#978]
Screenshot Example

![notepad_formula_display_in_download](https://user-images.githubusercontent.com/11938477/193118542-f9b13a29-f258-4202-8090-392a7390a7e3.png)

**Comment by b-solution** [comment]
@LAlexMHllc It is not possible because data is encoded in binary in every editor therefore every editor read it according to its base.
